#!/usr/bin/env python3
"""add_b1_expansion_packs.py — B1-Erweiterung: 12 neue Vokabelpakete (144 Wörter).

Quelle: Jins TOPIK-Vokabelliste (~1.260 Einträge, KO/EN) + 국립국어원-Phrasebook-
Boxvokabeln — kuratiert (Duplikate zu den 558 Bestandswörtern entfernt, Partikeln/
Endungen/Zähleinheiten ausgeschlossen), DE-Glossen und alle Beispielsätze neu
verfasst (App ist Deutsch-zuerst; Quellen sind KO/EN-only).

⚠️ Von Claude verfasst — Jin (Muttersprachler) sollte KO/DE stichprobenartig
prüfen (Projekt-Konvention: generieren → Muttersprachler-Review → commit).

Konventionen (siehe add_b2_environment_pack.py, plus id-Spalte von 2026):
- 15 Spalten inkl. explizite id `vocab_b1_NNNN` (Fortsetzung ab aktuellem Max).
- Letzte 3 Wörter jedes Pakets sind Review-Bosse.
- Keine Kommata in Textfeldern (CSV-Konvention der Content-Factory).

Idempotent: bereits vorhandene koreanische Wörter werden übersprungen.
Nutzung: python tools/content_factory/add_b1_expansion_packs.py --write
"""
import csv
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
VOCAB = os.path.join(ROOT, "assets", "data", "korean_vocab.csv")

LEVEL = "B1"
ID_PREFIX = "vocab_b1_"

# pack_id → (topic_de, [ (ko, rom, de, pos_de, ex_ko, ex_de, en, pos_en, ex_en) ])
# Reihenfolge = pack_order; die letzten 3 jedes Pakets werden Bosse.
PACKS = [
    ("b1_media_culture_1", "Medien & Kultur", [
        ("광고", "gwanggo", "Werbung", "Nomen",
         "요즘 이 광고가 아주 인기예요.", "Diese Werbung ist zurzeit sehr beliebt.",
         "advertisement", "Noun", "This ad is very popular these days."),
        ("방송", "bangsong", "Sendung", "Nomen",
         "어제 그 방송 봤어요?", "Hast du gestern die Sendung gesehen?",
         "broadcast", "Noun", "Did you watch that broadcast yesterday?"),
        ("뉴스", "nyuseu", "Nachrichten", "Nomen",
         "아침마다 뉴스를 봐요.", "Ich schaue jeden Morgen die Nachrichten.",
         "news", "Noun", "I watch the news every morning."),
        ("배우", "baeu", "Schauspieler", "Nomen",
         "제가 좋아하는 배우가 나와요.", "Mein Lieblingsschauspieler tritt auf.",
         "actor", "Noun", "My favorite actor appears."),
        ("공연", "gongyeon", "Aufführung", "Nomen",
         "주말에 공연을 보러 가요.", "Am Wochenende gehe ich zu einer Aufführung.",
         "performance", "Noun", "I am going to see a performance this weekend."),
        ("무대", "mudae", "Bühne", "Nomen",
         "가수가 무대에 올라갔어요.", "Der Sänger ging auf die Bühne.",
         "stage", "Noun", "The singer went on stage."),
        ("문학", "munhak", "Literatur", "Nomen",
         "한국 문학에 관심이 있어요.", "Ich interessiere mich für koreanische Literatur.",
         "literature", "Noun", "I am interested in Korean literature."),
        ("전통", "jeontong", "Tradition", "Nomen",
         "이 마을은 전통을 지켜요.", "Dieses Dorf bewahrt seine Tradition.",
         "tradition", "Noun", "This village keeps its tradition."),
        ("유행", "yuhaeng", "Trend", "Nomen",
         "이 노래가 요즘 유행이에요.", "Dieses Lied ist gerade im Trend.",
         "trend", "Noun", "This song is trending these days."),
        ("미술관", "misulgwan", "Kunstmuseum", "Nomen",
         "미술관이 어디에 있어요?", "Wo ist das Kunstmuseum?",
         "art museum", "Noun", "Where is the art museum?"),
        ("박물관", "bangmulgwan", "Museum", "Nomen",
         "박물관은 월요일에 쉬어요.", "Das Museum hat montags geschlossen.",
         "museum", "Noun", "The museum is closed on Mondays."),
        ("기념품", "ginyeompum", "Souvenir", "Nomen",
         "기념품은 어디에서 팔아요?", "Wo werden Souvenirs verkauft?",
         "souvenir", "Noun", "Where do they sell souvenirs?"),
    ]),
    ("b1_city_places_1", "Stadt & Orte", [
        ("광장", "gwangjang", "Platz", "Nomen",
         "광장에 사람이 많아요.", "Auf dem Platz sind viele Menschen.",
         "plaza", "Noun", "There are many people in the plaza."),
        ("시청", "sicheong", "Rathaus", "Nomen",
         "시청 앞에서 만나요.", "Treffen wir uns vor dem Rathaus.",
         "city hall", "Noun", "Let us meet in front of city hall."),
        ("시설", "siseol", "Einrichtung", "Nomen",
         "이 호텔은 시설이 좋아요.", "Dieses Hotel hat eine gute Ausstattung.",
         "facility", "Noun", "This hotel has good facilities."),
        ("상가", "sangga", "Einkaufszeile", "Nomen",
         "집 근처에 상가가 있어요.", "In der Nähe meiner Wohnung gibt es eine Einkaufszeile.",
         "shopping street", "Noun", "There is a shopping street near my home."),
        ("동물원", "dongmurwon", "Zoo", "Nomen",
         "아이들과 동물원에 갔어요.", "Ich war mit den Kindern im Zoo.",
         "zoo", "Noun", "I went to the zoo with the kids."),
        ("놀이공원", "norigongwon", "Freizeitpark", "Nomen",
         "주말에 놀이공원에 가요.", "Am Wochenende gehen wir in den Freizeitpark.",
         "amusement park", "Noun", "We go to the amusement park on weekends."),
        ("공연장", "gongyeonjang", "Konzerthalle", "Nomen",
         "공연장 입구가 복잡해요.", "Der Eingang der Konzerthalle ist voll.",
         "concert hall", "Noun", "The concert hall entrance is crowded."),
        ("하숙집", "hasukjip", "Studentenpension", "Nomen",
         "대학교 근처 하숙집에 살아요.", "Ich wohne in einer Studentenpension nahe der Uni.",
         "boarding house", "Noun", "I live in a boarding house near the university."),
        ("면세점", "myeonsejeom", "Duty-free-Laden", "Nomen",
         "공항 면세점에서 화장품을 샀어요.", "Im Duty-free-Laden am Flughafen habe ich Kosmetik gekauft.",
         "duty-free shop", "Noun", "I bought cosmetics at the airport duty-free shop."),
        ("책방", "chaekbang", "Buchladen", "Nomen",
         "동네 책방에서 책을 샀어요.", "Ich habe im Buchladen im Viertel ein Buch gekauft.",
         "bookstore", "Noun", "I bought a book at the local bookstore."),
        ("우체국", "ucheguk", "Post", "Nomen",
         "우체국에서 소포를 보냈어요.", "Ich habe bei der Post ein Paket verschickt.",
         "post office", "Noun", "I sent a package at the post office."),
        ("경찰서", "gyeongchalseo", "Polizeiwache", "Nomen",
         "지갑을 잃어버려서 경찰서에 갔어요.", "Ich habe meinen Geldbeutel verloren und bin zur Polizeiwache gegangen.",
         "police station", "Noun", "I lost my wallet and went to the police station."),
    ]),
    ("b1_money_bank_1", "Geld & Gebühren", [
        ("지폐", "jipye", "Geldschein", "Nomen",
         "지폐를 동전으로 바꿨어요.", "Ich habe den Geldschein in Münzen gewechselt.",
         "banknote", "Noun", "I changed the banknote into coins."),
        ("동전", "dongjeon", "Münze", "Nomen",
         "동전이 하나도 없어요.", "Ich habe keine einzige Münze.",
         "coin", "Noun", "I do not have a single coin."),
        ("환율", "hwanyul", "Wechselkurs", "Nomen",
         "오늘 환율이 어떻게 돼요?", "Wie steht heute der Wechselkurs?",
         "exchange rate", "Noun", "What is the exchange rate today?"),
        ("공과금", "gonggwageum", "Nebenkosten", "Nomen",
         "매달 공과금을 내요.", "Ich zahle jeden Monat die Nebenkosten.",
         "utility bill", "Noun", "I pay utility bills every month."),
        ("벌금", "beolgeum", "Bußgeld", "Nomen",
         "주차 벌금을 냈어요.", "Ich habe ein Bußgeld fürs Parken bezahlt.",
         "fine", "Noun", "I paid a parking fine."),
        ("예금", "yegeum", "Sparguthaben", "Nomen",
         "은행에 예금이 조금 있어요.", "Ich habe etwas Sparguthaben auf der Bank.",
         "deposit", "Noun", "I have some savings in the bank."),
        ("생활비", "saenghwalbi", "Lebenshaltungskosten", "Nomen",
         "서울은 생활비가 비싸요.", "In Seoul sind die Lebenshaltungskosten hoch.",
         "living expenses", "Noun", "Living expenses in Seoul are high."),
        ("식비", "sikbi", "Essenskosten", "Nomen",
         "이번 달 식비가 많이 나왔어요.", "Diesen Monat waren die Essenskosten hoch.",
         "food expenses", "Noun", "Food expenses were high this month."),
        ("입장료", "ipjangnyo", "Eintrittsgebühr", "Nomen",
         "입장료가 얼마예요?", "Wie hoch ist die Eintrittsgebühr?",
         "admission fee", "Noun", "How much is the admission fee?"),
        ("지불", "jibul", "Bezahlung", "Nomen",
         "카드로 지불이 가능해요?", "Ist Bezahlung mit Karte möglich?",
         "payment", "Noun", "Is payment by card possible?"),
        ("거스름돈", "geoseureumdon", "Wechselgeld", "Nomen",
         "거스름돈을 받았어요.", "Ich habe das Wechselgeld bekommen.",
         "change", "Noun", "I received the change."),
        ("신용카드", "sinyongkadeu", "Kreditkarte", "Nomen",
         "신용카드로 계산할게요.", "Ich zahle mit Kreditkarte.",
         "credit card", "Noun", "I will pay by credit card."),
    ]),
    ("b1_travel_transport_1", "Reise & Verkehr", [
        ("열차", "yeolcha", "Zug", "Nomen",
         "열차가 곧 출발해요.", "Der Zug fährt gleich ab.",
         "train", "Noun", "The train departs soon."),
        ("대중교통", "daejunggyotong", "öffentliche Verkehrsmittel", "Nomen",
         "저는 대중교통을 자주 이용해요.", "Ich benutze oft öffentliche Verkehrsmittel.",
         "public transportation", "Noun", "I often use public transportation."),
        ("교통카드", "gyotongkadeu", "Verkehrskarte", "Nomen",
         "교통카드 어디에서 충전해요?", "Wo kann ich die Verkehrskarte aufladen?",
         "transit card", "Noun", "Where can I top up the transit card?"),
        ("갈아타다", "garatada", "umsteigen", "Verb",
         "다음 역에서 갈아타세요.", "Steigen Sie an der nächsten Station um.",
         "to transfer", "Verb", "Transfer at the next station."),
        ("좌회전", "jwahoejeon", "Linksabbiegen", "Nomen",
         "여기에서 좌회전 해 주세요.", "Biegen Sie hier bitte links ab.",
         "left turn", "Noun", "Please turn left here."),
        ("우회전", "uhoejeon", "Rechtsabbiegen", "Nomen",
         "다음 골목에서 우회전 하세요.", "Biegen Sie an der nächsten Gasse rechts ab.",
         "right turn", "Noun", "Turn right at the next alley."),
        ("직진", "jikjin", "Geradeausfahren", "Nomen",
         "이 길로 직진 해 주세요.", "Fahren Sie auf dieser Straße bitte geradeaus.",
         "going straight", "Noun", "Please go straight on this road."),
        ("정차하다", "jeongchahada", "anhalten", "Verb",
         "버스가 정류장에 정차해요.", "Der Bus hält an der Haltestelle.",
         "to stop", "Verb", "The bus stops at the station."),
        ("관광", "gwangwang", "Tourismus", "Nomen",
         "부산은 관광으로 유명해요.", "Busan ist für Tourismus bekannt.",
         "tourism", "Noun", "Busan is famous for tourism."),
        ("비상구", "bisanggu", "Notausgang", "Nomen",
         "비상구는 어디에 있어요?", "Wo ist der Notausgang?",
         "emergency exit", "Noun", "Where is the emergency exit?"),
        ("입장권", "ipjanggwon", "Eintrittskarte", "Nomen",
         "입장권 두 장 주세요.", "Zwei Eintrittskarten bitte.",
         "admission ticket", "Noun", "Two admission tickets please."),
        ("안내문", "annaemun", "Hinweisblatt", "Nomen",
         "입구에 안내문이 붙어 있어요.", "Am Eingang hängt ein Hinweisblatt.",
         "notice", "Noun", "A notice is posted at the entrance."),
    ]),
    ("b1_health_hospital_1", "Krankenhaus & Apotheke", [
        ("환자", "hwanja", "Patient", "Nomen",
         "병원에 환자가 많아요.", "Im Krankenhaus sind viele Patienten.",
         "patient", "Noun", "There are many patients in the hospital."),
        ("주사", "jusa", "Spritze", "Nomen",
         "주사를 맞았어요.", "Ich habe eine Spritze bekommen.",
         "injection", "Noun", "I got an injection."),
        ("처방전", "cheobangjeon", "Rezept", "Nomen",
         "의사가 처방전을 써 줬어요.", "Der Arzt hat mir ein Rezept ausgestellt.",
         "prescription", "Noun", "The doctor wrote me a prescription."),
        ("치료하다", "chiryohada", "behandeln", "Verb",
         "이를 치료해야 해요.", "Der Zahn muss behandelt werden.",
         "to treat", "Verb", "The tooth needs to be treated."),
        ("입원하다", "ibwonhada", "ins Krankenhaus aufgenommen werden", "Verb",
         "할머니가 지난주에 입원하셨어요.", "Meine Großmutter kam letzte Woche ins Krankenhaus.",
         "to be hospitalized", "Verb", "My grandmother was hospitalized last week."),
        ("퇴원하다", "toewonhada", "entlassen werden", "Verb",
         "내일 퇴원할 수 있어요.", "Morgen kann ich entlassen werden.",
         "to be discharged", "Verb", "I can be discharged tomorrow."),
        ("감기약", "gamgiyak", "Erkältungsmedizin", "Nomen",
         "약국에서 감기약을 샀어요.", "Ich habe in der Apotheke Erkältungsmedizin gekauft.",
         "cold medicine", "Noun", "I bought cold medicine at the pharmacy."),
        ("두통약", "dutongyak", "Kopfschmerztablette", "Nomen",
         "두통약 있어요?", "Haben Sie Kopfschmerztabletten?",
         "headache medicine", "Noun", "Do you have headache medicine?"),
        ("진통제", "jintongje", "Schmerzmittel", "Nomen",
         "진통제를 하루에 두 번 드세요.", "Nehmen Sie das Schmerzmittel zweimal täglich.",
         "painkiller", "Noun", "Take the painkiller twice a day."),
        ("소화제", "sohwaje", "Verdauungsmittel", "Nomen",
         "속이 안 좋아서 소화제를 먹었어요.", "Mir war schlecht und ich habe ein Verdauungsmittel genommen.",
         "digestive medicine", "Noun", "I felt unwell and took digestive medicine."),
        ("안약", "anyak", "Augentropfen", "Nomen",
         "눈이 건조해서 안약을 넣어요.", "Meine Augen sind trocken und ich benutze Augentropfen.",
         "eye drops", "Noun", "My eyes are dry so I use eye drops."),
        ("다치다", "dachida", "sich verletzen", "Verb",
         "운동하다가 다리를 다쳤어요.", "Beim Sport habe ich mir das Bein verletzt.",
         "to get hurt", "Verb", "I hurt my leg while exercising."),
    ]),
    ("b1_work_career_1", "Karriere & Büro", [
        ("출장", "chuljang", "Dienstreise", "Nomen",
         "다음 주에 부산으로 출장을 가요.", "Nächste Woche mache ich eine Dienstreise nach Busan.",
         "business trip", "Noun", "I go on a business trip to Busan next week."),
        ("승진", "seungjin", "Beförderung", "Nomen",
         "승진을 축하해요!", "Herzlichen Glückwunsch zur Beförderung!",
         "promotion", "Noun", "Congratulations on your promotion!"),
        ("취직하다", "chwijikhada", "eine Stelle finden", "Verb",
         "형이 은행에 취직했어요.", "Mein Bruder hat eine Stelle bei einer Bank gefunden.",
         "to get a job", "Verb", "My brother got a job at a bank."),
        ("신입사원", "sinipsawon", "neuer Mitarbeiter", "Nomen",
         "신입사원 교육이 있어요.", "Es gibt eine Schulung für neue Mitarbeiter.",
         "new employee", "Noun", "There is training for new employees."),
        ("업무", "eommu", "Arbeitsaufgaben", "Nomen",
         "오늘 업무가 많아요.", "Heute habe ich viele Arbeitsaufgaben.",
         "duties", "Noun", "I have a lot of work today."),
        ("근무하다", "geunmuhada", "tätig sein", "Verb",
         "저는 주말에도 근무해요.", "Ich bin auch am Wochenende im Dienst.",
         "to be on duty", "Verb", "I also work on weekends."),
        ("서류", "seoryu", "Unterlagen", "Nomen",
         "서류를 준비해 주세요.", "Bereiten Sie bitte die Unterlagen vor.",
         "documents", "Noun", "Please prepare the documents."),
        ("보고서", "bogoseo", "Bericht", "Nomen",
         "내일까지 보고서를 써야 해요.", "Bis morgen muss ich den Bericht schreiben.",
         "report", "Noun", "I have to write the report by tomorrow."),
        ("서명하다", "seomyeonghada", "unterschreiben", "Verb",
         "여기에 서명해 주세요.", "Unterschreiben Sie bitte hier.",
         "to sign", "Verb", "Please sign here."),
        ("합격하다", "hapgyeokhada", "bestehen", "Verb",
         "시험에 합격했어요!", "Ich habe die Prüfung bestanden!",
         "to pass", "Verb", "I passed the exam!"),
        ("모집하다", "mojiphada", "rekrutieren", "Verb",
         "회사가 새 직원을 모집해요.", "Die Firma rekrutiert neue Mitarbeiter.",
         "to recruit", "Verb", "The company is recruiting new employees."),
        ("지각하다", "jigakhada", "zu spät kommen", "Verb",
         "오늘 회사에 지각했어요.", "Heute bin ich zu spät zur Arbeit gekommen.",
         "to be late", "Verb", "I was late for work today."),
    ]),
    ("b1_social_events_1", "Feste & Einladungen", [
        ("모임", "moim", "Treffen", "Nomen",
         "오늘 저녁에 모임이 있어요.", "Heute Abend habe ich ein Treffen.",
         "gathering", "Noun", "I have a gathering this evening."),
        ("초대하다", "chodaehada", "einladen", "Verb",
         "친구를 집에 초대했어요.", "Ich habe einen Freund nach Hause eingeladen.",
         "to invite", "Verb", "I invited a friend to my home."),
        ("집들이", "jipdeuri", "Einweihungsfeier", "Nomen",
         "토요일에 집들이를 해요.", "Am Samstag machen wir eine Einweihungsfeier.",
         "housewarming party", "Noun", "We are having a housewarming party on Saturday."),
        ("돌잔치", "doljanchi", "Fest zum ersten Geburtstag", "Nomen",
         "조카 돌잔치에 갔어요.", "Ich war auf dem ersten Geburtstagsfest meiner Nichte.",
         "first birthday party", "Noun", "I went to my niece's first birthday party."),
        ("송별회", "songbyeolhoe", "Abschiedsfeier", "Nomen",
         "부장님 송별회가 금요일이에요.", "Die Abschiedsfeier des Abteilungsleiters ist am Freitag.",
         "farewell party", "Noun", "The manager's farewell party is on Friday."),
        ("결혼식", "gyeolhonsik", "Hochzeit", "Nomen",
         "주말에 결혼식에 가요.", "Am Wochenende gehe ich zu einer Hochzeit.",
         "wedding", "Noun", "I am going to a wedding this weekend."),
        ("결혼기념일", "gyeolhonginyeomil", "Hochzeitstag", "Nomen",
         "오늘은 부모님 결혼기념일이에요.", "Heute ist der Hochzeitstag meiner Eltern.",
         "wedding anniversary", "Noun", "Today is my parents' wedding anniversary."),
        ("신혼여행", "sinhonyeohaeng", "Flitterwochen", "Nomen",
         "신혼여행은 제주도로 가요.", "Die Flitterwochen verbringen wir auf Jeju.",
         "honeymoon", "Noun", "We are going to Jeju for our honeymoon."),
        ("선물하다", "seonmulhada", "schenken", "Verb",
         "부모님께 꽃을 선물했어요.", "Ich habe meinen Eltern Blumen geschenkt.",
         "to give a present", "Verb", "I gave my parents flowers."),
        ("참석하다", "chamseokhada", "teilnehmen", "Verb",
         "회의에 꼭 참석해 주세요.", "Nehmen Sie bitte unbedingt an der Sitzung teil.",
         "to attend", "Verb", "Please be sure to attend the meeting."),
        ("회비", "hoebi", "Mitgliedsbeitrag", "Nomen",
         "모임 회비는 만 원이에요.", "Der Beitrag für das Treffen beträgt 10.000 Won.",
         "membership fee", "Noun", "The meeting fee is 10000 won."),
        ("외식", "oesik", "Essengehen", "Nomen",
         "오늘은 가족과 외식을 해요.", "Heute gehen wir mit der Familie essen.",
         "eating out", "Noun", "We are eating out with the family today."),
    ]),
    ("b1_communication_lang_1", "Sprache & Ausdruck", [
        ("표현", "pyohyeon", "Ausdruck", "Nomen",
         "이 표현은 자주 써요.", "Diesen Ausdruck benutzt man oft.",
         "expression", "Noun", "This expression is used often."),
        ("어휘", "eohwi", "Wortschatz", "Nomen",
         "어휘를 늘리고 싶어요.", "Ich möchte meinen Wortschatz erweitern.",
         "vocabulary", "Noun", "I want to expand my vocabulary."),
        ("문장", "munjang", "Satz", "Nomen",
         "이 문장은 조금 어려워요.", "Dieser Satz ist etwas schwierig.",
         "sentence", "Noun", "This sentence is a bit difficult."),
        ("뜻", "tteut", "Bedeutung", "Nomen",
         "이 단어는 뜻이 두 개예요.", "Dieses Wort hat zwei Bedeutungen.",
         "meaning", "Noun", "This word has two meanings."),
        ("대화", "daehwa", "Gespräch", "Nomen",
         "한국어로 대화를 연습해요.", "Wir üben Gespräche auf Koreanisch.",
         "conversation", "Noun", "We practice conversations in Korean."),
        ("번역하다", "beonyeokhada", "übersetzen", "Verb",
         "이 문장을 독일어로 번역해 주세요.", "Übersetzen Sie diesen Satz bitte ins Deutsche.",
         "to translate", "Verb", "Please translate this sentence into German."),
        ("통역", "tongyeok", "Dolmetschen", "Nomen",
         "친구가 통역을 해 줬어요.", "Ein Freund hat für mich gedolmetscht.",
         "interpretation", "Noun", "A friend interpreted for me."),
        ("질문", "jilmun", "Frage", "Nomen",
         "질문이 하나 있어요.", "Ich habe eine Frage.",
         "question", "Noun", "I have a question."),
        ("대답하다", "daedaphada", "antworten", "Verb",
         "질문에 대답해 주세요.", "Antworten Sie bitte auf die Frage.",
         "to answer", "Verb", "Please answer the question."),
        ("소개하다", "sogaehada", "vorstellen", "Verb",
         "친구를 소개해 줄게요.", "Ich stelle dir einen Freund vor.",
         "to introduce", "Verb", "I will introduce a friend to you."),
        ("존댓말", "jondaenmal", "Höflichkeitssprache", "Nomen",
         "어른에게는 존댓말을 써요.", "Gegenüber Älteren benutzt man die Höflichkeitssprache.",
         "honorific speech", "Noun", "You use honorific speech with elders."),
        ("반말", "banmal", "informelle Sprache", "Nomen",
         "친한 친구와는 반말을 해요.", "Mit engen Freunden spricht man informell.",
         "casual speech", "Noun", "You speak casually with close friends."),
    ]),
    ("b1_character_feelings_1", "Charakter & Gefühle", [
        ("성격", "seonggyeok", "Charakter", "Nomen",
         "제 동생은 성격이 밝아요.", "Meine kleine Schwester hat einen fröhlichen Charakter.",
         "personality", "Noun", "My younger sister has a cheerful personality."),
        ("관심", "gwansim", "Interesse", "Nomen",
         "역사에 관심이 많아요.", "Ich habe großes Interesse an Geschichte.",
         "interest", "Noun", "I am very interested in history."),
        ("기쁨", "gippeum", "Freude", "Nomen",
         "합격 소식은 큰 기쁨이었어요.", "Die Nachricht vom Bestehen war eine große Freude.",
         "joy", "Noun", "The news of passing was a great joy."),
        ("슬픔", "seulpeum", "Trauer", "Nomen",
         "슬픔은 시간이 지나면 나아져요.", "Trauer wird mit der Zeit leichter.",
         "sadness", "Noun", "Sadness gets better with time."),
        ("외로움", "oeroum", "Einsamkeit", "Nomen",
         "혼자 살면 가끔 외로움을 느껴요.", "Beim Alleinleben fühlt man manchmal Einsamkeit.",
         "loneliness", "Noun", "Living alone you sometimes feel loneliness."),
        ("고민", "gomin", "Sorge", "Nomen",
         "요즘 고민이 하나 있어요.", "Zurzeit habe ich eine Sorge.",
         "worry", "Noun", "I have one worry these days."),
        ("부럽다", "bureopda", "beneiden", "Adjektiv",
         "여행 사진을 보니까 정말 부러워요.", "Beim Anblick deiner Reisefotos beneide ich dich wirklich.",
         "to envy", "Adjective", "Seeing your travel photos I really envy you."),
        ("궁금하다", "gunggeumhada", "neugierig sein", "Adjektiv",
         "결과가 정말 궁금해요.", "Ich bin sehr gespannt auf das Ergebnis.",
         "to be curious", "Adjective", "I am very curious about the result."),
        ("섭섭하다", "seopseophada", "enttäuscht sein", "Adjektiv",
         "연락이 없어서 조금 섭섭했어요.", "Ohne deine Nachricht war ich etwas enttäuscht.",
         "to feel hurt", "Adjective", "I felt a bit hurt because you did not call."),
        ("심각하다", "simgakhada", "ernst", "Adjektiv",
         "문제가 생각보다 심각해요.", "Das Problem ist ernster als gedacht.",
         "serious", "Adjective", "The problem is more serious than expected."),
        ("이상하다", "isanghada", "seltsam", "Adjektiv",
         "이 소리 좀 이상해요.", "Dieses Geräusch ist etwas seltsam.",
         "strange", "Adjective", "This sound is a bit strange."),
        ("훌륭하다", "hullyunghada", "ausgezeichnet", "Adjektiv",
         "발표가 정말 훌륭했어요.", "Die Präsentation war wirklich ausgezeichnet.",
         "excellent", "Adjective", "The presentation was truly excellent."),
    ]),
    ("b1_verbs_daily_1", "Nützliche Verben", [
        ("맡기다", "matgida", "abgeben", "Verb",
         "가방을 호텔에 맡겼어요.", "Ich habe die Tasche im Hotel abgegeben.",
         "to entrust", "Verb", "I left my bag at the hotel."),
        ("치우다", "chiuda", "aufräumen", "Verb",
         "방을 좀 치워 주세요.", "Räum bitte das Zimmer auf.",
         "to clean up", "Verb", "Please clean up the room."),
        ("사귀다", "sagwida", "sich anfreunden", "Verb",
         "한국 친구를 많이 사귀었어요.", "Ich habe viele koreanische Freunde gefunden.",
         "to make friends", "Verb", "I made many Korean friends."),
        ("줍다", "jupda", "aufheben", "Verb",
         "길에서 지갑을 주웠어요.", "Ich habe auf der Straße einen Geldbeutel aufgehoben.",
         "to pick up", "Verb", "I picked up a wallet on the street."),
        ("키우다", "kiuda", "aufziehen", "Verb",
         "저는 고양이 한 마리를 키워요.", "Ich halte eine Katze.",
         "to raise", "Verb", "I am raising a cat."),
        ("모으다", "moeuda", "sammeln", "Verb",
         "취미로 우표를 모아요.", "Als Hobby sammle ich Briefmarken.",
         "to collect", "Verb", "I collect stamps as a hobby."),
        ("벌다", "beolda", "verdienen", "Verb",
         "아르바이트로 돈을 벌어요.", "Mit einem Nebenjob verdiene ich Geld.",
         "to earn", "Verb", "I earn money with a part-time job."),
        ("깎다", "kkakda", "schälen", "Verb",
         "사과를 깎아서 먹었어요.", "Ich habe den Apfel geschält und gegessen.",
         "to peel", "Verb", "I peeled the apple and ate it."),
        ("헤어지다", "heeojida", "sich trennen", "Verb",
         "남자친구와 헤어졌어요.", "Ich habe mich von meinem Freund getrennt.",
         "to break up", "Verb", "I broke up with my boyfriend."),
        ("잊어버리다", "ijeobeorida", "vergessen", "Verb",
         "약속을 깜빡 잊어버렸어요.", "Ich habe den Termin völlig vergessen.",
         "to forget", "Verb", "I completely forgot the appointment."),
        ("고치다", "gochida", "reparieren", "Verb",
         "컴퓨터를 고쳐야 해요.", "Der Computer muss repariert werden.",
         "to fix", "Verb", "The computer needs to be fixed."),
        ("던지다", "deonjida", "werfen", "Verb",
         "공을 던져 주세요.", "Wirf mir bitte den Ball zu.",
         "to throw", "Verb", "Please throw me the ball."),
    ]),
    ("b1_descriptions_adj_1", "Eigenschaften", [
        ("뚱뚱하다", "ttungttunghada", "dick", "Adjektiv",
         "우리 고양이는 조금 뚱뚱해요.", "Unsere Katze ist etwas dick.",
         "fat", "Adjective", "Our cat is a little fat."),
        ("날씬하다", "nalssinhada", "schlank", "Adjektiv",
         "운동해서 날씬해졌어요.", "Durch Sport bin ich schlank geworden.",
         "slim", "Adjective", "I became slim through exercise."),
        ("미끄럽다", "mikkeureopda", "rutschig", "Adjektiv",
         "겨울에는 길이 미끄러워요.", "Im Winter sind die Straßen rutschig.",
         "slippery", "Adjective", "The roads are slippery in winter."),
        ("편리하다", "pyeollihada", "praktisch", "Adjektiv",
         "지하철이 정말 편리해요.", "Die U-Bahn ist wirklich praktisch.",
         "convenient", "Adjective", "The subway is really convenient."),
        ("불편하다", "bulpyeonhada", "unbequem", "Adjektiv",
         "이 의자는 불편해요.", "Dieser Stuhl ist unbequem.",
         "uncomfortable", "Adjective", "This chair is uncomfortable."),
        ("심하다", "simhada", "schlimm", "Adjektiv",
         "감기가 심해요.", "Die Erkältung ist schlimm.",
         "severe", "Adjective", "The cold is severe."),
        ("똑같다", "ttokgatda", "genau gleich", "Adjektiv",
         "우리는 취미가 똑같아요.", "Wir haben genau das gleiche Hobby.",
         "identical", "Adjective", "We have exactly the same hobby."),
        ("비슷하다", "biseuthada", "ähnlich", "Adjektiv",
         "두 단어는 뜻이 비슷해요.", "Die beiden Wörter haben eine ähnliche Bedeutung.",
         "similar", "Adjective", "The two words have similar meanings."),
        ("세다", "seda", "stark", "Adjektiv",
         "바람이 아주 세요.", "Der Wind ist sehr stark.",
         "strong", "Adjective", "The wind is very strong."),
        ("굵다", "gukda", "dick (grob)", "Adjektiv",
         "굵은 펜으로 써 주세요.", "Schreiben Sie bitte mit einem dicken Stift.",
         "thick", "Adjective", "Please write with a thick pen."),
        ("밝다", "bakda", "hell", "Adjektiv",
         "이 방은 아주 밝아요.", "Dieses Zimmer ist sehr hell.",
         "bright", "Adjective", "This room is very bright."),
        ("어둡다", "eodupda", "dunkel", "Adjektiv",
         "밖이 벌써 어두워요.", "Draußen ist es schon dunkel.",
         "dark", "Adjective", "It is already dark outside."),
    ]),
    ("b1_time_life_1", "Zeit & Lebenslauf", [
        ("기간", "gigan", "Zeitraum", "Nomen",
         "시험 기간에는 바빠요.", "In der Prüfungszeit bin ich beschäftigt.",
         "period", "Noun", "I am busy during exam period."),
        ("순간", "sungan", "Moment", "Nomen",
         "그 순간을 잊을 수 없어요.", "Diesen Moment kann ich nicht vergessen.",
         "moment", "Noun", "I cannot forget that moment."),
        ("평일", "pyeongil", "Wochentag", "Nomen",
         "평일에는 회사에 가요.", "An Wochentagen gehe ich zur Arbeit.",
         "weekday", "Noun", "I go to work on weekdays."),
        ("연휴", "yeonhyu", "lange Feiertage", "Nomen",
         "이번 연휴에 뭐 해요?", "Was machst du an den langen Feiertagen?",
         "long holiday", "Noun", "What are you doing over the long holiday?"),
        ("세월", "sewol", "die Jahre", "Nomen",
         "세월이 참 빨라요.", "Die Zeit vergeht wirklich schnell.",
         "passing years", "Noun", "Time really flies."),
        ("태어나다", "taeeonada", "geboren werden", "Verb",
         "저는 서울에서 태어났어요.", "Ich bin in Seoul geboren.",
         "to be born", "Verb", "I was born in Seoul."),
        ("졸업하다", "joreophada", "den Abschluss machen", "Verb",
         "내년에 대학교를 졸업해요.", "Nächstes Jahr mache ich meinen Uni-Abschluss.",
         "to graduate", "Verb", "I graduate from university next year."),
        ("입학하다", "iphakhada", "eingeschult werden", "Verb",
         "조카가 올해 초등학교에 입학했어요.", "Meine Nichte wurde dieses Jahr eingeschult.",
         "to enter a school", "Verb", "My niece started elementary school this year."),
        ("어른", "eoreun", "Erwachsener", "Nomen",
         "어른에게 존댓말을 써야 해요.", "Gegenüber Erwachsenen muss man höflich sprechen.",
         "adult", "Noun", "You must speak politely to adults."),
        ("노인", "noin", "älterer Mensch", "Nomen",
         "지하철에서 노인에게 자리를 양보했어요.", "In der U-Bahn habe ich einem älteren Menschen den Platz überlassen.",
         "elderly person", "Noun", "I gave my seat to an elderly person on the subway."),
        ("미래", "mirae", "Zukunft", "Nomen",
         "미래를 위해 저축해요.", "Für die Zukunft spare ich.",
         "future", "Noun", "I save for the future."),
        ("옛날", "yennal", "früher", "Nomen",
         "옛날에는 여기가 시장이었어요.", "Früher war hier ein Markt.",
         "old days", "Noun", "This used to be a market in the old days."),
    ]),
]


def next_id_start(rows):
    mx = 0
    for r in rows:
        m = re.fullmatch(re.escape(ID_PREFIX) + r"(\d+)", r["id"].strip())
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1


def main():
    rows = list(csv.DictReader(open(VOCAB, encoding="utf-8")))
    existing = {r["korean"].strip() for r in rows}
    seq = next_id_start(rows)

    to_add = []
    for pack_id, topic, words in PACKS:
        n = len(words)
        for i, (ko, rom, de, posde, exko, exde, en, posen, exen) in enumerate(words):
            if ko in existing:
                print(f"skip (exists): {ko}")
                continue
            assert not any("," in f for f in (ko, de, exko, exde, en, exen)), f"comma in {ko}"
            boss = "true" if i >= n - 3 else "false"
            to_add.append([
                ko, rom, de, LEVEL, posde, exko, exde, topic, pack_id,
                i + 1, boss, en, posen, exen, f"{ID_PREFIX}{seq:04d}",
            ])
            existing.add(ko)
            seq += 1

    print(f"neu: {len(to_add)} Wörter in {len(PACKS)} Paketen")
    for r in to_add:
        print(f"  {r[8]} #{r[9]:>2}{'★' if r[10] == 'true' else ' '} {r[0]} — {r[2]}")

    if "--write" in sys.argv and to_add:
        with open(VOCAB, "a", encoding="utf-8", newline="") as f:
            w = csv.writer(f)
            for r in to_add:
                w.writerow(r)
        print(f"\n✅ {len(to_add)} Zeilen an {VOCAB} angehängt")
    else:
        print("\n(Dry-Run — mit --write anhängen)")


if __name__ == "__main__":
    main()
