#!/usr/bin/env python3
"""add_a2_expansion_packs.py — A2-Erweiterung: 9 neue Vokabelpakete (108 Wörter).

Quelle: Jins TOPIK-Liste + 국립국어원-Phrasebook-Boxvokabeln — kuratiert;
DE-Glossen und Beispielsätze neu verfasst. A1 wurde bewusst ausgelassen
(bereits 211 Wörter / 24 Pakete; Rest der Quelle wäre größtenteils Duplikat
und A1-Pakete brechen die Golden-Tests der Paketliste).

⚠️ Von Claude verfasst — Jin (Muttersprachler) sollte KO/DE stichprobenartig prüfen.

Idempotent. Nutzung: python tools/content_factory/add_a2_expansion_packs.py --write
"""
import csv
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
VOCAB = os.path.join(ROOT, "assets", "data", "korean_vocab.csv")

LEVEL = "A2"
ID_PREFIX = "vocab_a2_"

PACKS = [
    ("a2_clothing_1", "Kleidung", [
        ("코트", "koteu", "Mantel", "Nomen",
         "겨울에는 코트를 입어요.", "Im Winter trage ich einen Mantel.",
         "coat", "Noun", "I wear a coat in winter."),
        ("치마", "chima", "Rock", "Nomen",
         "오늘은 치마를 입었어요.", "Heute trage ich einen Rock.",
         "skirt", "Noun", "I am wearing a skirt today."),
        ("원피스", "wonpiseu", "Kleid", "Nomen",
         "파티에 원피스를 입고 갔어요.", "Ich bin im Kleid zur Party gegangen.",
         "dress", "Noun", "I went to the party in a dress."),
        ("양복", "yangbok", "Anzug", "Nomen",
         "아버지는 양복을 입고 출근해요.", "Mein Vater geht im Anzug zur Arbeit.",
         "suit", "Noun", "My father goes to work in a suit."),
        ("구두", "gudu", "Lederschuhe", "Nomen",
         "새 구두가 조금 작아요.", "Die neuen Schuhe sind etwas klein.",
         "dress shoes", "Noun", "The new shoes are a bit small."),
        ("양말", "yangmal", "Socken", "Nomen",
         "따뜻한 양말을 신었어요.", "Ich habe warme Socken angezogen.",
         "socks", "Noun", "I put on warm socks."),
        ("장갑", "janggap", "Handschuhe", "Nomen",
         "장갑을 어디에 뒀지요?", "Wo habe ich meine Handschuhe hingelegt?",
         "gloves", "Noun", "Where did I put my gloves?"),
        ("목도리", "mokdori", "Schal", "Nomen",
         "할머니가 목도리를 떠 주셨어요.", "Meine Oma hat mir einen Schal gestrickt.",
         "scarf", "Noun", "My grandma knitted me a scarf."),
        ("반지", "banji", "Ring", "Nomen",
         "예쁜 반지를 선물 받았어요.", "Ich habe einen schönen Ring geschenkt bekommen.",
         "ring", "Noun", "I received a pretty ring as a gift."),
        ("귀걸이", "gwigeori", "Ohrringe", "Nomen",
         "새 귀걸이를 하고 나갔어요.", "Ich bin mit neuen Ohrringen ausgegangen.",
         "earrings", "Noun", "I went out wearing new earrings."),
        ("넥타이", "nektai", "Krawatte", "Nomen",
         "파란 넥타이가 잘 어울려요.", "Die blaue Krawatte steht dir gut.",
         "necktie", "Noun", "The blue tie suits you well."),
        ("배낭", "baenang", "Rucksack", "Nomen",
         "배낭을 메고 여행을 떠났어요.", "Mit dem Rucksack bin ich auf Reisen gegangen.",
         "backpack", "Noun", "I went traveling with a backpack."),
    ]),
    ("a2_wearing_verbs_1", "Anziehen & Accessoires", [
        ("신다", "sinda", "anziehen (Schuhe)", "Verb",
         "운동화를 신고 뛰어요.", "Ich laufe in Turnschuhen.",
         "to wear (feet)", "Verb", "I run wearing sneakers."),
        ("벗다", "beotda", "ausziehen", "Verb",
         "집에서는 신발을 벗어요.", "Zu Hause zieht man die Schuhe aus.",
         "to take off", "Verb", "You take off your shoes at home."),
        ("매다", "maeda", "binden", "Verb",
         "넥타이를 매는 법을 배웠어요.", "Ich habe gelernt eine Krawatte zu binden.",
         "to tie", "Verb", "I learned how to tie a tie."),
        ("끼다", "kkida", "anziehen (Hände)", "Verb",
         "추워서 장갑을 꼈어요.", "Wegen der Kälte habe ich Handschuhe angezogen.",
         "to wear (hands)", "Verb", "I put on gloves because it was cold."),
        ("차다", "chada", "umlegen (Uhr)", "Verb",
         "새 시계를 차고 있어요.", "Ich trage eine neue Uhr.",
         "to wear (watch)", "Verb", "I am wearing a new watch."),
        ("메다", "meda", "schultern", "Verb",
         "가방을 메고 학교에 가요.", "Ich gehe mit der Tasche über der Schulter zur Schule.",
         "to carry (shoulder)", "Verb", "I go to school with a bag on my shoulder."),
        ("벨트", "belteu", "Gürtel", "Nomen",
         "바지가 커서 벨트를 했어요.", "Die Hose war groß und ich habe einen Gürtel angelegt.",
         "belt", "Noun", "The pants were big so I wore a belt."),
        ("팔찌", "paljji", "Armband", "Nomen",
         "은 팔찌를 자주 해요.", "Ich trage oft ein silbernes Armband.",
         "bracelet", "Noun", "I often wear a silver bracelet."),
        ("부츠", "bucheu", "Stiefel", "Nomen",
         "눈이 와서 부츠를 신었어요.", "Es hat geschneit und ich habe Stiefel angezogen.",
         "boots", "Noun", "It snowed so I wore boots."),
        ("샌들", "saendeul", "Sandalen", "Nomen",
         "여름에는 샌들이 편해요.", "Im Sommer sind Sandalen bequem.",
         "sandals", "Noun", "Sandals are comfortable in summer."),
        ("슬리퍼", "seullipeo", "Hausschuhe", "Nomen",
         "집에서 슬리퍼를 신어요.", "Zu Hause trage ich Hausschuhe.",
         "slippers", "Noun", "I wear slippers at home."),
        ("스타킹", "seutaking", "Strumpfhose", "Nomen",
         "스타킹에 구멍이 났어요.", "Meine Strumpfhose hat ein Loch.",
         "stockings", "Noun", "My stockings have a hole."),
    ]),
    ("a2_restaurant_1", "Im Restaurant", [
        ("반찬", "banchan", "Beilage", "Nomen",
         "한국 식당은 반찬이 많아요.", "Koreanische Restaurants haben viele Beilagen.",
         "side dish", "Noun", "Korean restaurants have many side dishes."),
        ("소금", "sogeum", "Salz", "Nomen",
         "소금 좀 건네주세요.", "Reich mir bitte das Salz.",
         "salt", "Noun", "Please pass the salt."),
        ("후추", "huchu", "Pfeffer", "Nomen",
         "수프에 후추를 넣었어요.", "Ich habe Pfeffer in die Suppe getan.",
         "pepper", "Noun", "I put pepper in the soup."),
        ("젓가락", "jeotgarak", "Stäbchen", "Nomen",
         "젓가락 사용이 어려워요.", "Stäbchen zu benutzen ist schwierig.",
         "chopsticks", "Noun", "Using chopsticks is difficult."),
        ("숟가락", "sutgarak", "Löffel", "Nomen",
         "숟가락으로 국을 먹어요.", "Suppe isst man mit dem Löffel.",
         "spoon", "Noun", "You eat soup with a spoon."),
        ("계산서", "gyesanseo", "Rechnung", "Nomen",
         "계산서 좀 주세요.", "Die Rechnung bitte.",
         "check", "Noun", "The check please."),
        ("차림표", "charimpyo", "Speisekarte", "Nomen",
         "차림표 좀 볼 수 있을까요?", "Könnte ich die Speisekarte sehen?",
         "menu", "Noun", "Could I see the menu?"),
        ("인분", "inbun", "Portion", "Nomen",
         "불고기 2인분 주세요.", "Zwei Portionen Bulgogi bitte.",
         "serving", "Noun", "Two servings of bulgogi please."),
        ("배부르다", "baebureuda", "satt sein", "Adjektiv",
         "너무 많이 먹어서 배불러요.", "Ich habe zu viel gegessen und bin satt.",
         "to be full", "Adjective", "I ate too much and I am full."),
        ("씹다", "ssipda", "kauen", "Verb",
         "음식을 천천히 씹으세요.", "Kauen Sie das Essen langsam.",
         "to chew", "Verb", "Chew your food slowly."),
        ("맛보다", "matboda", "probieren", "Verb",
         "이 김치 좀 맛보세요.", "Probieren Sie mal dieses Kimchi.",
         "to taste", "Verb", "Try this kimchi."),
        ("후식", "husik", "Nachtisch", "Nomen",
         "후식으로 아이스크림을 먹었어요.", "Als Nachtisch habe ich Eis gegessen.",
         "dessert", "Noun", "I had ice cream for dessert."),
    ]),
    ("a2_household_1", "Haushalt & Zimmer", [
        ("거울", "geoul", "Spiegel", "Nomen",
         "거울을 보면서 머리를 빗어요.", "Ich kämme mich vor dem Spiegel.",
         "mirror", "Noun", "I comb my hair in front of the mirror."),
        ("달력", "dallyeok", "Kalender", "Nomen",
         "달력에 약속을 표시했어요.", "Ich habe den Termin im Kalender markiert.",
         "calendar", "Noun", "I marked the appointment on the calendar."),
        ("비누", "binu", "Seife", "Nomen",
         "비누로 손을 씻으세요.", "Waschen Sie die Hände mit Seife.",
         "soap", "Noun", "Wash your hands with soap."),
        ("칫솔", "chitsol", "Zahnbürste", "Nomen",
         "새 칫솔로 바꿨어요.", "Ich habe eine neue Zahnbürste genommen.",
         "toothbrush", "Noun", "I switched to a new toothbrush."),
        ("수건", "sugeon", "Handtuch", "Nomen",
         "깨끗한 수건 있어요?", "Gibt es ein sauberes Handtuch?",
         "towel", "Noun", "Is there a clean towel?"),
        ("그릇", "geureut", "Schüssel", "Nomen",
         "그릇을 씻어서 정리했어요.", "Ich habe die Schüsseln gespült und weggeräumt.",
         "bowl", "Noun", "I washed and put away the bowls."),
        ("컵", "keop", "Tasse", "Nomen",
         "컵에 물을 따랐어요.", "Ich habe Wasser in die Tasse gegossen.",
         "cup", "Noun", "I poured water into the cup."),
        ("냄새", "naemsae", "Geruch", "Nomen",
         "부엌에서 좋은 냄새가 나요.", "Aus der Küche kommt ein guter Geruch.",
         "smell", "Noun", "A good smell comes from the kitchen."),
        ("창문", "changmun", "Fenster", "Nomen",
         "더워서 창문을 열었어요.", "Mir war warm und ich habe das Fenster geöffnet.",
         "window", "Noun", "I was hot so I opened the window."),
        ("꽃병", "kkotbyeong", "Blumenvase", "Nomen",
         "꽃병에 장미를 꽂았어요.", "Ich habe Rosen in die Vase gestellt.",
         "flower vase", "Noun", "I put roses in the vase."),
        ("화분", "hwabun", "Blumentopf", "Nomen",
         "창가에 화분이 세 개 있어요.", "Am Fenster stehen drei Blumentöpfe.",
         "flower pot", "Noun", "There are three flower pots by the window."),
        ("옷걸이", "otgeori", "Kleiderbügel", "Nomen",
         "코트를 옷걸이에 걸었어요.", "Ich habe den Mantel auf den Bügel gehängt.",
         "coat hanger", "Noun", "I hung the coat on the hanger."),
    ]),
    ("a2_food_more_1", "Essen & Zutaten", [
        ("야채", "yachae", "Gemüse", "Nomen",
         "야채를 많이 드세요.", "Essen Sie viel Gemüse.",
         "vegetables", "Noun", "Eat lots of vegetables."),
        ("수박", "subak", "Wassermelone", "Nomen",
         "여름에는 수박이 최고예요.", "Im Sommer ist Wassermelone das Beste.",
         "watermelon", "Noun", "Watermelon is the best in summer."),
        ("배", "bae", "Birne", "Nomen",
         "한국 배는 크고 달아요.", "Koreanische Birnen sind groß und süß.",
         "pear", "Noun", "Korean pears are big and sweet."),
        ("딸기", "ttalgi", "Erdbeere", "Nomen",
         "딸기 케이크를 좋아해요.", "Ich mag Erdbeerkuchen.",
         "strawberry", "Noun", "I like strawberry cake."),
        ("쇠고기", "soegogi", "Rindfleisch", "Nomen",
         "쇠고기로 국을 끓였어요.", "Ich habe Suppe mit Rindfleisch gekocht.",
         "beef", "Noun", "I made soup with beef."),
        ("돼지고기", "dwaejigogi", "Schweinefleisch", "Nomen",
         "돼지고기는 잘 익혀야 해요.", "Schweinefleisch muss gut durchgegart werden.",
         "pork", "Noun", "Pork must be cooked well."),
        ("불고기", "bulgogi", "Bulgogi", "Nomen",
         "저녁에 불고기를 만들어요.", "Zum Abendessen mache ich Bulgogi.",
         "bulgogi", "Noun", "I am making bulgogi for dinner."),
        ("비빔밥", "bibimbap", "Bibimbap", "Nomen",
         "비빔밥에는 나물이 들어가요.", "In Bibimbap kommen Gemüsebeilagen.",
         "bibimbap", "Noun", "Bibimbap contains seasoned vegetables."),
        ("냉면", "naengmyeon", "kalte Nudeln", "Nomen",
         "여름에 냉면을 자주 먹어요.", "Im Sommer esse ich oft kalte Nudeln.",
         "cold noodles", "Noun", "I often eat cold noodles in summer."),
        ("땅콩", "ttangkong", "Erdnuss", "Nomen",
         "땅콩 알레르기가 있어요?", "Haben Sie eine Erdnussallergie?",
         "peanut", "Noun", "Do you have a peanut allergy?"),
        ("잼", "jaem", "Marmelade", "Nomen",
         "빵에 딸기 잼을 발랐어요.", "Ich habe Erdbeermarmelade aufs Brot gestrichen.",
         "jam", "Noun", "I spread strawberry jam on the bread."),
        ("밀가루", "milgaru", "Mehl", "Nomen",
         "밀가루로 빵을 만들어요.", "Aus Mehl macht man Brot.",
         "flour", "Noun", "Bread is made from flour."),
    ]),
    ("a2_nature_1", "Natur & Draußen", [
        ("지구", "jigu", "Erde", "Nomen",
         "지구는 둥글어요.", "Die Erde ist rund.",
         "Earth", "Noun", "The Earth is round."),
        ("태양", "taeyang", "Sonne", "Nomen",
         "태양이 밝게 빛나요.", "Die Sonne scheint hell.",
         "sun", "Noun", "The sun shines brightly."),
        ("숲", "sup", "Wald", "Nomen",
         "숲에서 산책했어요.", "Ich bin im Wald spazieren gegangen.",
         "forest", "Noun", "I took a walk in the forest."),
        ("물고기", "mulgogi", "Fisch", "Nomen",
         "강에 물고기가 많아요.", "Im Fluss gibt es viele Fische.",
         "fish", "Noun", "There are many fish in the river."),
        ("모기", "mogi", "Mücke", "Nomen",
         "여름 밤에는 모기가 많아요.", "In Sommernächten gibt es viele Mücken.",
         "mosquito", "Noun", "There are many mosquitoes on summer nights."),
        ("풀", "pul", "Gras", "Nomen",
         "풀 위에 앉아서 쉬었어요.", "Ich habe mich ins Gras gesetzt und ausgeruht.",
         "grass", "Noun", "I sat on the grass and rested."),
        ("잎", "ip", "Blatt", "Nomen",
         "가을에는 잎이 빨개져요.", "Im Herbst werden die Blätter rot.",
         "leaf", "Noun", "Leaves turn red in autumn."),
        ("용", "yong", "Drache", "Nomen",
         "옛날이야기에 용이 나와요.", "In alten Geschichten kommen Drachen vor.",
         "dragon", "Noun", "Dragons appear in old tales."),
        ("바람", "baram", "Wind", "Nomen",
         "오늘은 바람이 시원해요.", "Heute ist der Wind angenehm kühl.",
         "wind", "Noun", "The wind is cool today."),
        ("눈사람", "nunsaram", "Schneemann", "Nomen",
         "아이들이 눈사람을 만들어요.", "Die Kinder bauen einen Schneemann.",
         "snowman", "Noun", "The children are building a snowman."),
        ("눈싸움", "nunssaum", "Schneeballschlacht", "Nomen",
         "친구들과 눈싸움을 했어요.", "Ich habe mit Freunden eine Schneeballschlacht gemacht.",
         "snowball fight", "Noun", "I had a snowball fight with friends."),
        ("동네", "dongne", "Viertel", "Nomen",
         "우리 동네는 조용해요.", "Unser Viertel ist ruhig.",
         "neighborhood", "Noun", "Our neighborhood is quiet."),
    ]),
    ("a2_people_jobs_1", "Menschen & Berufe", [
        ("가수", "gasu", "Sänger", "Nomen",
         "저 가수는 노래를 정말 잘해요.", "Dieser Sänger singt wirklich gut.",
         "singer", "Noun", "That singer sings really well."),
        ("변호사", "byeonhosa", "Anwalt", "Nomen",
         "언니는 변호사예요.", "Meine große Schwester ist Anwältin.",
         "lawyer", "Noun", "My older sister is a lawyer."),
        ("경찰", "gyeongchal", "Polizist", "Nomen",
         "경찰이 길을 안내해 줬어요.", "Ein Polizist hat mir den Weg gezeigt.",
         "police officer", "Noun", "A police officer showed me the way."),
        ("군인", "gunin", "Soldat", "Nomen",
         "형은 지금 군인이에요.", "Mein Bruder ist gerade Soldat.",
         "soldier", "Noun", "My brother is a soldier now."),
        ("사원", "sawon", "Angestellter", "Nomen",
         "저는 회사 사원이에요.", "Ich bin Angestellter in einer Firma.",
         "employee", "Noun", "I am a company employee."),
        ("주인", "juin", "Besitzer", "Nomen",
         "가게 주인이 친절해요.", "Der Ladenbesitzer ist freundlich.",
         "owner", "Noun", "The shop owner is friendly."),
        ("아저씨", "ajeossi", "Onkel (Anrede)", "Nomen",
         "택시 아저씨가 길을 잘 알아요.", "Der Taxifahrer kennt den Weg gut.",
         "middle-aged man", "Noun", "The taxi driver knows the way well."),
        ("아주머니", "ajumeoni", "Tante (Anrede)", "Nomen",
         "식당 아주머니가 반찬을 더 주셨어요.", "Die Wirtin hat uns mehr Beilagen gegeben.",
         "middle-aged woman", "Noun", "The restaurant lady gave us more side dishes."),
        ("왕", "wang", "König", "Nomen",
         "세종대왕은 유명한 왕이에요.", "König Sejong ist ein berühmter König.",
         "king", "Noun", "King Sejong is a famous king."),
        ("왕비", "wangbi", "Königin", "Nomen",
         "왕비가 궁에 살았어요.", "Die Königin lebte im Palast.",
         "queen", "Noun", "The queen lived in the palace."),
        ("왕자", "wangja", "Prinz", "Nomen",
         "동화에 왕자가 나와요.", "Im Märchen kommt ein Prinz vor.",
         "prince", "Noun", "A prince appears in the fairy tale."),
        ("공주", "gongju", "Prinzessin", "Nomen",
         "아이가 공주 그림을 그렸어요.", "Das Kind hat eine Prinzessin gemalt.",
         "princess", "Noun", "The child drew a princess."),
    ]),
    ("a2_school_uni_1", "Schule & Uni", [
        ("교실", "gyosil", "Klassenzimmer", "Nomen",
         "교실이 아주 조용해요.", "Das Klassenzimmer ist sehr ruhig.",
         "classroom", "Noun", "The classroom is very quiet."),
        ("교과서", "gyogwaseo", "Lehrbuch", "Nomen",
         "교과서 20쪽을 펴세요.", "Öffnet das Lehrbuch auf Seite zwanzig.",
         "textbook", "Noun", "Open the textbook to page twenty."),
        ("공책", "gongchaek", "Heft", "Nomen",
         "공책에 단어를 썼어요.", "Ich habe die Wörter ins Heft geschrieben.",
         "notebook", "Noun", "I wrote the words in my notebook."),
        ("칠판", "chilpan", "Tafel", "Nomen",
         "선생님이 칠판에 써요.", "Der Lehrer schreibt an die Tafel.",
         "blackboard", "Noun", "The teacher writes on the blackboard."),
        ("대학교", "daehakgyo", "Universität", "Nomen",
         "누나는 대학교에 다녀요.", "Meine Schwester geht zur Universität.",
         "university", "Noun", "My sister attends university."),
        ("대학생", "daehaksaeng", "Student", "Nomen",
         "저는 대학생이에요.", "Ich bin Student.",
         "university student", "Noun", "I am a university student."),
        ("고등학생", "godeunghaksaeng", "Oberschüler", "Nomen",
         "동생은 고등학생이에요.", "Mein Bruder ist Oberschüler.",
         "high school student", "Noun", "My younger brother is a high school student."),
        ("중학생", "junghaksaeng", "Mittelschüler", "Nomen",
         "중학생 때 한국어를 시작했어요.", "Als Mittelschüler habe ich mit Koreanisch angefangen.",
         "middle school student", "Noun", "I started Korean in middle school."),
        ("반", "ban", "Klasse (Gruppe)", "Nomen",
         "우리 반은 학생이 스무 명이에요.", "Unsere Klasse hat zwanzig Schüler.",
         "class", "Noun", "Our class has twenty students."),
        ("교수", "gyosu", "Professor", "Nomen",
         "교수님 수업이 재미있어요.", "Die Vorlesung des Professors ist interessant.",
         "professor", "Noun", "The professor's lecture is interesting."),
        ("유학", "yuhak", "Auslandsstudium", "Nomen",
         "내년에 한국으로 유학을 가요.", "Nächstes Jahr gehe ich zum Studium nach Korea.",
         "studying abroad", "Noun", "I am going to study in Korea next year."),
        ("유학생", "yuhaksaeng", "Auslandsstudent", "Nomen",
         "우리 학교에 유학생이 많아요.", "An unserer Schule gibt es viele Auslandsstudenten.",
         "international student", "Noun", "There are many international students at our school."),
    ]),
    ("a2_change_verbs_1", "Zustandsverben", [
        ("열리다", "yeollida", "sich öffnen", "Verb",
         "문이 저절로 열렸어요.", "Die Tür öffnete sich von selbst.",
         "to be opened", "Verb", "The door opened by itself."),
        ("닫히다", "dachida", "sich schließen", "Verb",
         "바람에 창문이 닫혔어요.", "Das Fenster schloss sich durch den Wind.",
         "to be closed", "Verb", "The window closed from the wind."),
        ("켜지다", "kyeojida", "angehen (Licht)", "Verb",
         "불이 자동으로 켜져요.", "Das Licht geht automatisch an.",
         "to be turned on", "Verb", "The light turns on automatically."),
        ("꺼지다", "kkeojida", "ausgehen (Licht)", "Verb",
         "갑자기 불이 꺼졌어요.", "Plötzlich ging das Licht aus.",
         "to be turned off", "Verb", "The light suddenly went out."),
        ("떨어지다", "tteoreojida", "herunterfallen", "Verb",
         "책이 책상에서 떨어졌어요.", "Das Buch fiel vom Tisch.",
         "to fall", "Verb", "The book fell off the desk."),
        ("남다", "namda", "übrig bleiben", "Verb",
         "음식이 많이 남았어요.", "Es ist viel Essen übrig geblieben.",
         "to remain", "Verb", "A lot of food was left over."),
        ("붙다", "butda", "kleben (haften)", "Verb",
         "벽에 포스터가 붙어 있어요.", "An der Wand klebt ein Poster.",
         "to stick", "Verb", "A poster is stuck on the wall."),
        ("걸리다", "geollida", "hängen (dauern)", "Verb",
         "벽에 그림이 걸려 있어요.", "An der Wand hängt ein Bild.",
         "to hang", "Verb", "A picture hangs on the wall."),
        ("빼다", "ppaeda", "herausziehen", "Verb",
         "가방에서 책을 뺐어요.", "Ich habe das Buch aus der Tasche genommen.",
         "to take out", "Verb", "I took the book out of the bag."),
        ("세우다", "seuda", "aufstellen (parken)", "Verb",
         "차를 여기에 세워 주세요.", "Stellen Sie das Auto bitte hier ab.",
         "to park", "Verb", "Please park the car here."),
        ("나가다", "nagada", "hinausgehen", "Verb",
         "잠깐 밖에 나갔다 올게요.", "Ich gehe kurz raus und komme wieder.",
         "to go out", "Verb", "I will step out for a moment."),
        ("나오다", "naoda", "herauskommen", "Verb",
         "회의가 끝나고 방에서 나왔어요.", "Nach der Sitzung kam ich aus dem Raum.",
         "to come out", "Verb", "I came out of the room after the meeting."),
    ]),
]


def next_id_start(rows):
    mx = 0
    for r in rows:
        m = re.fullmatch(re.escape(ID_PREFIX) + r"(\d+)", r["id"].strip())
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1


def main():
    rows = list(csv.DictReader(open(VOCAB, encoding="utf-8")))
    existing = {r["korean"].strip() for r in rows}
    seq = next_id_start(rows)

    to_add = []
    for pack_id, topic, words in PACKS:
        n = len(words)
        for i, (ko, rom, de, posde, exko, exde, en, posen, exen) in enumerate(words):
            if ko in existing:
                print(f"skip (exists): {ko}")
                continue
            assert not any("," in f for f in (ko, de, exko, exde, en, exen)), f"comma in {ko}"
            boss = "true" if i >= n - 3 else "false"
            to_add.append([
                ko, rom, de, LEVEL, posde, exko, exde, topic, pack_id,
                i + 1, boss, en, posen, exen, f"{ID_PREFIX}{seq:04d}",
            ])
            existing.add(ko)
            seq += 1

    print(f"neu: {len(to_add)} Wörter in {len(PACKS)} Paketen")
    for r in to_add:
        print(f"  {r[8]} #{r[9]:>2}{'★' if r[10] == 'true' else ' '} {r[0]} — {r[2]}")

    if "--write" in sys.argv and to_add:
        with open(VOCAB, "a", encoding="utf-8", newline="") as f:
            w = csv.writer(f)
            for r in to_add:
                w.writerow(r)
        print(f"\n✅ {len(to_add)} Zeilen an {VOCAB} angehängt")
    else:
        print("\n(Dry-Run — mit --write anhängen)")


if __name__ == "__main__":
    main()
