#!/usr/bin/env python3
"""add_b2_expansion_packs.py — B2-Erweiterung: 10 neue Vokabelpakete (120 Wörter).

Quelle: Jins TOPIK-Vokabelliste (KO/EN) — kuratiert wie add_b1_expansion_packs.py;
DE-Glossen und alle Beispielsätze neu verfasst. Enthält u. a. ein dediziertes
Ehrensprache-Paket (높임말) — Kernthema der Mittelstufe.

⚠️ Von Claude verfasst — Jin (Muttersprachler) sollte KO/DE stichprobenartig prüfen.

Idempotent: bereits vorhandene koreanische Wörter werden übersprungen.
Nutzung: python tools/content_factory/add_b2_expansion_packs.py --write
"""
import csv
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
VOCAB = os.path.join(ROOT, "assets", "data", "korean_vocab.csv")

LEVEL = "B2"
ID_PREFIX = "vocab_b2_"

PACKS = [
    ("b2_modern_life_1", "Modernes Leben", [
        ("현대", "hyeondae", "Gegenwart", "Nomen",
         "현대 사회는 변화가 빨라요.", "Die moderne Gesellschaft verändert sich schnell.",
         "modern times", "Noun", "Modern society changes fast."),
        ("현대인", "hyeondaein", "moderner Mensch", "Nomen",
         "현대인은 스트레스가 많아요.", "Moderne Menschen haben viel Stress.",
         "modern person", "Noun", "Modern people have a lot of stress."),
        ("최신식", "choesinsik", "hochmodern", "Nomen",
         "이 건물은 최신식 시설을 갖췄어요.", "Dieses Gebäude hat eine hochmoderne Ausstattung.",
         "state-of-the-art", "Noun", "This building has state-of-the-art facilities."),
        ("기계", "gigye", "Maschine", "Nomen",
         "이 기계는 사용법이 간단해요.", "Diese Maschine ist einfach zu bedienen.",
         "machine", "Noun", "This machine is easy to use."),
        ("스스로", "seuseuro", "selbst", "Adverb",
         "문제를 스스로 해결했어요.", "Ich habe das Problem selbst gelöst.",
         "by oneself", "Adverb", "I solved the problem by myself."),
        ("독립하다", "dongniphada", "unabhängig werden", "Verb",
         "서른 살에 부모님에게서 독립했어요.", "Mit dreißig bin ich von zu Hause ausgezogen.",
         "to become independent", "Verb", "I became independent from my parents at thirty."),
        ("공간", "gonggan", "Raum", "Nomen",
         "이 방은 공간이 넓어요.", "Dieses Zimmer bietet viel Raum.",
         "space", "Noun", "This room has a lot of space."),
        ("활동", "hwaldong", "Aktivität", "Nomen",
         "동아리 활동을 해요.", "Ich mache bei Klubaktivitäten mit.",
         "activity", "Noun", "I take part in club activities."),
        ("외출하다", "oechulhada", "ausgehen", "Verb",
         "잠깐 외출했어요.", "Ich war kurz außer Haus.",
         "to go out", "Verb", "I went out for a while."),
        ("평소", "pyeongso", "gewöhnliche Zeit", "Nomen",
         "평소에 일찍 일어나요.", "Normalerweise stehe ich früh auf.",
         "usual times", "Noun", "I usually get up early."),
        ("인기", "ingi", "Beliebtheit", "Nomen",
         "이 가수는 인기가 많아요.", "Dieser Sänger ist sehr beliebt.",
         "popularity", "Noun", "This singer is very popular."),
        ("달라지다", "dallajida", "sich verändern", "Verb",
         "동네가 많이 달라졌어요.", "Das Viertel hat sich stark verändert.",
         "to change", "Verb", "The neighborhood has changed a lot."),
    ]),
    ("b2_manners_society_1", "Umgangsformen", [
        ("예절", "yejeol", "Etikette", "Nomen",
         "식사 예절을 배웠어요.", "Ich habe Tischmanieren gelernt.",
         "etiquette", "Noun", "I learned table manners."),
        ("예의", "yeui", "Höflichkeit", "Nomen",
         "예의를 지키는 게 중요해요.", "Höflichkeit zu wahren ist wichtig.",
         "manners", "Noun", "Keeping good manners is important."),
        ("양보하다", "yangbohada", "überlassen", "Verb",
         "버스에서 자리를 양보했어요.", "Im Bus habe ich meinen Platz überlassen.",
         "to yield", "Verb", "I gave up my seat on the bus."),
        ("방해하다", "banghaehada", "stören", "Verb",
         "공부를 방해하지 마세요.", "Stör mich bitte nicht beim Lernen.",
         "to disturb", "Verb", "Please do not disturb my studying."),
        ("주의", "juui", "Vorsicht", "Nomen",
         "계단에서는 주의가 필요해요.", "Auf der Treppe ist Vorsicht nötig.",
         "caution", "Noun", "Caution is needed on the stairs."),
        ("금지하다", "geumjihada", "verbieten", "Verb",
         "여기서는 흡연을 금지해요.", "Hier ist Rauchen verboten.",
         "to prohibit", "Verb", "Smoking is prohibited here."),
        ("출입", "churip", "Zutritt", "Nomen",
         "여기는 출입 금지예요.", "Hier ist der Zutritt verboten.",
         "entry", "Noun", "Entry is forbidden here."),
        ("벌", "beol", "Strafe", "Nomen",
         "거짓말을 하면 벌을 받아요.", "Auf Lügen folgt eine Strafe.",
         "punishment", "Noun", "Lying brings punishment."),
        ("사회생활", "sahoesaenghwal", "Berufsleben", "Nomen",
         "사회생활에서는 예의가 중요해요.", "Im Berufsleben ist Höflichkeit wichtig.",
         "social life", "Noun", "Manners matter in social life."),
        ("세상", "sesang", "Welt (Leben)", "Nomen",
         "세상에는 좋은 사람이 많아요.", "Auf der Welt gibt es viele gute Menschen.",
         "world", "Noun", "There are many good people in the world."),
        ("임산부", "imsanbu", "Schwangere", "Nomen",
         "임산부에게 자리를 양보하세요.", "Überlassen Sie Schwangeren den Platz.",
         "pregnant woman", "Noun", "Give up your seat to pregnant women."),
        ("무료", "muryo", "kostenlos", "Nomen",
         "입장은 무료예요.", "Der Eintritt ist kostenlos.",
         "free of charge", "Noun", "Admission is free."),
    ]),
    ("b2_abstract_concepts_1", "Abstrakte Begriffe", [
        ("경우", "gyeongu", "Fall", "Nomen",
         "비가 올 경우에는 취소돼요.", "Im Fall von Regen wird es abgesagt.",
         "case", "Noun", "In case of rain it is canceled."),
        ("전체", "jeonche", "Gesamtheit", "Nomen",
         "학생 전체가 참여했어요.", "Alle Schüler haben teilgenommen.",
         "whole", "Noun", "All the students participated."),
        ("정도", "jeongdo", "Ausmaß", "Nomen",
         "삼십 분 정도 걸려요.", "Es dauert etwa dreißig Minuten.",
         "degree", "Noun", "It takes about thirty minutes."),
        ("종류", "jongnyu", "Sorte", "Nomen",
         "차 종류가 정말 많네요.", "Es gibt wirklich viele Teesorten.",
         "kind", "Noun", "There are so many kinds of tea."),
        ("느낌", "neukkim", "Gefühl", "Nomen",
         "이 노래는 느낌이 좋아요.", "Dieses Lied fühlt sich gut an.",
         "feeling", "Noun", "This song has a good feeling."),
        ("핵심", "haeksim", "Kern", "Nomen",
         "문제의 핵심을 말해 주세요.", "Nennen Sie bitte den Kern des Problems.",
         "core", "Noun", "Please state the core of the problem."),
        ("유형", "yuhyeong", "Typ", "Nomen",
         "시험 문제 유형을 분석했어요.", "Ich habe die Aufgabentypen der Prüfung analysiert.",
         "type", "Noun", "I analyzed the exam question types."),
        ("부분", "bubun", "Teil", "Nomen",
         "이 부분을 다시 설명해 주세요.", "Erklären Sie diesen Teil bitte noch einmal.",
         "part", "Noun", "Please explain this part again."),
        ("내용", "naeyong", "Inhalt", "Nomen",
         "책 내용이 어려워요.", "Der Inhalt des Buches ist schwierig.",
         "content", "Noun", "The content of the book is difficult."),
        ("주제", "juje", "Thema", "Nomen",
         "오늘 회의 주제가 뭐예요?", "Was ist das Thema der heutigen Sitzung?",
         "topic", "Noun", "What is the topic of today's meeting?"),
        ("자료", "jaryo", "Material", "Nomen",
         "발표 자료를 준비했어요.", "Ich habe die Präsentationsunterlagen vorbereitet.",
         "material", "Noun", "I prepared the presentation materials."),
        ("비결", "bigyeol", "Geheimtipp", "Nomen",
         "건강의 비결이 뭐예요?", "Was ist das Geheimnis Ihrer Gesundheit?",
         "secret", "Noun", "What is the secret of your health?"),
    ]),
    ("b2_language_grammar_1", "Sprache & Grammatik", [
        ("문법", "munbeop", "Grammatik", "Nomen",
         "한국어 문법은 재미있어요.", "Koreanische Grammatik macht Spaß.",
         "grammar", "Noun", "Korean grammar is fun."),
        ("명사", "myeongsa", "Substantiv", "Nomen",
         "이 단어는 명사예요.", "Dieses Wort ist ein Substantiv.",
         "noun", "Noun", "This word is a noun."),
        ("동사", "dongsa", "Verb", "Nomen",
         "동사는 문장 끝에 와요.", "Das Verb steht am Satzende.",
         "verb", "Noun", "The verb comes at the end of the sentence."),
        ("형용사", "hyeongyongsa", "Adjektiv", "Nomen",
         "형용사로 기분을 표현해요.", "Mit Adjektiven drückt man Gefühle aus.",
         "adjective", "Noun", "You express feelings with adjectives."),
        ("부사", "busa", "Adverb", "Nomen",
         "부사는 동사를 꾸며요.", "Adverbien beschreiben das Verb.",
         "adverb", "Noun", "Adverbs modify the verb."),
        ("자음", "jaeum", "Konsonant", "Nomen",
         "한글에는 자음이 열아홉 개 있어요.", "Hangul hat neunzehn Konsonanten.",
         "consonant", "Noun", "Hangul has nineteen consonants."),
        ("모음", "moeum", "Vokal", "Nomen",
         "모음부터 배웠어요.", "Ich habe zuerst die Vokale gelernt.",
         "vowel", "Noun", "I learned the vowels first."),
        ("반의어", "banuieo", "Antonym", "Nomen",
         "크다의 반의어는 작다예요.", "Das Antonym von groß ist klein.",
         "antonym", "Noun", "The antonym of big is small."),
        ("동의어", "donguieo", "Synonym", "Nomen",
         "두 단어는 동의어예요.", "Die beiden Wörter sind Synonyme.",
         "synonym", "Noun", "The two words are synonyms."),
        ("철자", "cheolja", "Rechtschreibung", "Nomen",
         "철자를 자주 틀려요.", "Ich mache oft Rechtschreibfehler.",
         "spelling", "Noun", "I often make spelling mistakes."),
        ("오류", "oryu", "Fehler", "Nomen",
         "문장에 오류가 있어요.", "Im Satz ist ein Fehler.",
         "error", "Noun", "There is an error in the sentence."),
        ("외우다", "oeuda", "auswendig lernen", "Verb",
         "단어를 매일 외워요.", "Ich lerne jeden Tag Wörter auswendig.",
         "to memorize", "Verb", "I memorize words every day."),
    ]),
    ("b2_household_practical_1", "Haushalt & Praktisches", [
        ("온도", "ondo", "Temperatur", "Nomen",
         "방 온도가 너무 높아요.", "Die Zimmertemperatur ist zu hoch.",
         "temperature", "Noun", "The room temperature is too high."),
        ("습도", "seupdo", "Luftfeuchtigkeit", "Nomen",
         "여름에는 습도가 높아요.", "Im Sommer ist die Luftfeuchtigkeit hoch.",
         "humidity", "Noun", "Humidity is high in summer."),
        ("조절하다", "jojeolhada", "regulieren", "Verb",
         "에어컨 온도를 조절했어요.", "Ich habe die Klimaanlage eingestellt.",
         "to adjust", "Verb", "I adjusted the air conditioner."),
        ("건조하다", "geonjohada", "trocken", "Adjektiv",
         "겨울에는 공기가 건조해요.", "Im Winter ist die Luft trocken.",
         "dry", "Adjective", "The air is dry in winter."),
        ("가습기", "gaseupgi", "Luftbefeuchter", "Nomen",
         "방에 가습기를 켰어요.", "Ich habe den Luftbefeuchter im Zimmer angemacht.",
         "humidifier", "Noun", "I turned on the humidifier in the room."),
        ("형광등", "hyeonggwangdeung", "Leuchtstofflampe", "Nomen",
         "형광등을 갈아야 해요.", "Die Leuchtstofflampe muss gewechselt werden.",
         "fluorescent light", "Noun", "The fluorescent light needs changing."),
        ("뚜껑", "ttukkeong", "Deckel", "Nomen",
         "병 뚜껑을 열어 주세요.", "Öffne bitte den Flaschendeckel.",
         "lid", "Noun", "Please open the bottle lid."),
        ("봉투", "bongtu", "Umschlag", "Nomen",
         "편지를 봉투에 넣었어요.", "Ich habe den Brief in den Umschlag gesteckt.",
         "envelope", "Noun", "I put the letter in the envelope."),
        ("서랍", "seorap", "Schublade", "Nomen",
         "서랍에 열쇠가 있어요.", "Der Schlüssel ist in der Schublade.",
         "drawer", "Noun", "The key is in the drawer."),
        ("담다", "damda", "hineintun", "Verb",
         "과일을 바구니에 담았어요.", "Ich habe das Obst in den Korb getan.",
         "to put in", "Verb", "I put the fruit in the basket."),
        ("젖다", "jeotda", "nass werden", "Verb",
         "비에 옷이 다 젖었어요.", "Meine Kleidung ist im Regen ganz nass geworden.",
         "to get wet", "Verb", "My clothes got all wet in the rain."),
        ("말리다", "mallida", "trocknen", "Verb",
         "머리를 말리고 나갈게요.", "Ich trockne mir die Haare und gehe dann los.",
         "to dry", "Verb", "I will dry my hair and then leave."),
    ]),
    ("b2_relationships_people_1", "Menschen & Beziehungen", [
        ("부부", "bubu", "Ehepaar", "Nomen",
         "그 부부는 정말 행복해 보여요.", "Das Ehepaar sieht wirklich glücklich aus.",
         "married couple", "Noun", "That couple looks really happy."),
        ("친척", "chincheok", "Verwandte", "Nomen",
         "명절에 친척들이 모여요.", "An Feiertagen kommen die Verwandten zusammen.",
         "relatives", "Noun", "Relatives gather on holidays."),
        ("애인", "aein", "Partner", "Nomen",
         "애인과 영화를 봤어요.", "Ich habe mit meinem Partner einen Film gesehen.",
         "romantic partner", "Noun", "I watched a movie with my partner."),
        ("동창", "dongchang", "Schulfreund", "Nomen",
         "어제 고등학교 동창을 만났어요.", "Gestern habe ich einen alten Schulfreund getroffen.",
         "schoolmate", "Noun", "I met a high school classmate yesterday."),
        ("자식", "jasik", "Kind (aus Elternsicht)", "Nomen",
         "부모는 자식을 걱정해요.", "Eltern sorgen sich um ihre Kinder.",
         "one's children", "Noun", "Parents worry about their children."),
        ("쌍둥이", "ssangdungi", "Zwillinge", "Nomen",
         "제 동생들은 쌍둥이예요.", "Meine jüngeren Geschwister sind Zwillinge.",
         "twins", "Noun", "My younger siblings are twins."),
        ("닮다", "damda", "ähneln", "Verb",
         "저는 아버지를 닮았어요.", "Ich ähnele meinem Vater.",
         "to resemble", "Verb", "I resemble my father."),
        ("몸매", "mommae", "Figur", "Nomen",
         "운동으로 몸매를 관리해요.", "Mit Sport halte ich meine Figur.",
         "figure", "Noun", "I keep my figure through exercise."),
        ("실수하다", "silsuhada", "einen Fehler machen", "Verb",
         "발표에서 실수했어요.", "Bei der Präsentation habe ich einen Fehler gemacht.",
         "to make a mistake", "Verb", "I made a mistake in the presentation."),
        ("서투르다", "seotureuda", "ungeschickt", "Adjektiv",
         "아직 한국어가 서툴러요.", "Mein Koreanisch ist noch holprig.",
         "clumsy", "Adjective", "My Korean is still clumsy."),
        ("울리다", "ullida", "zum Weinen bringen", "Verb",
         "동생을 울리지 마!", "Bring deine kleine Schwester nicht zum Weinen!",
         "to make cry", "Verb", "Do not make your little sister cry!"),
        ("잘생기다", "jalsaenggida", "gut aussehend", "Adjektiv",
         "그 배우는 정말 잘생겼어요.", "Dieser Schauspieler sieht wirklich gut aus.",
         "handsome", "Adjective", "That actor is really handsome."),
    ]),
    ("b2_safety_rules_1", "Sicherheit & Regeln", [
        ("위험", "wiheom", "Gefahr", "Nomen",
         "공사장은 위험이 많아요.", "Auf der Baustelle gibt es viele Gefahren.",
         "danger", "Noun", "Construction sites have many dangers."),
        ("안전하다", "anjeonhada", "sicher", "Adjektiv",
         "이 동네는 밤에도 안전해요.", "Dieses Viertel ist auch nachts sicher.",
         "safe", "Adjective", "This neighborhood is safe even at night."),
        ("보관하다", "bogwanhada", "aufbewahren", "Verb",
         "귀중품은 금고에 보관하세요.", "Bewahren Sie Wertsachen im Safe auf.",
         "to store", "Verb", "Store valuables in the safe."),
        ("정지하다", "jeongjihada", "stoppen", "Verb",
         "빨간불에서는 정지해야 해요.", "Bei Rot muss man anhalten.",
         "to stop", "Verb", "You must stop at a red light."),
        ("유통기한", "yutonggihan", "Haltbarkeitsdatum", "Nomen",
         "우유 유통기한을 확인하세요.", "Prüfen Sie das Haltbarkeitsdatum der Milch.",
         "expiration date", "Noun", "Check the milk's expiration date."),
        ("지키다", "jikida", "einhalten", "Verb",
         "약속을 꼭 지키세요.", "Halten Sie Ihr Versprechen unbedingt ein.",
         "to keep", "Verb", "Be sure to keep your promise."),
        ("비상", "bisang", "Notfall", "Nomen",
         "비상 상황에는 이 버튼을 누르세요.", "Im Notfall drücken Sie diesen Knopf.",
         "emergency", "Noun", "Press this button in an emergency."),
        ("사고", "sago", "Unfall", "Nomen",
         "어제 길에서 사고가 났어요.", "Gestern gab es auf der Straße einen Unfall.",
         "accident", "Noun", "There was an accident on the road yesterday."),
        ("즉시", "jeuksi", "sofort", "Adverb",
         "문제가 생기면 즉시 연락하세요.", "Bei Problemen melden Sie sich sofort.",
         "immediately", "Adverb", "Contact us immediately if problems arise."),
        ("무조건", "mujogeon", "bedingungslos", "Adverb",
         "무조건 오세요.", "Kommen Sie auf jeden Fall.",
         "unconditionally", "Adverb", "Come no matter what."),
        ("반드시", "bandeusi", "unbedingt", "Adverb",
         "안전벨트를 반드시 매세요.", "Schnallen Sie sich unbedingt an.",
         "certainly", "Adverb", "Be sure to wear your seat belt."),
        ("고지서", "gojiseo", "Gebührenbescheid", "Nomen",
         "전기 요금 고지서가 왔어요.", "Die Stromrechnung ist gekommen.",
         "bill notice", "Noun", "The electricity bill has arrived."),
    ]),
    ("b2_events_culture_1", "Feste & Traditionen", [
        ("예매하다", "yemaehada", "im Voraus buchen", "Verb",
         "기차표를 미리 예매했어요.", "Ich habe die Zugtickets im Voraus gebucht.",
         "to book in advance", "Verb", "I booked the train tickets in advance."),
        ("소풍", "sopung", "Ausflug", "Nomen",
         "내일 학교에서 소풍을 가요.", "Morgen macht die Schule einen Ausflug.",
         "picnic", "Noun", "The school goes on a picnic tomorrow."),
        ("음력", "eumnyeok", "Mondkalender", "Nomen",
         "설날은 음력 1월 1일이에요.", "Seollal ist der erste Tag des Mondkalenders.",
         "lunar calendar", "Noun", "Seollal is the first day of the lunar calendar."),
        ("제사", "jesa", "Ahnenzeremonie", "Nomen",
         "명절에 제사를 지내요.", "An Feiertagen halten wir die Ahnenzeremonie ab.",
         "ancestral rite", "Noun", "We hold ancestral rites on holidays."),
        ("윷놀이", "yunnori", "Yut-Spiel", "Nomen",
         "설날에 가족과 윷놀이를 해요.", "An Seollal spielen wir mit der Familie Yut.",
         "yut game", "Noun", "We play yut with the family at Seollal."),
        ("관객", "gwangaek", "Zuschauer", "Nomen",
         "공연장에 관객이 가득해요.", "Die Halle ist voller Zuschauer.",
         "audience", "Noun", "The hall is full of spectators."),
        ("기념하다", "ginyeomhada", "feierlich begehen", "Verb",
         "결혼 10주년을 기념했어요.", "Wir haben den zehnten Hochzeitstag gefeiert.",
         "to commemorate", "Verb", "We celebrated our tenth wedding anniversary."),
        ("촛불", "chotbul", "Kerzenlicht", "Nomen",
         "케이크에 촛불을 켰어요.", "Wir haben die Kerzen auf der Torte angezündet.",
         "candlelight", "Noun", "We lit the candles on the cake."),
        ("국기", "gukgi", "Nationalflagge", "Nomen",
         "광복절에 국기를 달아요.", "Am Befreiungstag hängen wir die Nationalflagge auf.",
         "national flag", "Noun", "We fly the national flag on Liberation Day."),
        ("세계", "segye", "Welt (Erde)", "Nomen",
         "세계 여러 나라를 여행하고 싶어요.", "Ich möchte viele Länder der Welt bereisen.",
         "world", "Noun", "I want to travel to many countries of the world."),
        ("공휴일", "gonghyuil", "gesetzlicher Feiertag", "Nomen",
         "내일은 공휴일이라서 쉬어요.", "Morgen ist Feiertag und wir haben frei.",
         "public holiday", "Noun", "Tomorrow is a public holiday so we rest."),
        ("야경", "yagyeong", "Nachtansicht", "Nomen",
         "서울의 야경이 아름다워요.", "Die nächtliche Skyline von Seoul ist wunderschön.",
         "night view", "Noun", "Seoul's night view is beautiful."),
    ]),
    ("b2_thinking_verbs_1", "Handeln & Verändern", [
        ("발견하다", "balgyeonhada", "entdecken", "Verb",
         "새로운 카페를 발견했어요.", "Ich habe ein neues Café entdeckt.",
         "to discover", "Verb", "I discovered a new café."),
        ("이루다", "iruda", "verwirklichen", "Verb",
         "드디어 꿈을 이뤘어요.", "Endlich habe ich meinen Traum verwirklicht.",
         "to achieve", "Verb", "I finally achieved my dream."),
        ("이어지다", "ieojida", "sich fortsetzen", "Verb",
         "회의가 밤까지 이어졌어요.", "Die Sitzung zog sich bis in die Nacht.",
         "to continue", "Verb", "The meeting continued into the night."),
        ("간직하다", "ganjikhada", "bewahren", "Verb",
         "그 추억을 마음에 간직할게요.", "Diese Erinnerung bewahre ich im Herzen.",
         "to treasure", "Verb", "I will treasure that memory in my heart."),
        ("갖추다", "gatchuda", "ausstatten", "Verb",
         "이 호텔은 모든 시설을 갖췄어요.", "Dieses Hotel ist mit allem ausgestattet.",
         "to equip", "Verb", "This hotel is equipped with everything."),
        ("전하다", "jeonhada", "übermitteln", "Verb",
         "가족에게 안부를 전해 주세요.", "Richten Sie Ihrer Familie Grüße aus.",
         "to convey", "Verb", "Please give my regards to your family."),
        ("모이다", "moida", "sich versammeln", "Verb",
         "주말에 가족이 다 모여요.", "Am Wochenende kommt die ganze Familie zusammen.",
         "to gather", "Verb", "The whole family gathers on weekends."),
        ("담그다", "damgeuda", "einlegen", "Verb",
         "가을에 김치를 담가요.", "Im Herbst legen wir Kimchi ein.",
         "to pickle", "Verb", "We make kimchi in autumn."),
        ("섞이다", "seokkida", "sich vermischen", "Verb",
         "물과 기름은 잘 안 섞여요.", "Wasser und Öl vermischen sich nicht gut.",
         "to be mixed", "Verb", "Water and oil do not mix well."),
        ("정하다", "jeonghada", "festlegen", "Verb",
         "약속 시간을 정합시다.", "Legen wir die Uhrzeit fest.",
         "to decide", "Verb", "Let us set the meeting time."),
        ("변하다", "byeonhada", "sich verändern", "Verb",
         "십 년 사이에 도시가 많이 변했어요.", "In zehn Jahren hat sich die Stadt stark verändert.",
         "to change", "Verb", "The city changed a lot in ten years."),
        ("나누다", "nanuda", "teilen", "Verb",
         "빵을 반으로 나눴어요.", "Ich habe das Brot halbiert.",
         "to share", "Verb", "I divided the bread in half."),
    ]),
    ("b2_honorifics_1", "Ehrensprache", [
        ("말씀", "malsseum", "Worte (ehrerbietig)", "Nomen",
         "선생님 말씀 잘 들었어요.", "Ich habe Ihre Worte aufmerksam gehört.",
         "words (honorific)", "Noun", "I listened carefully to your words."),
        ("연세", "yeonse", "Alter (ehrerbietig)", "Nomen",
         "할아버지 연세가 어떻게 되세요?", "Wie alt ist Ihr Großvater?",
         "age (honorific)", "Noun", "How old is your grandfather?"),
        ("성함", "seongham", "Name (ehrerbietig)", "Nomen",
         "성함이 어떻게 되세요?", "Wie ist Ihr werter Name?",
         "name (honorific)", "Noun", "May I ask your name?"),
        ("생신", "saengsin", "Geburtstag (ehrerbietig)", "Nomen",
         "내일이 할머니 생신이에요.", "Morgen hat meine Großmutter Geburtstag.",
         "birthday (honorific)", "Noun", "Tomorrow is my grandmother's birthday."),
        ("댁", "daek", "Haus (ehrerbietig)", "Nomen",
         "선생님 댁에 초대받았어요.", "Ich wurde zum Haus des Lehrers eingeladen.",
         "house (honorific)", "Noun", "I was invited to the teacher's house."),
        ("드리다", "deurida", "geben (ehrerbietig)", "Verb",
         "할머니께 선물을 드렸어요.", "Ich habe meiner Großmutter ein Geschenk überreicht.",
         "to give (honorific)", "Verb", "I gave my grandmother a present."),
        ("뵙다", "boepda", "treffen (ehrerbietig)", "Verb",
         "내일 뵙겠습니다.", "Ich freue mich Sie morgen zu sehen.",
         "to meet (humble)", "Verb", "I will see you tomorrow."),
        ("여쭈다", "yeojjuda", "fragen (ehrerbietig)", "Verb",
         "선생님께 여쭤 볼게요.", "Ich werde den Lehrer ehrerbietig fragen.",
         "to ask (humble)", "Verb", "I will ask the teacher politely."),
        ("주무시다", "jumusida", "schlafen (ehrerbietig)", "Verb",
         "부모님은 벌써 주무세요.", "Meine Eltern schlafen schon.",
         "to sleep (honorific)", "Verb", "My parents are already asleep."),
        ("드시다", "deusida", "essen (ehrerbietig)", "Verb",
         "많이 드세요!", "Greifen Sie zu!",
         "to eat (honorific)", "Verb", "Please help yourself!"),
        ("계시다", "gyesida", "sich befinden (ehrerbietig)", "Verb",
         "어머니는 지금 집에 계세요.", "Meine Mutter ist gerade zu Hause.",
         "to be (honorific)", "Verb", "My mother is at home right now."),
        ("잡수시다", "japsusida", "speisen (ehrerbietig)", "Verb",
         "할머니는 아침을 잡수셨어요.", "Meine Großmutter hat gefrühstückt.",
         "to eat (very honorific)", "Verb", "My grandmother ate breakfast."),
    ]),
]


def next_id_start(rows):
    mx = 0
    for r in rows:
        m = re.fullmatch(re.escape(ID_PREFIX) + r"(\d+)", r["id"].strip())
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1


def main():
    rows = list(csv.DictReader(open(VOCAB, encoding="utf-8")))
    existing = {r["korean"].strip() for r in rows}
    seq = next_id_start(rows)

    to_add = []
    for pack_id, topic, words in PACKS:
        n = len(words)
        for i, (ko, rom, de, posde, exko, exde, en, posen, exen) in enumerate(words):
            if ko in existing:
                print(f"skip (exists): {ko}")
                continue
            assert not any("," in f for f in (ko, de, exko, exde, en, exen)), f"comma in {ko}"
            boss = "true" if i >= n - 3 else "false"
            to_add.append([
                ko, rom, de, LEVEL, posde, exko, exde, topic, pack_id,
                i + 1, boss, en, posen, exen, f"{ID_PREFIX}{seq:04d}",
            ])
            existing.add(ko)
            seq += 1

    print(f"neu: {len(to_add)} Wörter in {len(PACKS)} Paketen")
    for r in to_add:
        print(f"  {r[8]} #{r[9]:>2}{'★' if r[10] == 'true' else ' '} {r[0]} — {r[2]}")

    if "--write" in sys.argv and to_add:
        with open(VOCAB, "a", encoding="utf-8", newline="") as f:
            w = csv.writer(f)
            for r in to_add:
                w.writerow(r)
        print(f"\n✅ {len(to_add)} Zeilen an {VOCAB} angehängt")
    else:
        print("\n(Dry-Run — mit --write anhängen)")


if __name__ == "__main__":
    main()
