"""KP06 experience and duration sources; publication requires separate review."""
from phase_task_authoring import choice, grammar_task, loc, packet, sentence, task, write_source


def kp06():
    rows = [
        ('G2:-는2', loc('동사 -는은 현재의 행동으로 뒤 명사를 꾸며요. 수식받는 사람이 그 행동을 하는지 문맥에서 확인해요.', 'Verb + -는 identifies a noun through a present action. Use context to identify who acts.', 'Verb + -는 bestimmt ein Nomen durch eine gegenwärtige Handlung. Kläre im Kontext, wer handelt.'), ('지금 노래하는 사람이 소라예요.', '소라가 지금 노래해요.', '소라는 어제 노래를 끝냈어요.'), ('저기 그림을 그리는 사람이 준호예요.', '준호가 지금 그림을 그려요.', '준호가 내일 그림을 그릴 예정이에요.')),
        ('G2:-은2', loc('동사의 -(으)ㄴ은 여기서 이미 한 행동으로 명사를 꾸며요. 앞으로 할 일과 구별해요.', 'With these verbs, -(으)ㄴ describes a completed past action, not a future plan.', 'Bei diesen Verben beschreibt -(으)ㄴ eine vergangene, ausgeführte Handlung, keinen Zukunftsplan.'), ('지난주에 만든 컵을 가져왔어요.', '컵을 이미 만들었어요.', '컵은 다음 주에 만들 거예요.'), ('어제 찍은 사진을 보여 줄게요.', '사진을 어제 찍었어요.', '사진은 아직 찍지 않았어요.')),
        ('G2:-은3', loc('형용사의 -(으)ㄴ은 성질·상태로 명사를 꾸며요. 작은은 과거에 작았다는 뜻이 아니에요.', 'With adjectives, -(으)ㄴ describes a quality or state. 작은 does not itself mean previously small.', 'Bei Adjektiven beschreibt -(으)ㄴ eine Eigenschaft oder einen Zustand. 작은 bedeutet nicht von sich aus früher klein.'), ('밝은 방에서 그림을 그려요.', '그림을 그리는 방이 밝아요.', '방이 예전에만 밝았어요.'), ('조용한 카페에서 책을 읽어요.', '책을 읽는 카페가 조용해요.', '카페가 어제만 조용했어요.')),
        ('G2:-을2', loc('동사의 -(으)ㄹ은 여기서 앞으로 할 행동으로 명사를 특정해요. 이미 했다고 바꾸지 않아요.', 'Here, verb + -(으)ㄹ identifies a noun through a future action; the action is not yet completed.', 'Hier bestimmt Verb + -(으)ㄹ ein Nomen durch eine künftige Handlung. Sie ist noch nicht abgeschlossen.'), ('내일 배울 노래가 어려워요.', '노래를 내일 배울 예정이에요.', '노래를 어제 다 배웠어요.'), ('다음 주에 만들 가방의 색을 골랐어요.', '가방을 다음 주에 만들 예정이에요.', '가방 만들기를 이미 끝냈어요.')),
        ('G2:-는 것', loc('-는 것은 행동을 명사처럼 다뤄요. 좋아하는 대상이 사람인지 행동인지 구분해요.', '-는 것 treats an action as a noun phrase. Distinguish liking an activity from liking a person.', '-는 것 macht eine Handlung zur Nominalgruppe. Unterscheide die Vorliebe für eine Tätigkeit von der für eine Person.'), ('저는 사진 찍는 것을 좋아해요.', '좋아하는 활동은 사진 찍기예요.', '사진 찍는 모든 사람을 좋아해요.'), ('미나는 혼자 걷는 것을 좋아해요.', '미나가 좋아하는 활동은 혼자 걷기예요.', '미나는 혼자 걷는 사람을 모두 좋아해요.')),
        ('G2:-기', loc('-기는 행동을 주제·대상으로 만드는 명사형이에요. 활동 이름을 사람 이름으로 읽지 않아요.', '-기 nominalizes an action so it can be a topic or object. It names an activity, not a person.', '-기 nominalisiert eine Handlung, die so Thema oder Objekt sein kann. Gemeint ist eine Tätigkeit, keine Person.'), ('이 모임에서는 책 읽기가 중요해요.', '중요한 활동은 책 읽기예요.', '책을 읽는 사람이 중요하지 않아요.'), ('제 취미는 자전거 타기예요.', '자전거를 타는 것이 취미예요.', '자전거를 타는 사람이 제 취미예요.')),
        ('G2:-을 때', loc('-(으)ㄹ 때는 행동이나 상태와 관련된 시점이에요. 언제인지와 얼마나 오래인지를 구분해요.', '-(으)ㄹ 때 locates an action in a situation or time; distinguish when from how long.', '-(으)ㄹ 때 nennt einen Zeitpunkt oder eine Situation. Unterscheide wann von wie lange.'), ('쉬는 시간이 있을 때 사진을 봐요.', '쉴 시간이 생기면 사진을 봐요.', '사진을 보는 데 늘 한 시간이 걸려요.'), ('친구를 만날 때 이 책을 줄 거예요.', '책을 주는 시점은 친구를 만날 때예요.', '책을 주는 데 하루가 걸려요.')),
        ('G2:-는 동안에', loc('-는 동안에는 어떤 행동이 계속되는 기간 안에 다른 일이 일어남을 나타내요.', '-는 동안에 places another event within the period of an ongoing activity.', '-는 동안에 ordnet ein anderes Ereignis in die Dauer einer laufenden Tätigkeit ein.'), ('버스를 기다리는 동안에 책을 읽었어요.', '기다리는 시간에 책을 읽었어요.', '버스를 탄 뒤에만 책을 읽었어요.'), ('빵을 굽는 동안에 차를 준비했어요.', '빵이 구워지는 시간에 차를 준비했어요.', '빵을 다 먹은 뒤에 차를 준비했어요.')),
        ('G2:-은 지2', loc('-(으)ㄴ 지는 시작이나 사건 이후 흐른 시간을 세어요. 그 시간 내내 쉬지 않고 했다는 뜻은 아니에요.', '-(으)ㄴ 지 measures elapsed time since an event or start, not uninterrupted activity throughout.', '-(으)ㄴ 지 misst die seit einem Ereignis oder Beginn vergangene Zeit, keine ununterbrochene Tätigkeit.'), ('수영을 배운 지 두 달 됐어요.', '수영을 배우기 시작한 뒤 두 달이 지났어요.', '두 달 동안 잠도 안 자고 수영했어요.'), ('이 모임에 가입한 지 일 년 됐어요.', '가입한 때부터 일 년이 지났어요.', '모임이 끝난 뒤 일 년이 지났어요.')),
        ('G2:-은 적이 있다', loc('-(으)ㄴ 적이 있다는 과거 경험의 존재예요. 한 번 이상이라는 뜻이지 현재 진행이나 반복 횟수 전체를 말하지 않아요.', '-(으)ㄴ 적이 있다 reports past experience, at least once. It does not specify the total frequency or a current action.', '-(으)ㄴ 적이 있다 bezeichnet eine mindestens einmalige Erfahrung. Es nennt weder die genaue Häufigkeit noch eine gerade laufende Handlung.'), ('공연에서 노래한 적이 있어요.', '과거에 공연에서 노래한 경험이 있어요.', '지금 공연에서 노래하는 중이에요.'), ('혼자 여행한 적이 없어요.', '혼자 여행한 경험이 없어요.', '혼자 여행한 경험이 한 번 있어요.')),
        ('G2:-어 보다', loc('-아/어 보다는 시험 삼아 하는 행동이에요. 권유만 듣고 실제로 했다고 기록하지 않아요.', '-아/어 보다 invites or reports trying an activity. An invitation alone does not prove it happened.', '-아/어 보다 bezeichnet das Ausprobieren. Eine Aufforderung dazu belegt noch keine ausgeführte Handlung.'), ('이 악기를 한번 연주해 보세요.', '악기 연주를 시도해 보라는 권유예요.', '이미 악기 연주를 끝냈다는 보고예요.'), ('새로운 길로 걸어 봤어요.', '새로운 길로 걷는 경험을 해 봤어요.', '새로운 길을 보기만 하고 걷지 않았어요.')),
        ('G2:-으면서', loc('-(으)면서는 여기서 한 사람이 동시에 하는 두 행동을 연결해요. 순서를 뜻하는 말과 구별해요.', 'Here, -(으)면서 links two simultaneous actions by one person, not a sequence.', 'Hier verbindet -(으)면서 zwei gleichzeitige Handlungen derselben Person, keine Abfolge.'), ('음악을 들으면서 청소했어요.', '음악 듣기와 청소가 겹쳐요.', '음악을 다 들은 뒤에만 청소했어요.'), ('노래를 부르면서 걸었어요.', '노래 부르기와 걷기가 겹쳐요.', '노래가 끝난 뒤에만 걸었어요.')),
        ('G2:-다가1(1)', loc('-다가 앞 행동 도중 다른 일이 생겨요. 문맥 없이 첫 행동의 완료를 단정하지 않아요.', '-다가 introduces an event during another activity. Do not assume the first activity was completed.', '-다가 führt ein Ereignis während einer anderen Tätigkeit ein. Setze deren Abschluss nicht voraus.'), ('책을 읽다가 잠이 들었어요. 책은 다 못 읽었어요.', '책을 읽는 도중 잠들었어요.', '책을 끝까지 읽은 뒤에 잠들었어요.'), ('그림을 그리다가 전화가 왔어요. 그림은 아직 미완성이에요.', '그림을 그리는 도중 전화가 왔어요.', '그림을 완성한 다음 전화가 왔어요.')),
        ('G1:-고 있다', loc('-고 있다는 지금 진행 중인 행동이에요. 배운 지 일 년 같은 경과 기간과 구별해요.', '-고 있다 reports an ongoing action; distinguish it from elapsed time since starting to learn.', '-고 있다 beschreibt eine laufende Handlung. Unterscheide sie von der seit dem Lernbeginn vergangenen Zeit.'), ('노래를 배운 지 한 달 됐어요. 지금 그 노래를 연습하고 있어요.', '현재 하는 일은 노래 연습이에요.', '한 달 내내 쉬지 않고 노래해요.'), ('그림을 배운 지 일 년 됐어요. 지금 꽃을 그리고 있어요.', '현재 하는 일은 꽃 그리기예요.', '일 년 내내 같은 꽃만 그려요.')),
    ]
    tasks = [grammar_task('KP06', i, *row) for i, row in enumerate(rows, 1)]
    def introduction(person, activity, duration, past, future):
        text = f'안녕하세요. 저는 {person}예요. {activity} 모임에 가입한 지 {duration} 됐어요. 지난달에 {past}. 다음 주에는 {future}. 지금은 새 회원에게 모임을 소개하고 있어요.'
        return packet(text, [
            choice('person', loc('소개하는 사람은?', 'Who is introducing the group?', 'Wer stellt die Gruppe vor?'), [person, '새 회원'], loc(f'{person}가 자기 경험을 말해요.', f'{person} describes their own experience.', f'{person} beschreibt die eigene Erfahrung.')),
            choice('duration', loc('가입 후 흐른 시간은?', 'How long since joining?', 'Wie viel Zeit ist seit dem Beitritt vergangen?'), [duration, '아직 가입하지 않음'], loc(f'가입한 지 {duration} 됐다고 했어요.', f'The speaker says {duration} have passed since joining.', f'Seit dem Beitritt sind laut Aussage {duration} vergangen.')),
            choice('past', loc('이미 한 경험은?', 'Which experience already happened?', 'Welche Erfahrung wurde schon gemacht?'), [past, future], loc('지난달 일과 다음 주 계획을 구별해요.', 'Separate last month’s experience from next week’s plan.', 'Trenne die Erfahrung letzten Monat vom Plan für nächste Woche.')),
            choice('future', loc('앞으로 할 일은?', 'What is planned next?', 'Was ist als Nächstes geplant?'), [future, past], loc('다음 주에는이라는 말은 앞으로 할 일을 소개해요.', '다음 주에는 introduces the future plan.', '다음 주에는 leitet den Zukunftsplan ein.')),
        ], 'audio')
    tasks.append(task('KP06', 'listening:01', 'listening', loc('모임의 경험과 다음 계획', 'Group experience and the next plan', 'Gruppenerfahrung und nächster Plan'),
        loc('소개하는 사람, 가입 기간, 지난 경험, 예정된 일을 나눠 들어요.', 'Listen separately for the speaker, membership duration, past experience and future plan.', 'Achte getrennt auf Person, Mitgliedsdauer, Erfahrung und Vorhaben.'),
        introduction('민지', '그림', '세 달', '작은 전시회에 그림을 냈어요', '공원에서 그림을 그릴 거예요'),
        introduction('유나', '사진', '두 달', '시장 사진을 찍었어요', '바다 사진을 찍을 거예요')))
    def email(sender, duration, activity, completed, planned):
        return packet(f'제목: 우리 모임에 올래?\n지수야, 안녕! 나 {sender}야.\n내가 다니는 {activity} 모임을 소개할게. 모임에 다닌 지 {duration} 됐어.\n지난주에 {completed} 사람은 나야. 다음 주에 {planned} 사람은 은우야. 은우는 지난주에는 오지 않았어.\n처음 오는 사람도 참여할 수 있어. 같이 갈래? 답장 줘.\n{sender}', [
            choice('actor_past', loc('지난주 활동을 한 사람은?', 'Who did last week’s activity?', 'Wer hat letzte Woche mitgemacht?'), [sender, '은우'], loc('지난주 행동을 꾸미는 관형절 뒤 사람은 나라고 밝혔어요.', 'The writer identifies themself as the person who did last week’s activity.', 'Die schreibende Person bezeichnet sich als diejenige, die letzte Woche mitgemacht hat.')),
            choice('actor_future', loc('다음 주 활동을 할 사람은?', 'Who will do next week’s activity?', 'Wer wird nächste Woche mitmachen?'), ['은우', sender], loc('다음 주 계획의 사람은 은우예요. 지난주 사람과 바꾸지 않아요.', '은우 is the person assigned to the future activity.', '은우 ist die Person für die künftige Tätigkeit.')),
            choice('duration', loc('보낸 사람이 다닌 기간은?', 'How long has the sender attended?', 'Wie lange nimmt die schreibende Person schon teil?'), [duration, '지난주 하루뿐'], loc(f'보낸 사람의 기간은 {duration}이에요.', f'The sender’s duration is {duration}.', f'Die schreibende Person nimmt seit {duration} teil.')),
            choice('purpose', loc('받는 사람에게 원하는 반응은?', 'What response does the sender request?', 'Um welche Reaktion wird gebeten?'), ['같이 갈지 답장하기', '은우가 지난주에 왔다고 알리기'], loc('초대와 답장 요청이에요. 은우의 지난주 참석을 새로 만들지 않아요.', 'It is an invitation requesting a reply; do not invent 은우’s attendance last week.', 'Die Einladung bittet um eine Antwort. Erfinde keine Teilnahme von 은우 in der Vorwoche.')),
        ])
    tasks.append(task('KP06', 'reading:01', 'reading', loc('친구의 초대 이메일', 'An invitation email from a friend', 'Einladung per E-Mail von einer befreundeten Person'),
        loc('편지 속 나가 누구인지 찾고 과거·미래 관형절의 사람을 구별해요.', 'Identify who 나 refers to and keep past and future activity participants separate.', 'Kläre, auf wen 나 verweist, und trenne die Personen in vergangenen und künftigen Tätigkeiten.'),
        email('소라', '네 달', '요리', '빵을 만든', '국수를 만들'), email('준호', '여섯 달', '음악', '기타를 연주한', '노래를 부를')))
    def diary(day, first, interrupted, reason):
        return packet(f'가상 일기 자료\n날짜: {day}\n오늘 처음 해 본 활동: {first}\n행동 도중 일어난 일: {interrupted}\n끝내지 못한 이유: {reason}\n활동을 끝내지는 못했어요. 사실을 유지해 두 문장으로 적으세요.', [
            sentence('first_experience', loc('처음 한 경험을 쓰세요.', 'Describe the first experience.', 'Beschreibe die erste Erfahrung.'), [f'오늘 처음 {first}.', f'저는 오늘 처음 {first}.'], [f'예전에도 여러 번 {first}.'], loc(f'예: 오늘 처음 {first}. 처음이라는 정보를 유지해요.', f'Example: 오늘 처음 {first}. Preserve that it was the first time.', f'Beispiel: 오늘 처음 {first}. Erhalte die Angabe, dass es das erste Mal war.')),
            sentence('interruption', loc('중단과 미완료를 적으세요.', 'State the interruption and non-completion.', 'Nenne die Unterbrechung und den fehlenden Abschluss.'), [interrupted+' 끝내지는 못했어요.', interrupted+' 다 끝내지는 못했어요.'], [interrupted+' 모두 끝냈어요.'], loc('도중에 생긴 일을 행동 완료로 바꾸지 않아요.', 'Do not turn an interruption into successful completion.', 'Mache aus einer Unterbrechung keinen erfolgreichen Abschluss.')),
        ], 'form')
    tasks.append(task('KP06', 'writing:01', 'writing', loc('처음 해 본 활동의 짧은 일기', 'A short diary of a first attempt', 'Kurzer Tagebucheintrag über einen ersten Versuch'),
        loc('처음 한 경험과 중단을 따로 적어요. 문장 예시 밖의 자유 표현은 자동 채점되지 않을 수 있어요.', 'Separate first experience from interruption. Free wording outside the reviewed examples may remain unscored.', 'Trenne die erste Erfahrung von der Unterbrechung. Freie Formulierungen außerhalb der geprüften Beispiele können unbewertet bleiben.'),
        diary('6월 3일', '빵을 만들어 봤어요', '빵을 만들다가 정전이 됐어요.', '정전'),
        diary('7월 8일', '화분을 만들어 봤어요', '화분을 만들다가 수업이 끝났어요.', '수업 종료')))
    tasks.append(task('KP06', 'speaking:01', 'speaking', loc('경험을 나누고 동료 초대하기', 'Share an experience and invite a peer', 'Eine Erfahrung teilen und jemanden einladen'),
        loc('상대와 관심사를 연결해 초대하고 답에 맞춰 반응해요. 경험 시점, 초대 이유, 상대가 거절할 여지를 확인하며 다시 녹음하세요. 의미는 미채점이에요.', 'Link the invitation to a shared interest and respond to the peer’s reply. Review timing, invitation reason and freedom to decline, then re-record. Meaning is unscored.', 'Begründe die Einladung mit einem gemeinsamen Interesse und reagiere auf die Antwort. Prüfe Zeitpunkt, Grund und die Möglichkeit abzusagen, dann nimm erneut auf. Der Inhalt bleibt unbewertet.'),
        packet('같은 취미가 있는 동료와 해요체로 이야기해요.\n나: 지난달 처음 빵을 만들어 봄.\n상대: 빵 만들기에 관심 있음. 토요일은 바쁘고 일요일은 가능.\n일요일 모임에 초대하고, 일요일에는 갈 수 있어요라는 응답에 답하세요.', []),
        packet('같은 취미가 있는 동료와 해요체로 이야기해요.\n나: 지난주 처음 도자기를 만들어 봄.\n상대: 도자기에 관심 있음. 이번 주에는 못 감.\n모임에 초대한 뒤 이번 주는 어려워요라는 응답에 압박 없이 답하세요.', [])))
    return tasks


if __name__ == '__main__':
    write_source('KP06', kp06())
