#!/usr/bin/env python3
"""build_satzbauen.py — Satzbau-Daten (Wort-Kacheln) aus VORHANDENEN,
muttersprachlich geprüften Beispielsätzen erzeugen. Keine neue Übersetzung (§0).

Quelle: korean_vocab.csv `example_korean` (≥3 Eojeol) + `example_german/english`.
Pro Satz: Ziel = der Satz, Kacheln = seine Eojeol + 2 Distraktor-Eojeol aus
anderen Sätzen desselben Levels (echte Wörter, nicht im Zielsatz). Speist den
bestehenden SatzBauenQuest (targetKo/promptDe/promptEn/distractors).

Aktiver Abruf + SOV-Wortstellung = stärkste Lernwirkung (Forschung).

Nutzung:
    python3 tools/content_factory/build_satzbauen.py          # Dry-Run
    python3 tools/content_factory/build_satzbauen.py --write  # → assets/data/satz_sentences.json
"""
import csv
import json
import os
import sys
import zlib
from random import Random

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
VOCAB = os.path.join(ROOT, "assets", "data", "korean_vocab.csv")
OUT = os.path.join(ROOT, "assets", "data", "satz_sentences.json")

MIN_TOKENS = 3
NUM_DISTRACTORS = 2


def strip_punct(tok):
    return tok.strip(" !?.,…~\"'()")


def load_rows():
    with open(VOCAB, encoding="utf-8") as f:
        return list(csv.DictReader(f))


def build(rows):
    by_level = {}
    for r in rows:
        by_level.setdefault(r["level"], []).append(r)

    # Eojeol-Vorrat pro Level (für Distraktoren), dedupe.
    level_tokens = {}
    for lvl, rs in by_level.items():
        toks = []
        seen = set()
        for r in rs:
            for t in r["example_korean"].split():
                t = strip_punct(t)
                if t and t not in seen and any("가" <= c <= "힣" for c in t):
                    seen.add(t)
                    toks.append(t)
        level_tokens[lvl] = toks

    items = []
    seen_targets = set()
    skipped = {"short": 0, "no_translation": 0, "few_distractors": 0, "dupe": 0}
    for r in rows:
        ex = r["example_korean"].strip()
        if ex in seen_targets:
            skipped["dupe"] += 1
            continue
        de = r["example_german"].strip()
        en = r["example_english"].strip()
        level = r["level"].strip()
        tokens = ex.split()
        if len(tokens) < MIN_TOKENS:
            skipped["short"] += 1
            continue
        if not de:
            skipped["no_translation"] += 1
            continue

        own = {strip_punct(t) for t in tokens}
        # Plausible Kachel-Distraktoren: kurze Eojeol (≤4 Zeichen), nicht im Satz.
        pool = [
            t for t in level_tokens.get(level, [])
            if t not in own and len(t) <= 4
        ]
        if len(pool) < NUM_DISTRACTORS:
            skipped["few_distractors"] += 1
            continue
        # Pro Satz variieren (stabiler Seed aus dem Zieltext) → nicht überall
        # dieselben zwei Distraktoren.
        rnd = Random(zlib.crc32(ex.encode("utf-8")))
        distractors = rnd.sample(pool, NUM_DISTRACTORS)

        seen_targets.add(ex)
        items.append({
            "level": level.lower(),
            "targetKo": ex,
            "promptDe": de,
            "promptEn": en,
            "distractors": distractors,
            # Headword, zu dem dieser Beispielsatz gehört → echtes SRS-Futter
            # (NICHT der ganze Satz → keine Geisterkarten).
            "vocabKo": r["korean"].strip(),
        })

    return items, skipped


def main():
    rows = load_rows()
    items, skipped = build(rows)
    by_level = {}
    for it in items:
        by_level[it["level"]] = by_level.get(it["level"], 0) + 1
    print(f"Quelle: {len(rows)} Vokabeln")
    print(f"Satzbau erzeugt: {len(items)}  pro Level: {dict(sorted(by_level.items()))}")
    print(f"  übersprungen: {skipped}")
    print("\nBeispiele:")
    for it in items[:8]:
        print(f"  [{it['level']}] {it['targetKo']}  +Dist {it['distractors']}  | {it['promptDe']}")

    if "--write" in sys.argv:
        payload = {
            "meta": {
                "total": len(items),
                "perLevel": dict(sorted(by_level.items())),
                "source": "korean_vocab.csv example sentences (native-reviewed)",
                "note": "Generated by build_satzbauen.py — tiles = sentence eojeol + 2 same-level distractors. No new translation (§0).",
            },
            "items": items,
        }
        with open(OUT, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=1)
        print(f"\n✅ geschrieben: {OUT} ({len(items)} Items)")
    else:
        print("\n(Dry-Run — mit --write speichern)")


if __name__ == "__main__":
    main()
