"""A2-C2 packs for the Korean-partner / family / holiday track."""

from __future__ import annotations

from .partner_family_packs import (
    A2_CON,
    A2_UNIT,
    B1_CON,
    B1_UNIT,
    B2_CON,
    B2_UNIT,
    C1_CON,
    C1_UNIT,
    C2_CON,
    C2_UNIT,
    _pack,
)

REST_PACKS = [
    _pack("partner_dinner_talk", "A2", A2_UNIT, A2_CON, "octagon", "저녁 자리 이야기", "Gespräch am Abendessen", "Talk at the family dinner", [
        ("어디서 오셨어요", "woher kommen Sie", "where are you from", "Ausdruck", "어디서 오셨어요 하시길래 독일 베를린이라고 했어요.", "Sie fragten, woher ich komme, also sagte ich Berlin.", "They asked where I am from, so I said Berlin in Germany."),
        ("한국어 잘하시네요", "Sie sprechen gut Koreanisch", "your Korean is good", "Ausdruck", "한국어 잘하시네요는 칭찬인데 더 긴장됐어요.", "Das Lob machte mich noch nervöser.", "Your Korean is good is praise, but I got more nervous."),
        ("직업이 뭐예요", "was sind Sie von Beruf", "what do you do", "Ausdruck", "직업이 뭐예요에 디자이너라고 짧게 답했어요.", "Auf die Berufsfrage antwortete ich kurz Designerin.", "To what do you do I answered designer, briefly."),
        ("언제 왔어요", "wann sind Sie gekommen", "when did you arrive", "Ausdruck", "언제 왔어요는 한국에 온 해를 묻는 말이에요.", "Die Frage meint das Ankunftsjahr in Korea.", "When did you come asks which year I arrived in Korea."),
        ("얼마나 됐어요", "wie lange schon", "how long has it been", "Ausdruck", "사귄 지 얼마나 됐어요를 듣고 현우가 물을 마셨어요.", "Als sie nach der Beziehungsdauer fragten, trank Hyunwoo Wasser.", "When they asked how long we have been together, Hyunwoo drank water."),
        ("소개팅", "Vermittlungsdate", "a set-up date", "Nomen", "소개팅이 아니라 동아리에서 만났다고 했어요.", "Wir haben uns nicht über ein Date, sondern im Verein kennengelernt.", "I said we met in a club, not on a set-up date."),
        ("유창하다", "fließend sein", "to be fluent", "Adjektiv", "유창하지 않아도 천천히 말하면 통해요.", "Auch ohne fließendes Koreanisch versteht man langsames Sprechen.", "Even if it is not fluent, slow speech still works."),
        ("통역 부탁", "Dolmetschbitte", "asking for interpreting", "Nomen", "어려운 말은 현우에게 통역 부탁을 했어요.", "Schwierige Sätze ließ ich mir von Hyunwoo dolmetschen.", "I asked Hyunwoo for interpreting on the hard parts."),
        ("자기소개", "Selbstvorstellung", "self-introduction", "Nomen", "자기소개를 세 문장으로 준비해 갔어요.", "Ich hatte die Selbstvorstellung in drei Sätzen vorbereitet.", "I prepared the self-introduction in three sentences."),
        ("고향 이야기", "Heimatgeschichte", "hometown story", "Ausdruck", "고향 이야기를 하니 할머니가 지도를 찾아오셨어요.", "Als ich von der Heimat erzählte, holte die Großmutter eine Karte.", "When I told a hometown story, grandmother brought a map."),
        ("음식 취향", "Essensvorlieben", "food preferences", "Nomen", "음식 취향을 묻길래 매운 건 조금 먹는다고 했어요.", "Nach den Vorlieben gefragt sagte ich, Scharfes esse ich wenig.", "They asked about food preferences, so I said I eat spicy food a little."),
        ("분위기 파악", "die Stimmung lesen", "reading the room", "Ausdruck", "분위기 파악이 안 되면 현우 얼굴을 봐요.", "Wenn ich die Lage nicht lese, schaue ich Hyunwoo an.", "If I cannot read the room, I look at Hyunwoo's face."),
    ]),
    _pack("partner_seollal_day", "A2", A2_UNIT, A2_CON, "chrysanthemum", "설날 하루", "Ein Seollal-Tag", "A full Seollal day", [
        ("세배하러 가다", "zur Verbeugung gehen", "to go offer New Year bows", "Ausdruck", "오전에 세배하러 가는 집이 세 곳이었어요.", "Vormittags gab es drei Häuser für die Verbeugung.", "In the morning there were three houses for New Year bows."),
        ("떡국 먹다", "Reiskuchensuppe essen", "to eat rice-cake soup", "Ausdruck", "떡국 먹다 보면 한 살이 는다는 농담을 들었어요.", "Beim Essen hörte ich den Witz, man werde ein Jahr älter.", "While eating the soup I heard the joke that you gain a year."),
        ("세뱃돈 사양", "Neujahrsgeld ablehnen", "declining New Year money", "Ausdruck", "어른인데 세뱃돈 사양을 두 번 하고 받았어요.", "Als Erwachsene lehnte ich das Geld zweimal ab und nahm es dann.", "As an adult I declined the New Year money twice, then accepted."),
        ("한복 대여", "Hanbok-Verleih", "hanbok rental", "Nomen", "한복 대여 가게가 명절 전날 문을 일찍 닫았어요.", "Der Hanbok-Verleih schloss am Vortag früh.", "The hanbok rental closed early the day before."),
        ("세배 순서", "Reihenfolge der Verbeugung", "bowing order", "Nomen", "세배 순서는 나이 많은 분부터예요.", "Die Reihenfolge beginnt bei den Ältesten.", "The bowing order starts with the oldest people."),
        ("복주머니", "Glücksbeutel", "lucky pouch", "Nomen", "아이 복주머니에 세뱃돈을 넣어 주셨어요.", "In den Glücksbeutel des Kindes steckten sie das Geld.", "They put the New Year money into the child's lucky pouch."),
        ("설날 인사말", "Seollal-Grußformel", "Seollal greeting line", "Nomen", "설날 인사말을 종이에 적어 주머니에 넣었어요.", "Die Grußformel schrieb ich auf Papier und steckte sie ein.", "I wrote the Seollal greeting on paper and put it in my pocket."),
        ("세배 영상", "Video der Verbeugung", "bowing video", "Nomen", "세배 영상은 가족 앨범에만 두래요.", "Das Video sollte nur ins Familienalbum.", "They said keep the bowing video in the family album only."),
        ("명절 음식", "Festtagsessen", "holiday food", "Nomen", "명절 음식은 전 냄새가 먼저 나요.", "Beim Festtagsessen riecht man zuerst die Pfannengerichte.", "With holiday food you smell the pancakes first."),
        ("전 부치다", "jeon braten", "to fry Korean pancakes", "Ausdruck", "전 부치는 기름이 팔에 튀었어요.", "Beim Braten spritzte Öl auf den Arm.", "Oil from frying jeon splashed on my arm."),
        ("세배 연습", "Verbeugungsübung", "bow practice", "Nomen", "세배 연습을 거울 앞에서 열 번 했어요.", "Die Verbeugung übte ich zehnmal vor dem Spiegel.", "I practiced the bow ten times in front of the mirror."),
        ("새해 목표", "Neujahrsvorsatz", "new-year goal", "Nomen", "새해 목표를 묻길래 한국어 일기라고 했어요.", "Nach dem Vorsatz gefragt sagte ich koreanisches Tagebuch.", "They asked for a new-year goal, so I said a Korean diary."),
    ]),
    _pack("partner_chuseok_day", "A2", A2_UNIT, A2_CON, "chrysanthemum", "추석 하루", "Ein Chuseok-Tag", "A full Chuseok day", [
        ("귀성길", "Heimreiseverkehr", "holiday homebound traffic", "Nomen", "귀성길에서 휴게소 호두과자를 샀어요.", "Im Heimreiseverkehr kaufte ich Walnusskuchen an der Raststätte.", "In holiday traffic I bought walnut cakes at the rest stop."),
        ("송편 맛", "Geschmack der Songpyeon", "songpyeon flavor", "Nomen", "송편 맛이 콩이면 제가 이기고 깨면 현우가 이겨요.", "Bei Bohnenfüllung gewinne ich, bei Sesam Hyunwoo.", "If the filling is bean I win; if sesame, Hyunwoo wins."),
        ("보름달", "Vollmond", "full moon", "Nomen", "보름달을 보며 소원을 말하래요.", "Beim Vollmond sollte ich einen Wunsch sagen.", "They told me to make a wish looking at the full moon."),
        ("성묘 옷", "Kleidung für den Grabbesuch", "clothes for the grave visit", "Nomen", "성묘 옷은 흰색보다 어두운 색이 편해요.", "Für den Grabbesuch sind dunkle Farben bequemer als Weiß.", "For the grave visit dark colors are easier than white."),
        ("벌초 장갑", "Handschuhe zum Jäten", "weeding gloves", "Nomen", "벌초 장갑을 끼고 사진만 찍었어요.", "Mit Jätehandschuhen machte ich nur Fotos.", "I put on weeding gloves and only took photos."),
        ("차례 음식", "Speisen für das Ritual", "food for the rite", "Nomen", "차례 음식은 먹기 전에 먼저 올렸어요.", "Die Ritualspeisen kamen auf den Tisch, bevor jemand ass.", "The rite food was offered before anyone ate."),
        ("송편 만들기", "Songpyeon herstellen", "making songpyeon", "Nomen", "송편 만들기는 손끝이 분홍해지는 일이에요.", "Beim Formen werden die Finger rosa.", "Making songpyeon turns your fingertips pink."),
        ("명절 인사", "Festtagsgruss", "holiday greeting", "Nomen", "카톡 명절 인사는 짧게, 하지만 존댓말로 보냈어요.", "Den Festtagsgruss schickte ich kurz, aber höflich.", "I sent the holiday greeting short, but in honorifics."),
        ("고향집", "Elternhaus in der Heimat", "family home in the hometown", "Nomen", "고향집 마당에 감이 아직 열려 있었어요.", "Im Hof des Elternhauses hingen noch Kakis.", "Persimmons were still hanging in the hometown yard."),
        ("친척 방문", "Verwandtenbesuch", "visiting relatives", "Nomen", "친척 방문이 다섯 집이라 미소를 아껴 썼어요.", "Bei fünf Besuchen sparte ich das Lächeln ein.", "With five relative visits I rationed my smile."),
        ("송편 점", "Songpyeon-Orakel", "songpyeon fortune", "Nomen", "송편 점이 깨면 딸이라는 말에 현우가 숨었어요.", "Bei Sesam werde es eine Tochter, sagte man, und Hyunwoo versteckte sich.", "They said sesame means a daughter, and Hyunwoo hid."),
        ("추석 연휴", "Chuseok-Ferien", "Chuseok long weekend", "Nomen", "추석 연휴 마지막 날 기차가 제일 비쌌어요.", "Am letzten Ferientag war der Zug am teuersten.", "On the last day of the Chuseok break the train was most expensive."),
    ]),
    _pack("partner_sibling_tease", "A2", A2_UNIT, A2_CON, "plum", "형제 장난과 편들기", "Geschwisterscherze", "Sibling teasing and backup", [
        ("놀리다", "aufziehen", "to tease", "Verb", "발음을 놀려도 웃어 주면 금방 끝나요.", "Wenn sie die Aussprache aufziehen und ich lache, ist es vorbei.", "If they tease my pronunciation and I laugh, it ends quickly."),
        ("편들다", "Partei ergreifen", "to take someone's side", "Verb", "현우가 제 편을 들어 줘서 어깨가 내려갔어요.", "Hyunwoo ergriff für mich Partei, da sank die Schulter.", "Hyunwoo took my side, and my shoulders dropped."),
        ("별명", "Spitzname", "nickname", "Nomen", "별명이 생기기 전에 제가 먼저 하나를 정했어요.", "Bevor ein Spitzname entstand, wählte ich selbst einen.", "Before a nickname appeared, I chose one first."),
        ("게임 한 판", "eine Spielrunde", "one game round", "Ausdruck", "게임 한 판 하니 존댓말이 반말로 넘어갔어요.", "Nach einer Runde rutschte die Höflichkeit ins Vertraute.", "After one game, honorifics slipped into casual speech."),
        ("비밀 보장", "ein Geheimnis wahren", "keeping a secret", "Ausdruck", "현우 어릴 적 비밀 보장은 제가 먼저 약속했어요.", "Das Kindheitsgeheimnis zu wahren versprach ich zuerst.", "I promised first to keep Hyunwoo's childhood secret."),
        ("맞장구", "zustimmendes Mitgehen", "supportive backchannel", "Nomen", "맞장구를 너무 크게 해서 국이 흔들렸어요.", "Mein Mitgehen war so laut, dass die Suppe wackelte.", "My backchannel was so loud the soup shook."),
        ("통역 눈짓", "sich mit Blicken verständigen", "to signal with a look", "Ausdruck", "통역 눈짓을 현우가 못 보면 그냥 웃어요.", "Versteht Hyunwoo meinen Blick nicht, lache ich einfach.", "If Hyunwoo doesn't get the look, I just laugh."),
        ("같이 웃다", "zusammen lachen", "to laugh together", "Ausdruck", "같이 웃다 보면 존댓말 실수는 잊혀요.", "Wenn man zusammen lacht, vergisst man Höflichkeitsfehler.", "If you laugh together, honorific mistakes are forgotten."),
        ("동생 편", "Seite des jüngeren Geschwisters", "the younger sibling side", "Ausdruck", "동생 편을 들면 현우가 눈을 흘겨요.", "Halte ich zum jüngeren Geschwister, schielt Hyunwoo.", "If I take the younger sibling side, Hyunwoo side-eyes me."),
        ("단톡방", "Familienchat", "family group chat", "Nomen", "단톡방에 입장하자마자 이모티콘이 쏟아졌어요.", "Kaum war ich im Familienchat, regnete es Sticker.", "As soon as I joined the family group chat, stickers poured in."),
        ("남은 반찬", "übrig gebliebene Beilagen", "leftover side dishes", "Nomen", "남은 반찬 봉투가 두 개라서 양손에 들었어요.", "Ich trug zwei Tüten Reste in beiden Händen.", "I carried two leftover bags, one in each hand."),
        ("반말 실수", "ein vertraulicher Sprachfehler", "a casual-speech slip", "Ausdruck", "반말 실수를 하자 동생이 더 좋아했어요.", "Nach einem vertraulichen Sprachfehler freute sich das jüngere Geschwister noch mehr.", "After a casual-speech slip the younger sibling liked me even more."),
    ]),
]
