"""Directly authored KO/EN/DE review copy; canonical ARB untouched."""
from pathlib import Path
import json
p=Path(__file__).resolve().parents[1]/"content.json"
d=json.loads(p.read_text(encoding="utf-8"))
copy={
 "ko":{"walletTitle":"내 엽전","walletIntro":"한국어를 배우며 모은 엽전으로 한옥을 지어요.","walletExample":"잔액 예시","coinUnit":"엽전","walletAction":"엽전 살펴보기","walletRule":"오늘 처음 완료한 레슨은 20엽전, 다른 두 번째 레슨은 10엽전이에요. 이미 완료한 레슨을 다시 열어도 엽전이 추가되지 않아요.","constructionCost":"다음 건축 단계 · 40엽전","constructionCondition":"학습 경로에서 건축 단계가 해금되어야 지을 수 있어요.","constructionAction":"한옥으로 가기","rewardPreview":"보상 연출 보기","rewardTitle":"오늘의 첫 레슨을 마쳤어요!","rewardReason":"확인된 첫 레슨 완료 보상","rewardBalance":"내 엽전","rewardContinue":"내 엽전 보기","rewardBoundary":"보상 표시 예시예요. 실제 잔액과 보상은 변경하지 않아요.","questTitle":"보자기가 기다려요","questIntro":"달성한 퀘스트·단어 팩·마일스톤의 선물을 열어봐요.","questSample":"완료 예시","questProgress":"보자기 1개 열기","openGift":"보자기 열기","giftHint":"매듭을 탭해 열어보세요","giftPickTitle":"마음에 드는 장식 하나를 골라요","giftPickBody":"고르지 않은 장식도 다음 보자기에서 다시 만날 수 있어요.","giftChosenTitle":"사랑방에 놓을 장식을 골랐어요","giftChosenBody":"시안에서 선택한 장식이에요. 실제 소유 목록은 바뀌지 않아요.","giftRoom":"한옥 살펴보기","giftAgain":"다시 열어보기","giftEmpty":"이번 시안의 보자기를 열었어요","giftToWallet":"엽전 살펴보기","decorSeoan":"서안","decorMunbangsau":"문방사우","decorSoban":"소반"},
 "en":{"walletTitle":"My Yeopjeon","walletIntro":"Learn Korean, collect Yeopjeon and build your Hanok.","walletExample":"Example balance","coinUnit":"Yeopjeon","walletAction":"View Yeopjeon","walletRule":"Your first completed lesson of the day earns 20 Yeopjeon. A different second lesson earns 10. Reopening a completed lesson does not earn more.","constructionCost":"Next building stage · 40 Yeopjeon","constructionCondition":"Complete the relevant learning path unit to unlock a building stage.","constructionAction":"Go to my Hanok","rewardPreview":"Preview the reward","rewardTitle":"Your first lesson today is done!","rewardReason":"Reward for a confirmed first lesson","rewardBalance":"My Yeopjeon","rewardContinue":"View my Yeopjeon","rewardBoundary":"Reward preview. Your real balance and rewards stay unchanged.","questTitle":"A Bojagi is waiting","questIntro":"Open gifts earned through quests, vocabulary packs and milestones.","questSample":"Completion example","questProgress":"Open one Bojagi","openGift":"Open Bojagi","giftHint":"Tap the knot to unwrap it","giftPickTitle":"Choose one decoration you like","giftPickBody":"The others can appear again in a future Bojagi.","giftChosenTitle":"A new piece for your Sarangbang","giftChosenBody":"You chose this decoration in the preview. Your real collection stays unchanged.","giftRoom":"Explore my Hanok","giftAgain":"Unwrap it again","giftEmpty":"You've opened this preview Bojagi","giftToWallet":"View Yeopjeon","decorSeoan":"Seoan · writing desk","decorMunbangsau":"Four treasures of the study","decorSoban":"Soban · small table"},
 "de":{"walletTitle":"Meine Yeopjeon","walletIntro":"Lerne Koreanisch, sammle Yeopjeon und baue dein Hanok.","walletExample":"Beispielguthaben","coinUnit":"Yeopjeon","walletAction":"Yeopjeon ansehen","walletRule":"Für deine erste abgeschlossene Lektion am Tag erhältst du 20 Yeopjeon, für eine zweite andere Lektion 10. Das erneute Öffnen einer abgeschlossenen Lektion bringt keine weiteren Yeopjeon.","constructionCost":"Nächste Bauphase · 40 Yeopjeon","constructionCondition":"Schließe die passende Einheit im Lernpfad ab, um eine Bauphase freizuschalten.","constructionAction":"Zu meinem Hanok","rewardPreview":"Belohnung ansehen","rewardTitle":"Deine erste Lektion heute ist geschafft!","rewardReason":"Belohnung für den bestätigten ersten Abschluss","rewardBalance":"Meine Yeopjeon","rewardContinue":"Meine Yeopjeon ansehen","rewardBoundary":"Belohnungsvorschau. Dein echtes Guthaben und deine Belohnungen ändern sich nicht.","questTitle":"Ein Bojagi wartet auf dich","questIntro":"Öffne Geschenke aus Quests, Wortpaketen und Meilensteinen.","questSample":"Abschlussbeispiel","questProgress":"Ein Bojagi öffnen","openGift":"Bojagi öffnen","giftHint":"Tippe auf den Knoten, um das Bojagi zu öffnen","giftPickTitle":"Wähle ein Dekorationsstück aus","giftPickBody":"Die anderen Stücke können in einem späteren Bojagi wieder auftauchen.","giftChosenTitle":"Ein neues Stück für dein Sarangbang","giftChosenBody":"Du hast dieses Stück in der Vorschau gewählt. Deine echte Sammlung bleibt unverändert.","giftRoom":"Mein Hanok ansehen","giftAgain":"Noch einmal öffnen","giftEmpty":"Dieses Vorschau-Bojagi ist geöffnet","giftToWallet":"Yeopjeon ansehen","decorSeoan":"Seoan · Schreibpult","decorMunbangsau":"Vier Schätze des Studierzimmers","decorSoban":"Soban · kleiner Tisch"}
}
for lang,new in copy.items():d["ui"][lang].update(new)
for lang,label in {"ko":"엽전 모으는 방법","en":"How to earn Yeopjeon","de":"So sammelst du Yeopjeon"}.items():d["ui"][lang]["walletRulesLabel"]=label
for lang,label in {"ko":"시안","en":"Preview","de":"Vorschau"}.items():d["ui"][lang]["reviewBadge"]=label
for lang,label in {"ko":"듣고 자연스럽게 대답해요","en":"Listen, then respond","de":"Hören und natürlich antworten"}.items():d["ui"][lang]["startContext"]=label
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print({lang:len(d["ui"][lang]) for lang in copy})
