// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_opujse33cwt6nOQFxqQJXfgSCW5UkO8',
    appId: '1:573567222361:android:38d26a50001ee64c356748',
    messagingSenderId: '573567222361',
    projectId: 'ko-lernen-app',
    storageBucket: 'ko-lernen-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY76D-dbZeV_Kr8g2UydWoB10Wv7Jc2Qs',
    appId: '1:573567222361:ios:0f8c0734410bb6cc356748',
    messagingSenderId: '573567222361',
    projectId: 'ko-lernen-app',
    storageBucket: 'ko-lernen-app.firebasestorage.app',
    androidClientId: '573567222361-clvvao1nbjue9a8seic223cue51pa5cp.apps.googleusercontent.com',
    iosClientId: '573567222361-uphimptmn43da1snk4hc60rhgjd28ppq.apps.googleusercontent.com',
    iosBundleId: 'com.sujinarin.koLernenApp',
  );
}
