"""Editable KO-first source for the ten context cases. No persona/profile writes."""
import json
from pathlib import Path

def t(value):
    ko, de, en = value.split('|')
    return dict(ko=ko, de=de, en=en)

def scene(person, context, prompt, goal=None, accepted=None):
    result = dict(characterId=person, context=t(context), prompt=t(prompt))
    if goal:
        result['requiredIntentId'] = goal
    if accepted:
        result['acceptedExpressionIds'] = accepted
    return result

def e(id, text, effect):
    return dict(id=id, text=t(text), effect=t(effect), grammarValid=True)

def i(id, label, reply, follow, *expressions):
    return dict(id=id, label=t(label), expressions=[dict(x, partnerReply=t(reply), followUp=t(follow)) for x in expressions])

def c(id, level, topic, title, base, transfer, *intents, phrases=()):
    return dict(id=id, revision=1, level=level, topic=topic, title=t(title), sourcePhraseIds=list(phrases), base=base, transfer=transfer, intents=list(intents))

cases = [
 c('invite_friend', 'a1', 'invite', '친구와 저녁 약속|Mit Freunden verabreden|Making dinner plans',
   scene('christian', '크리스티안은 친한 친구예요. 둘이 편하게 메시지를 주고받고 있어요.|Christian ist ein guter Freund. Ihr schreibt euch privat und ungezwungen.|Christian is a close friend. You are messaging each other casually.', '오늘 저녁에 시간 있어?|Hast du heute Abend Zeit?|Are you free this evening?'),
   scene('maya', '마야도 친한 친구예요. 수업 뒤 둘이 이야기해요. 오늘은 시간이 있지만, 먼저 용건을 알아보세요.|Maya ist ebenfalls eine gute Freundin. Ihr redet nach dem Unterricht. Du hast Zeit, möchtest aber zuerst wissen, worum es geht.|Maya is also a close friend. You are talking after class. You are free, but want to find out what she has in mind first.', '오늘 저녁에 시간 있어?|Hast du heute Abend Zeit?|Are you free this evening?', 'ask', ['casual']),
   i('accept', '만날 수 있다고 말하기|Sagen, dass du Zeit hast|Say you are available', '같이 저녁 먹을래?|Wollen wir zusammen essen?|Want to get dinner together?', '좋아. 몇 시에 만날까?|Gerne. Wann treffen wir uns?|Sure. What time shall we meet?',
     e('casual', '응, 있어. 왜?|Ja. Wieso?|Yeah, I am. Why?', '편하게 답하고 용건을 물어요. 친한 사이에서는 짧아도 무례한 답이 아니에요.|Du sagst ungezwungen, dass du Zeit hast, und fragst nach dem Anlass. Unter guten Freunden ist die kurze Antwort nicht unhöflich.|You answer casually and ask what it is about. A short reply can be friendly between close friends.'),
     e('playful', '네, 시간이 있습니다.|Ja, ich stehe zur Verfügung.|Yes, I am available.', '문법은 맞아요. 평소 반말을 쓰는 친구에게 갑자기 격식을 차리면 장난처럼 들릴 수 있어요. 억양에 따라 거리감도 생길 수 있어요.|Grammatisch stimmt der Satz. Wenn ihr sonst locker redet, kann die plötzliche Förmlichkeit scherzhaft wirken. Je nach Ton kann sie auch Distanz schaffen.|The grammar is correct. Sudden formality with a friend you usually speak casually to can sound playful. Depending on your tone, it may also create distance.')),
   i('ask', '먼저 용건 알아보기|Erst nachfragen|Ask what it is about first', '같이 저녁 먹으려고.|Ich wollte mit dir essen gehen.|I was thinking of getting dinner together.', '좋아. 같이 먹자.|Gerne, lass uns zusammen essen.|Sure. Let’s eat together.',
     e('what', '무슨 일인데?|Worum geht’s denn?|What is it about?', '약속하기 전에 용건을 물어요. 말끝을 세게 하면 따지는 느낌도 날 수 있어요.|Du fragst nach, bevor du zusagst. Mit scharfem Ton kann die Frage vorwurfsvoll wirken.|You ask before committing. A sharp tone could make it sound confrontational.'),
     e('plan', '뭐 하려고?|Was hast du vor?|What are you planning?', '상대의 계획에 관심을 보여요. 아직 만남을 확정하는 말은 아니에요.|Du zeigst Interesse am Plan. Eine feste Zusage ist das noch nicht.|You show interest in the plan. You have not agreed to meet yet.'))),
 c('refuse_today', 'a1', 'refuse', '오늘은 어려워요|Heute passt es nicht|Today does not work',
   scene('christian', '친한 친구 크리스티안과 집 앞에서 이야기해요. 오늘은 이미 약속이 있어요.|Du redest mit deinem guten Freund Christian vor dem Haus. Heute hast du schon eine Verabredung.|You are talking to your close friend Christian outside your home. You already have plans today.', '오늘 같이 영화 볼래?|Wollen wir heute einen Film schauen?|Want to watch a film together today?'),
   scene('maya', '친한 친구 마야가 메시지를 보냈어요. 오늘은 약속이 있고 내일은 시간이 있어요. 다른 날을 제안해 보세요.|Deine gute Freundin Maya schreibt dir. Heute bist du verabredet, morgen hast du Zeit. Schlage einen anderen Tag vor.|Your close friend Maya has sent a message. You have plans today and are free tomorrow. Suggest another day.', '오늘 같이 영화 볼래?|Wollen wir heute einen Film schauen?|Want to watch a film together today?', 'offer'),
   i('offer', '거절하고 다른 날 제안하기|Absagen und einen anderen Tag vorschlagen|Decline and suggest another day', '내일 좋아.|Morgen passt.|Tomorrow works.', '그럼 내일 만나자.|Dann treffen wir uns morgen.|Then let’s meet tomorrow.',
     e('tomorrow', '오늘은 약속이 있어. 내일은 어때?|Heute bin ich schon verabredet. Wie wäre es morgen?|I have plans today. How about tomorrow?', '오늘의 초대는 거절하면서 만날 마음은 전해요.|Du sagst für heute ab und zeigst, dass du dich trotzdem treffen möchtest.|You decline today’s invitation while showing that you still want to meet.'),
     e('can', '오늘은 안 돼. 내일은 괜찮아.|Heute geht es nicht. Morgen passt es.|I can’t today. Tomorrow is fine.', '거절이 더 직접적이지만 곧바로 대안을 줘요. 편한 친구 사이에서 쓸 수 있어요.|Die Absage ist direkter, aber du bietest sofort eine Alternative an. Das passt unter vertrauten Freunden.|The refusal is more direct, but you immediately offer an alternative. It can work between close friends.')),
   i('decline', '오늘 어렵다고만 알리기|Nur für heute absagen|Just say you cannot today', '알겠어.|Alles klar.|Okay.', '다음에 같이 보자.|Schauen wir ihn ein anderes Mal zusammen.|Let’s watch it together another time.',
     e('sorry', '미안, 오늘은 약속이 있어.|Tut mir leid, heute bin ich schon verabredet.|Sorry, I have plans today.', '이유와 미안한 마음을 전해요. 다음 약속은 아직 정하지 않아요.|Du nennst den Grund und bedauerst die Absage. Ein neuer Termin ist noch offen.|You give a reason and express regret. You have not arranged another time.'),
     e('short', '오늘은 좀 어려워.|Heute wird es schwierig.|Today is a bit difficult.', '부담을 줄여 거절해요. 구체적인 이유는 말하지 않아요.|Du milderst die Absage ab, ohne einen konkreten Grund zu nennen.|You soften the refusal without giving a specific reason.'))),
 c('request_photo', 'a2', 'request', '사진 부탁하기|Um ein Foto bitten|Asking for a photo',
   scene('sujin', '수진과는 오늘 처음 만났어요. 공원에서 사진을 부탁하려고 해요. 서로 존댓말을 써요.|Du hast Sujin heute kennengelernt. Im Park möchtest du sie um ein Foto bitten. Ihr sprecht höflich miteinander.|You met Sujin today. In the park, you want to ask her to take a photo. You use polite Korean with each other.', '여기 경치가 좋네요.|Die Aussicht hier ist schön.|The view here is lovely.'),
   scene('lena', '레나와는 아직 친하지 않아요. 전시장에서 서로 존댓말로 이야기해요. 사진을 찍어 달라고 부탁해 보세요.|Du kennst Lena noch nicht gut. Ihr unterhaltet euch höflich in einer Ausstellung. Bitte sie, ein Foto von dir zu machen.|You do not know Lena well yet. You are speaking politely at an exhibition. Ask her to take your photo.', '여기서 사진 찍어도 돼요.|Hier darf man fotografieren.|You can take photos here.', 'ask'),
   i('ask', '사진 찍어 달라고 부탁하기|Um ein Foto bitten|Ask for a photo', '네, 찍어 드릴게요.|Ja, gerne.|Yes, of course.', '감사합니다. 여기 눌러 주세요.|Vielen Dank. Drücken Sie bitte hier.|Thank you. Please press here.',
     e('could', '사진 좀 찍어 주시겠어요?|Könnten Sie ein Foto von mir machen?|Could you take a photo of me?', '좀은 부탁의 부담을 줄이고, 주시겠어요는 상대를 높이며 의향을 물어요.|좀 schwächt die Bitte ab. 주시겠어요 spricht die andere Person respektvoll an und fragt nach ihrer Bereitschaft.|좀 softens the request. 주시겠어요 shows respect for the other person and asks whether they are willing.'),
     e('please', '사진 한 장 찍어 주세요.|Machen Sie bitte ein Foto von mir.|Please take one photo of me.', '공손한 부탁이지만 의향을 묻는 질문보다 직접적이에요. 사진 한 장으로 부탁의 범위를 정해요.|Die Bitte ist höflich, aber direkter als eine Frage nach der Bereitschaft. 한 장 begrenzt sie auf ein Foto.|It is polite, but more direct than asking whether the person is willing. 한 장 limits the request to one photo.')),
   i('permission', '함께 찍어도 되는지 묻기|Nach einem gemeinsamen Foto fragen|Ask to take a photo together', '네, 좋아요.|Ja, gerne.|Yes, sure.', '그럼 여기서 찍을까요?|Sollen wir es dann hier machen?|Shall we take it here, then?',
     e('together', '같이 사진 찍어도 될까요?|Darf ich ein Foto mit Ihnen machen?|Could I take a photo with you?', '사진을 찍어 달라는 부탁이 아니라 함께 찍는 데 동의를 구해요.|Du bittest um Zustimmung zu einem gemeinsamen Foto, nicht darum, dass die Person dich fotografiert.|You ask for permission to take a photo together, rather than asking the person to photograph you.'),
     e('suggest', '같이 사진 한 장 찍을까요?|Wollen wir ein Foto zusammen machen?|Shall we take a photo together?', '함께 하자는 제안이에요. 상대가 거절할 수 있도록 질문으로 말해요.|Du schlägst etwas Gemeinsames vor. Die Frage lässt der anderen Person Raum, abzulehnen.|You make a joint suggestion. The question gives the other person room to decline.')), phrases=['smalltalk_a1_0059']),
 c('apologize_late', 'a2', 'apologize', '늦었을 때|Wenn du zu spät kommst|Arriving late',
   scene('christian', '친한 친구 크리스티안이 카페에서 기다리고 있어요. 약속 시간보다 십 분 늦었어요.|Dein guter Freund Christian wartet im Café. Du bist zehn Minuten zu spät.|Your close friend Christian is waiting at a café. You are ten minutes late.', '왔어?|Da bist du ja.|You’re here.'),
   scene('maya', '친한 친구 마야와 도서관 앞에서 만나기로 했어요. 십 분 늦었고 먼저 사과하려고 해요.|Du triffst deine gute Freundin Maya vor der Bibliothek. Du bist zehn Minuten zu spät und möchtest dich zuerst entschuldigen.|You arranged to meet your close friend Maya outside the library. You are ten minutes late and want to apologize first.', '왔어?|Da bist du ja.|You’re here.', 'apologize'),
   i('apologize', '먼저 사과하기|Dich zuerst entschuldigen|Apologize first', '괜찮아.|Schon gut.|It’s okay.', '기다려 줘서 고마워.|Danke, dass du gewartet hast.|Thanks for waiting.',
     e('sorry', '늦어서 미안해.|Tut mir leid, dass ich zu spät bin.|Sorry I’m late.', '늦은 행동에 대해 바로 사과해요. 아직 이유를 말한 것은 아니에요.|Du entschuldigst dich direkt für die Verspätung, ohne schon einen Grund zu nennen.|You apologize directly for being late, without giving a reason yet.'),
     e('wait', '많이 기다렸지? 미안해.|Du hast lange gewartet, oder? Tut mir leid.|You’ve been waiting a while, haven’t you? I’m sorry.', '상대가 기다린 시간을 먼저 짚고 사과해요. 기다림이 길었을 것이라고 짐작하며 확인해요.|Du sprichst zuerst das Warten an und entschuldigst dich. Die Frage legt nahe, dass die Wartezeit lang war, und sucht Bestätigung.|You acknowledge the wait and apologize. The question suggests that it was a long wait and seeks confirmation.')),
   i('check', '얼마나 기다렸는지 묻기|Nach der Wartezeit fragen|Ask how long they waited', '십 분쯤 전에 왔어.|Vor etwa zehn Minuten.|About ten minutes ago.', '늦어서 미안해.|Tut mir leid, dass ich zu spät bin.|Sorry I’m late.',
     e('long', '오래 기다렸어?|Hast du lange gewartet?|Have you been waiting long?', '기다림을 확인해요. 이 질문만으로 사과가 끝난 것은 아니에요.|Du fragst nach dem Warten. Die Frage allein ist noch keine ausdrückliche Entschuldigung.|You check how long they waited. The question alone is not an explicit apology.'),
     e('when', '언제 왔어?|Wann bist du gekommen?|When did you get here?', '도착 시간을 묻는 질문이에요. 상대의 불편함을 인정하려면 사과를 이어 가세요.|Du fragst nach der Ankunftszeit. Wenn du das Warten anerkennen möchtest, entschuldige dich danach.|You ask about their arrival time. Follow it with an apology to acknowledge the inconvenience.'))),
 c('request_file', 'b1', 'request', '파일 확인 부탁하기|Prüfen, ob eine Datei sich öffnen lässt|Checking whether a file opens',
   scene('andrea', '안드레아와는 서로 존댓말을 쓰는 동료예요. 개인 업무 메시지에서 아까 공유한 파일이 열리는지 확인을 부탁해요.|Andrea ist dein Kollege; ihr verwendet höfliches Koreanisch. In einer direkten Arbeitsnachricht bittest du ihn zu prüfen, ob sich die vorhin geteilte Datei öffnen lässt.|Andrea is a colleague you use polite Korean with. In a direct work message, you want him to check whether the file you shared earlier opens.', '파일 받았어요.|Die Datei ist angekommen.|I received the file.'),
   scene('sujin', '수진과는 아직 친하지 않은 동료예요. 회의 뒤 둘이 존댓말로 이야기해요. 아까 공유한 파일이 열리는지 확인을 부탁하세요.|Sujin ist eine Kollegin, die du noch nicht gut kennst. Nach der Besprechung redet ihr zu zweit in höflichem Koreanisch. Bitte sie zu prüfen, ob sich die vorhin geteilte Datei öffnen lässt.|Sujin is a colleague you do not know well yet. You are talking politely after a meeting. Ask her to check whether the file you shared earlier opens.', '파일 받았어요.|Die Datei ist angekommen.|I received the file.', 'check'),
   i('check', '파일이 열리는지 확인 부탁하기|Prüfen lassen, ob die Datei sich öffnet|Ask them to check whether the file opens', '네, 열어 볼게요.|Ja, ich probiere es.|Yes, I’ll try opening it.', '안 열리면 말씀해 주세요.|Sagen Sie mir bitte Bescheid, falls es nicht klappt.|Please let me know if it does not open.',
     e('question', '아까 공유한 파일이 열리는지 확인해 주실 수 있어요?|Könnten Sie prüfen, ob sich die vorhin geteilte Datei öffnen lässt?|Could you check whether the file I shared earlier opens?', '확인할 일을 구체적으로 말하고 상대가 할 수 있는지 물어요. 내용 검토를 부탁하는 말은 아니에요.|Du benennst die Aufgabe und fragst, ob sie möglich ist. Eine inhaltliche Prüfung verlangst du damit nicht.|You specify the task and ask whether they can do it. You are not requesting a review of the contents.'),
     e('please', '아까 공유한 파일이 열리는지 한번 확인해 주세요.|Prüfen Sie bitte einmal, ob sich die vorhin geteilte Datei öffnen lässt.|Please check whether the file I shared earlier opens.', '공손하게 확인을 요청해요. 한번은 가볍게 살펴보자는 느낌을 줄 수 있지만 요청 자체를 없애지는 않아요.|Du bittest höflich um die Prüfung. 한번 kann die Aufgabe als kurzen Check rahmen, hebt die Bitte aber nicht auf.|You make a polite request. 한번 can frame it as a quick check, but it remains a request.')),
   i('wait', '지금은 확인하지 않아도 된다고 알리기|Den Check auf später verschieben|Say the check can wait', '그럼 오후에 볼게요.|Dann schaue ich am Nachmittag.|Then I’ll look this afternoon.', '네, 오후에 확인해 주세요.|Ja, prüfen Sie es bitte am Nachmittag.|Yes, please check it this afternoon.',
     e('later', '지금 확인하지 않으셔도 돼요.|Sie müssen es nicht jetzt prüfen.|You do not need to check it now.', '지금 해야 한다는 부담을 풀어요. 확인하지 말라는 금지는 아니에요.|Du nimmst den Zeitdruck. Es ist kein Verbot, die Datei jetzt zu prüfen.|You remove the pressure to do it now. You are not forbidding them from checking it.'),
     e('afternoon', '오후에 확인해 주셔도 괜찮아요.|Am Nachmittag reicht auch.|It is fine to check it this afternoon.', '오후에 확인해도 된다고 말해 지금의 시간 부담을 줄여요.|Du sagst, dass der Nachmittag auch passt, und reduzierst den unmittelbaren Zeitdruck.|You say that this afternoon also works, reducing the immediate pressure.'))),
 c('repair_time', 'b1', 'repair', '약속 시간 확인하기|Eine Uhrzeit klären|Clarifying a meeting time',
   scene('maya', '마야는 친한 친구예요. 메시지로 약속을 정했는데 서로 기억하는 시간이 달라요.|Maya ist eine gute Freundin. Ihr habt euch per Nachricht verabredet, erinnert euch aber an unterschiedliche Uhrzeiten.|Maya is a close friend. You made plans by message but remember different times.', '우리 여섯 시에 만나기로 했지?|Wir wollten uns um sechs treffen, oder?|We agreed to meet at six, right?'),
   scene('christian', '크리스티안은 친한 친구예요. 약속 장소에서 통화하며 시간을 확인해요. 다섯 시로 알고 있었지만 확신은 없어요. 먼저 함께 확인해 보세요.|Christian ist ein guter Freund. Ihr telefoniert am Treffpunkt. Du hattest fünf Uhr im Kopf, bist aber nicht sicher. Schlagt die Zeit gemeinsam nach.|Christian is a close friend. You are on the phone at the meeting place. You thought it was five but are not sure. Check the time together first.', '우리 여섯 시에 만나기로 했지?|Wir wollten uns um sechs treffen, oder?|We agreed to meet at six, right?', 'check'),
   i('check', '누가 맞는지 단정하지 않고 확인하기|Nachsehen, ohne festzulegen, wer recht hat|Check without assuming who is right', '좋아, 확인해 보자.|Ja, schauen wir nach.|Sure, let’s check.', '확인하고 다시 정하자.|Danach legen wir die Zeit noch mal fest.|Let’s check and agree on the time again.',
     e('messages', '우리 메시지 다시 확인해 볼까?|Schauen wir noch mal in unsere Nachrichten?|Shall we check our messages again?', '기억이 다른 상태를 인정하고 함께 확인하자고 제안해요.|Du lässt die unterschiedlichen Erinnerungen offen und schlägst vor, gemeinsam nachzusehen.|You leave the different recollections open and suggest checking together.'),
     e('unsure', '내가 헷갈리나 봐. 메시지 한번 볼까?|Vielleicht habe ich da etwas durcheinandergebracht. Schauen wir in die Nachrichten?|Maybe I’ve mixed something up. Shall we check the messages?', '내 기억에 혼동이 있을 가능성을 인정하고 함께 확인하자고 제안해요. 상대가 맞다고 확정하는 말은 아니에요.|Du räumst ein, dass du etwas verwechselt haben könntest, und schlägst vor, gemeinsam nachzusehen. Damit steht noch nicht fest, dass die andere Person recht hat.|You allow for a mix-up on your side and suggest checking together. You are not yet confirming that the other person is right.')),
   i('remember', '내가 기억한 시간 설명하기|Deine Erinnerung erklären|Explain the time you remembered', '나는 여섯 시로 기억하는데.|Ich habe sechs Uhr im Kopf.|I remember six.', '그럼 메시지 다시 확인해 보자.|Dann schauen wir noch mal in die Nachrichten.|Then let’s check the messages again.',
     e('thought', '나는 다섯 시인 줄 알았어.|Ich dachte, es wäre um fünf.|I thought it was five.', '내가 이해한 시간을 말해요. 상대가 잘못했다고 단정하지 않아요.|Du erklärst dein Verständnis, ohne zu behaupten, dass die andere Person falschliegt.|You explain your understanding without declaring the other person wrong.'),
     e('understood', '내가 다섯 시로 이해했나 봐.|Ich habe es wohl als fünf Uhr verstanden.|I seem to have understood it as five.', '내 이해에 문제가 있었을 가능성을 열어 둬요. 잘못 들었다고 확정하지는 않아요.|Du lässt offen, dass du es falsch verstanden haben könntest. Ein Hörfehler ist damit nicht bestätigt.|You allow for a possible misunderstanding on your side. You are not confirming that you misheard.'))),
 c('refuse_extra', 'b2', 'refuse', '추가 부탁에 선 긋기|Eine zusätzliche Aufgabe ablehnen|Declining an extra task',
   scene('andrea', '안드레아와는 서로 존댓말을 쓰는 동료예요. 회의에서 오늘 끝내야 할 일에 추가 부탁이 들어왔어요.|Andrea ist dein Kollege; ihr sprecht höfliches Koreanisch. In einer Besprechung kommt eine zusätzliche Bitte zu deinen heutigen Aufgaben hinzu.|Andrea is a colleague you use polite Korean with. During a meeting, an extra request is added to the work you need to finish today.', '이것도 오늘 맡아 주실 수 있어요?|Könnten Sie das heute auch übernehmen?|Could you take this on today as well?'),
   scene('sujin', '수진과는 서로 존댓말을 쓰는 동료예요. 개인 업무 메시지에서 같은 추가 부탁을 받았어요. 오늘은 추가 일을 맡기 어렵다고 분명히 말하세요.|Sujin ist deine Kollegin; ihr sprecht höfliches Koreanisch. Sie schickt dir die zusätzliche Bitte direkt. Sage klar, dass du sie heute nicht übernehmen kannst.|Sujin is a colleague you use polite Korean with. She sends you the same extra request in a direct work message. Clearly say you cannot take it on today.', '이것도 오늘 맡아 주실 수 있어요?|Könnten Sie das heute auch übernehmen?|Could you take this on today as well?', 'decline'),
   i('decline', '오늘은 맡기 어렵다고 말하기|Für heute klar ablehnen|Clearly decline for today', '알겠어요. 다른 방법을 찾아볼게요.|Verstanden. Ich suche eine andere Lösung.|Understood. I’ll look for another solution.', '이해해 주셔서 감사합니다.|Danke für Ihr Verständnis.|Thank you for understanding.',
     e('reason', '오늘은 이미 맡은 일이 있어서 추가로 맡기 어려워요.|Für heute habe ich schon Aufgaben übernommen und kann nichts Zusätzliches übernehmen.|I already have work assigned today, so I cannot take on anything extra.', '현재 맡은 일을 이유로 오늘의 추가 부탁을 거절해요. 다른 날까지 거절하는 말은 아니에요.|Du begründest die Absage mit deinen heutigen Aufgaben. Über einen anderen Tag sagst du damit noch nichts.|You decline today’s extra request because of your current work. You have not ruled out another day.'),
     e('clear', '죄송하지만 오늘은 추가로 맡을 수 없어요.|Es tut mir leid, aber heute kann ich nichts Zusätzliches übernehmen.|I’m sorry, but I cannot take on extra work today.', '죄송하지만으로 부담을 줄이면서 가능 여부는 분명히 말해요.|죄송하지만 mildert die Absage, während du deine Grenze klar benennst.|죄송하지만 softens the refusal while keeping your limit clear.')),
   i('scope', '범위를 알아본 뒤 판단하기|Erst den Umfang klären|Ask about the scope before deciding', '짧은 문서 두 개를 확인하는 일이에요.|Es geht darum, zwei kurze Dokumente zu prüfen.|It involves checking two short documents.', '일정을 확인하고 말씀드릴게요.|Ich prüfe meinen Zeitplan und gebe Ihnen Bescheid.|I’ll check my schedule and let you know.',
     e('amount', '어느 정도 분량인지 먼저 알 수 있을까요?|Könnten Sie mir zuerst sagen, wie umfangreich es ist?|Could you first tell me how much work it involves?', '가능하다고 약속하지 않고 판단에 필요한 정보를 요청해요.|Du fragst nach Informationen, bevor du eine Zusage machst.|You request the information you need without agreeing to do it.'),
     e('which', '어떤 작업인지 조금 더 설명해 주시겠어요?|Könnten Sie die Aufgabe etwas genauer erklären?|Could you explain the task a little more?', '무슨 일을 해야 하는지 확인해요. 거절도 수락도 아직 하지 않아요.|Du klärst die Aufgabe, ohne schon zu- oder abzusagen.|You clarify the task without accepting or declining yet.'))),
 c('apologize_tone', 'b2', 'apologize', '말투가 날카로웠을 때|Wenn der Ton zu scharf war|Apologizing for your tone',
   scene('sujin', '수진은 친한 친구예요. 개인 메시지에서 내 말이 날카롭게 들렸다고 알려 줬어요.|Sujin ist eine gute Freundin. In einer privaten Nachricht sagt sie dir, dass dein Ton scharf klang.|Sujin is a close friend. In a private message, she tells you that your tone sounded sharp.', '아까 말이 좀 날카롭게 들렸어.|Das klang vorhin etwas scharf.|What you said earlier sounded a bit sharp.'),
   scene('christian', '크리스티안은 친한 친구예요. 카페에서 직접 내 말투 이야기를 꺼냈어요. 내 말이 미친 영향을 인정하고 사과하세요.|Christian ist ein guter Freund. Im Café spricht er deinen Ton persönlich an. Erkenne die Wirkung deiner Worte an und entschuldige dich.|Christian is a close friend. He raises the subject of your tone in person at a café. Acknowledge the impact of your words and apologize.', '아까 말이 좀 날카롭게 들렸어.|Das klang vorhin etwas scharf.|What you said earlier sounded a bit sharp.', 'own'),
   i('own', '말의 영향을 인정하고 사과하기|Die Wirkung anerkennen und dich entschuldigen|Acknowledge the impact and apologize', '말해 줘서 고마워.|Danke, dass du das sagst.|Thanks for saying that.', '다음에는 좀 더 차분하게 말할게.|Beim nächsten Mal sage ich es ruhiger.|I’ll say it more calmly next time.',
     e('sorry', '내 말이 날카로웠네. 미안해.|Ich war da ziemlich scharf. Tut mir leid.|I was sharp with you. I’m sorry.', '상대의 피드백을 받아들이고 내 말투에 대해 사과해요.|Du nimmst die Rückmeldung an und entschuldigst dich für deinen Ton.|You accept the feedback and apologize for your tone.'),
     e('impact', '그렇게 들렸구나. 내가 말을 너무 세게 했어. 미안해.|So ist es bei dir angekommen. Ich habe mich zu scharf ausgedrückt. Tut mir leid.|I see that is how it sounded to you. I put it too strongly. I’m sorry.', '상대가 들은 효과를 인정한 뒤 내 표현에 책임을 둬요. 상대의 오해 탓으로 돌리지 않아요.|Du erkennst an, wie es ankam, und übernimmst Verantwortung für deine Formulierung.|You acknowledge how it came across and take responsibility for your wording.')),
   i('clarify', '어느 부분인지 먼저 알아보기|Nach der konkreten Stelle fragen|Ask which part sounded sharp', '내 말을 끊을 때 그랬어.|Als du mich unterbrochen hast.|When you interrupted me.', '말을 끊어서 미안해.|Tut mir leid, dass ich dich unterbrochen habe.|Sorry I interrupted you.',
     e('part', '어느 부분이 그렇게 들렸는지 말해 줄래?|Kannst du mir sagen, welche Stelle so klang?|Could you tell me which part sounded that way?', '구체적인 부분을 물어요. 따지는 억양이면 방어적으로 들릴 수 있으니 답을 듣고 사과를 이어 가세요.|Du fragst nach der konkreten Stelle. Ein herausfordernder Ton kann abwehrend wirken; höre zu und entschuldige dich anschließend.|You ask for the specific part. A challenging tone can sound defensive, so listen and follow up with an apology.'),
     e('tell', '내가 어떻게 말했는지 좀 더 얘기해 줄 수 있어?|Kannst du mir genauer sagen, wie ich geklungen habe?|Could you tell me more about how I sounded?', '설명을 부탁해요. 피드백을 부정하는 말은 아니지만 듣는 태도가 효과를 바꿀 수 있어요.|Du bittest um eine Erklärung. Der Satz weist die Rückmeldung nicht zurück, aber deine Haltung beim Zuhören beeinflusst die Wirkung.|You ask for more detail. The words do not reject the feedback, but how you listen affects the exchange.'))),
 c('invite_low_pressure', 'c1', 'invite', '부담 없이 모임 권하기|Ohne Druck zu einem Treffen einladen|An invitation without pressure',
   scene('lena', '레나는 서로 존댓말을 쓰는 지인이에요. 소규모 모임을 개인 메시지로 제안하려고 해요. 참석 여부는 아직 몰라요.|Lena ist eine Bekannte; ihr sprecht höfliches Koreanisch. Du möchtest sie privat zu einem kleinen Treffen einladen. Du weißt noch nicht, ob sie teilnehmen kann.|Lena is an acquaintance you use polite Korean with. You want to invite her to a small gathering by private message. You do not know whether she can attend.', '이번 주말 모임이 있나요?|Gibt es dieses Wochenende ein Treffen?|Is there a gathering this weekend?'),
   scene('hyuna', '현아와는 아직 친하지 않고 서로 존댓말을 써요. 대면으로 주말 모임을 소개해요. 참석을 압박하지 않고 초대하세요.|Du kennst Hyuna noch nicht gut; ihr sprecht höfliches Koreanisch. Im persönlichen Gespräch erzählst du von einem Treffen am Wochenende. Lade sie ein, ohne Druck zu machen.|You do not know Hyuna well yet and use polite Korean with her. In person, you mention a weekend gathering. Invite her without pressuring her to attend.', '이번 주말 모임이 있나요?|Gibt es dieses Wochenende ein Treffen?|Is there a gathering this weekend?', 'invite'),
   i('invite', '거절할 여지를 남기며 초대하기|Mit Raum für eine Absage einladen|Invite while leaving room to decline', '좋아요. 시간 확인해 볼게요.|Gerne. Ich schaue, ob ich Zeit habe.|Sounds good. I’ll check whether I’m free.', '편하실 때 알려 주세요.|Geben Sie mir Bescheid, wenn es für Sie passt.|Let me know when it is convenient for you.',
     e('if', '네, 시간 괜찮으시면 함께하셔도 좋을 것 같아요. 부담 갖지는 마시고요.|Ja. Wenn Sie Zeit haben, wäre es schön, wenn Sie dabei wären. Fühlen Sie sich aber nicht verpflichtet.|Yes. If you are free, it would be nice to have you join us. Please do not feel obliged.', '시간이라는 조건과 부담을 갖지 않아도 된다는 말로 선택권을 열어 둬요.|Die Bedingung und der Zusatz lassen die Entscheidung ausdrücklich bei der anderen Person.|The condition and the extra reassurance explicitly leave the choice to the other person.'),
     e('welcome', '네, 괜찮으시면 오세요. 일정이 안 맞으셔도 괜찮고요.|Ja, kommen Sie gerne, wenn es passt. Wenn Sie keine Zeit haben, ist das auch in Ordnung.|Yes, please come if it works for you. It is also fine if your schedule does not allow it.', '오세요로 초대가 분명해지고 불참해도 괜찮다고 직접 말해 압박을 줄여요.|오세요 macht die Einladung deutlich. Der zweite Satz nimmt den Druck, teilnehmen zu müssen.|오세요 makes the invitation clear. The second sentence explicitly reduces the pressure to attend.')),
   i('inform', '일정만 먼저 알리기|Zuerst nur informieren|Give the schedule first', '어디서 모이나요?|Wo findet das Treffen statt?|Where are you meeting?', '역 앞 카페에서 모일 예정이에요.|Wir wollen uns im Café vor dem Bahnhof treffen.|We plan to meet at the café outside the station.',
     e('time', '네, 토요일 오후에 짧게 모일 예정이에요.|Ja, wir wollen uns am Samstagnachmittag kurz treffen.|Yes, we plan to meet briefly on Saturday afternoon.', '모임 정보를 전해요. 이 문장만으로 참석을 요청하거나 확정하지 않아요.|Du informierst über das Treffen, ohne eine Teilnahme zu erbitten oder festzulegen.|You give information about the gathering without requesting or confirming attendance.'),
     e('plan', '네, 토요일 오후에 모이려고 해요.|Ja, wir haben vor, uns am Samstagnachmittag zu treffen.|Yes, we are planning to meet on Saturday afternoon.', '현재 계획을 말해요. 맥락에서 초대로 추론될 수 있지만 직접 초대한 것은 아니에요.|Du beschreibst den Plan. Eine Einladung kann im Kontext mitschwingen, ist aber nicht ausdrücklich formuliert.|You describe the plan. The context may suggest an invitation, but the words do not explicitly make one.'))),
 c('repair_implication', 'c2', 'repair', '의도와 전달 효과 구분하기|Absicht und Wirkung unterscheiden|Separating intention from impact',
   scene('andrea', '안드레아와는 서로 존댓말을 쓰는 동료예요. 개인 업무 메시지에서 문제를 함께 확인하자는 내 말이 책임을 묻는 뜻으로 전달됐어요.|Andrea ist dein Kollege; ihr sprecht höfliches Koreanisch. Deine direkte Arbeitsnachricht, das Problem gemeinsam zu prüfen, kam als Schuldzuweisung an.|Andrea is a colleague you use polite Korean with. Your direct work message about checking a problem together came across as assigning blame.', '제 책임이라는 말씀이신가요?|Meinen Sie, dass ich dafür verantwortlich bin?|Are you saying it is my responsibility?'),
   scene('sujin', '수진과는 아직 친하지 않은 동료예요. 회의 뒤 대면으로 같은 오해를 풀어요. 전달된 효과를 인정하면서 함께 확인하려던 의도를 설명하세요.|Sujin ist eine Kollegin, die du noch nicht gut kennst. Nach der Besprechung klärst du dasselbe Missverständnis persönlich. Erkenne die Wirkung an und erkläre, dass du das Problem gemeinsam prüfen wolltest.|Sujin is a colleague you do not know well yet. After a meeting, you clarify the same misunderstanding in person. Acknowledge how it came across and explain that you wanted to check the problem together.', '제 책임이라는 말씀이신가요?|Meinen Sie, dass ich dafür verantwortlich bin?|Are you saying it is my responsibility?', 'clarify'),
   i('clarify', '효과를 인정하고 의도 설명하기|Die Wirkung anerkennen und die Absicht erklären|Acknowledge the impact and explain your intention', '그런 뜻이었군요.|So war das gemeint.|I see what you meant.', '확인할 부분부터 같이 정해 볼까요?|Legen wir zuerst gemeinsam fest, was wir prüfen?|Shall we first agree on what to check together?',
     e('impact', '책임을 묻는 뜻으로 들리셨군요. 함께 확인하자는 취지였는데, 제가 분명하게 말씀드리지 못했어요.|Das kam bei Ihnen als Schuldzuweisung an. Ich wollte vorschlagen, gemeinsam nachzusehen, habe mich aber nicht klar ausgedrückt.|It came across as assigning blame. I meant to suggest checking together, but I did not make that clear.', '전달된 뜻을 인정하고 내 설명의 부족함을 짚어요. 상대가 오해했다고만 말하지 않아요.|Du erkennst die Wirkung an und benennst deine unklare Formulierung, statt das Missverständnis allein der anderen Person zuzuschreiben.|You acknowledge the impact and your unclear wording, rather than placing the misunderstanding entirely on the other person.'),
     e('wording', '제 표현이 책임을 돌리는 말처럼 들렸을 수 있겠네요. 그보다는 문제를 같이 살펴보자는 뜻이었어요.|Meine Formulierung konnte wohl wie eine Schuldzuweisung klingen. Ich wollte eher vorschlagen, das Problem gemeinsam anzusehen.|My wording may have sounded like I was shifting the blame. I meant instead that we should look at the problem together.', '전달 효과를 가능성으로 인정해요. 직접적인 사과보다 설명 중심이어서 상대의 반응을 더 살펴야 해요.|Du erkennst die mögliche Wirkung an. Die Antwort erklärt mehr, als dass sie sich entschuldigt; achte deshalb auf die Reaktion.|You acknowledge the possible impact. This answer focuses more on explanation than apology, so pay attention to the response.')),
   i('scope', '책임 판단은 아직 하지 않았다고 밝히기|Die Verantwortungsfrage offenlassen|Say responsibility has not been decided', '어떤 부분을 확인하면 될까요?|Was sollen wir prüfen?|What should we check?', '우선 일어난 일을 함께 정리해 볼까요?|Tragen wir zuerst gemeinsam zusammen, was passiert ist?|Shall we first go through what happened together?',
     e('notyet', '아직 누구의 책임인지 판단한 것은 아니에요. 먼저 사실관계를 확인하려고 해요.|Ich habe noch nicht beurteilt, wer verantwortlich ist. Zuerst möchte ich klären, was passiert ist.|I have not decided who is responsible yet. First, I want to establish what happened.', '판단 전이라는 상태와 확인 순서를 분명히 해요. 상대에게 책임이 없다고 확정하는 말은 아니에요.|Du benennst den offenen Stand und die Reihenfolge. Damit sprichst du die andere Person noch nicht von jeder Verantwortung frei.|You clarify the current uncertainty and the order of steps. You are not declaring the other person free of responsibility.'),
     e('order', '책임을 정하기에 앞서, 어떤 일이 있었는지부터 확인했으면 해요.|Bevor wir die Verantwortung zuordnen, würde ich gern klären, was passiert ist.|Before assigning responsibility, I would like to establish what happened.', '판단보다 확인을 먼저 하자는 순서의 제안이에요. 책임 문제 자체를 없애는 말은 아니에요.|Du schlägst vor, zuerst die Fakten zu klären. Die Verantwortungsfrage wird dadurch nicht aufgehoben.|You propose checking the facts first. You are not removing the question of responsibility.'))),
]

def build():
    target = Path(__file__).resolve().parents[1] / 'assets/data/smalltalk_context_cases.json'
    target.write_text(json.dumps(dict(version=1, reviewStatus='Author model review; human language review not claimed', cases=cases), ensure_ascii=False, indent=2)+'\n', encoding='utf-8')

if __name__ == '__main__':
    build()
