#!/usr/bin/env python3
"""Validate the precomposited Hanji matte used by the home hero videos.

The regular character clips must keep a white matte for runtime multiply.
HomeHeroClips instead avoids the unreliable Android texture color-filter path,
so its two derivatives have #FAF6EC baked into every frame.

Usage:
    python tool/check_home_hero_matte.py
    python tool/check_home_hero_matte.py --check
"""

from __future__ import annotations

import json
import hashlib
import subprocess
import sys
from collections import Counter
from pathlib import Path

from check_clip_matte import GRID, corners, die, find_ffmpeg

ROOT = Path(__file__).resolve().parent.parent
CLIP_DIR = ROOT / "assets" / "video" / "home_hero"
REPORT = Path(__file__).resolve().parent / "home_hero_matte_report.json"
TARGET = (250, 246, 236)  # SoriColors.lightBg / #FAF6EC
TOLERANCE = 2
# A moving wing can touch one sampled corner in a single frame. As with the
# white-matte checker, use a strong majority instead of misclassifying subject
# pixels as background drift.
MIN_MATCH_RATIO = 0.99
EXPECTED_FRAMES = {
    "tiger_rise_hanji.mp4": 121,
    "magpie_walking_front_hanji.mp4": 113,
}


def check(path: Path, ffmpeg: str) -> dict:
    base = {
        "path": path.name,
        "bytes": path.stat().st_size,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest().upper(),
    }
    try:
        proc = subprocess.run(
            [
                ffmpeg,
                "-v",
                "error",
                "-i",
                str(path),
                "-vf",
                f"scale={GRID}:{GRID}",
                "-f",
                "rawvideo",
                "-pix_fmt",
                "rgb24",
                "-",
            ],
            capture_output=True,
            timeout=120,
        )
    except subprocess.TimeoutExpired:
        return {
            **base,
            "ok": False,
            "matte": None,
            "match_ratio": 0.0,
            "frames_sampled": 0,
            "reason": "decode timeout",
        }

    frame_size = GRID * GRID * 3
    frame_count = len(proc.stdout) // frame_size
    if frame_count == 0:
        error = proc.stderr.decode("utf-8", "replace").strip().split("\n")[-1]
        return {
            **base,
            "ok": False,
            "matte": None,
            "match_ratio": 0.0,
            "frames_sampled": 0,
            "reason": f"could not decode frames: {error[:120]}",
        }

    samples = []
    for index in range(frame_count):
        start = index * frame_size
        samples.extend(corners(proc.stdout[start : start + frame_size]))

    matching = [
        color
        for color in samples
        if all(abs(value - target) <= TOLERANCE for value, target in zip(color, TARGET))
    ]
    ratio = len(matching) / len(samples)
    matte = Counter(samples).most_common(1)[0][0]
    expected_frames = EXPECTED_FRAMES.get(path.name)
    frames_ok = expected_frames == frame_count
    ok = ratio >= MIN_MATCH_RATIO and frames_ok
    reasons = []
    if ratio < MIN_MATCH_RATIO:
        reasons.append("corner matte differs from #FAF6EC")
    if not frames_ok:
        reasons.append(f"expected {expected_frames} frames, found {frame_count}")

    return {
        **base,
        "ok": ok,
        "matte": "#%02X%02X%02X" % matte,
        "match_ratio": round(ratio, 3),
        "frames_sampled": frame_count,
        "reason": "; ".join(reasons),
    }


def main() -> int:
    check_only = "--check" in sys.argv
    ffmpeg = find_ffmpeg()
    if not CLIP_DIR.is_dir():
        die(f"{CLIP_DIR} does not exist")

    clips = sorted(CLIP_DIR.glob("*.mp4"))
    if {clip.name for clip in clips} != set(EXPECTED_FRAMES):
        die("home hero directory must contain exactly the two declared clips")

    print(f"  ffmpeg: {ffmpeg}\n")
    results = [check(path, ffmpeg) for path in clips]
    for result in results:
        mark = "OK" if result["ok"] else f"FAIL {result['reason']}"
        print(
            f"  {result['path']}: {result['matte']} "
            f"{result['match_ratio'] * 100:.0f}% "
            f"{result['frames_sampled']} frames  {mark}"
        )

    bad = [result for result in results if not result["ok"]]
    if not check_only:
        REPORT.write_text(
            json.dumps(
                {
                    "note": "Generated by tool/check_home_hero_matte.py; do not edit manually.",
                    "target": "#FAF6EC",
                    "tolerance": TOLERANCE,
                    "clips": results,
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        print(f"\n  report updated: {REPORT.relative_to(ROOT)}")

    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
