"""Tests for the Bible v2 draft deliverables (docs/data/level_bible/V2_*.csv).

These CSVs are hand-authored (not generated by build_level_bible_tables.py --
the brief explicitly says not to extend that generator for v2), but every
Sejong-textbook fact they carry must still be a real, already-verified
citation from docs/data/sejong/citations*.jsonl -- this test is the
anti-hallucination gate for v2, mirroring what
tool/verify_sejong_citations.py does for the Q-S/Q-S2 audit docs.

Two things are checked:
  1. CSV schema -- both V2_*.csv files have the exact expected header row
     and every data row has that many fields (catches truncated/misaligned
     rows early, before Jin reads them).
  2. Citation grounding -- every row in V2_grammar_gaps.csv that names a
     sejong_page also names a sejong_file, and that exact (file, page) pair
     appears at least once in citations*.jsonl (i.e. some fact on that page
     was already independently verified against the real PDF/OCR text by
     tool/verify_sejong_citations.py). This does not re-run the fuzzy/exact
     text match itself (that is verify_sejong_citations.py's job and it is
     re-run separately) -- it only checks that no NEW, unverified (file,
     page) pair was invented for v2.
"""
from __future__ import annotations

import csv
import glob
import json
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LEVEL_BIBLE_DIR = REPO / "docs" / "data" / "level_bible"
SEJONG_DIR = REPO / "docs" / "data" / "sejong"

GRAMMAR_GAPS_CSV = LEVEL_BIBLE_DIR / "V2_grammar_gaps.csv"
RELEVEL_CSV = LEVEL_BIBLE_DIR / "V2_relevel_candidates.csv"

GRAMMAR_GAPS_HEADER = [
    "nikl_grade", "category", "form", "variants", "status", "app_matched_ids",
    "app_levels", "sejong_evidence", "sejong_page", "sejong_file",
]

RELEVEL_HEADER = [
    "id", "headword", "current_level", "nikl_grade", "nikl_cefr", "delta",
    "confidence", "category", "proposed_level", "example_korean", "reason",
]

# Citation ids referenced by name in V2_jin_decisions.md / the v2 bible draft
# for the honorific-vocab exception proposal (B.4③) -- must exist verbatim.
EXPECTED_CITATION_IDS = {
    "sejong1_u9_voc8_계시다",
    "sejong1_u9_voc9_드리다",
    "sejong1_u9_voc10_말씀",
    "sejong1_u9_voc11_말씀하시다",
    "sejong5_세종_u1_gram0_...이라든가",
    "sejong5_세종_u2_gram0_-을뿐더러",
    "sejong5_세종_u7_gram0_-는 데다가",
    "sejong5_세종_u8_gram0_-다가는",
    "sejong5_세종_u9_gram0_-는 가운데",
    "sejong5_세종_u10_gram0_-으면 몰라도",
    "sejong6_세종_u4_gram0_-는 만큼",
}


def _load_csv_rows(path: Path) -> list[dict]:
    with path.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def _load_all_citations() -> list[dict]:
    out = []
    for path in sorted(SEJONG_DIR.glob("citations*.jsonl")):
        with path.open(encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    out.append(json.loads(line))
    return out


class GrammarGapsCsvSchemaTest(unittest.TestCase):
    def setUp(self):
        self.assertTrue(GRAMMAR_GAPS_CSV.is_file(), f"missing {GRAMMAR_GAPS_CSV}")
        with GRAMMAR_GAPS_CSV.open(encoding="utf-8-sig", newline="") as f:
            reader = csv.reader(f)
            self.header = next(reader)
            self.data_rows = list(reader)

    def test_header_matches_expected_schema(self):
        self.assertEqual(self.header, GRAMMAR_GAPS_HEADER)

    def test_every_row_has_expected_column_count(self):
        n = len(GRAMMAR_GAPS_HEADER)
        for i, row in enumerate(self.data_rows, start=2):
            self.assertEqual(len(row), n, f"row {i} has {len(row)} fields, expected {n}: {row}")

    def test_nonempty(self):
        self.assertGreater(len(self.data_rows), 0)


class RelevelCandidatesCsvSchemaTest(unittest.TestCase):
    def setUp(self):
        self.assertTrue(RELEVEL_CSV.is_file(), f"missing {RELEVEL_CSV}")
        with RELEVEL_CSV.open(encoding="utf-8-sig", newline="") as f:
            reader = csv.reader(f)
            self.header = next(reader)
            self.data_rows = list(reader)

    def test_header_matches_expected_schema(self):
        self.assertEqual(self.header, RELEVEL_HEADER)

    def test_every_row_has_expected_column_count(self):
        n = len(RELEVEL_HEADER)
        for i, row in enumerate(self.data_rows, start=2):
            self.assertEqual(len(row), n, f"row {i} has {len(row)} fields, expected {n}: {row}")

    def test_every_id_starts_with_vocab_(self):
        for row in _load_csv_rows(RELEVEL_CSV):
            self.assertTrue(row["id"].startswith("vocab_"), row["id"])

    def test_category_is_one_of_known_values(self):
        known = {
            "too_easy_move_down", "too_hard_or_survival_review",
            "f9_ruling_exists_not_applied", "sejong_a1_survival_new",
        }
        for row in _load_csv_rows(RELEVEL_CSV):
            self.assertIn(row["category"], known, row)


class SejongCitationGroundingTest(unittest.TestCase):
    """Every (file, page) named as sejong evidence in V2_grammar_gaps.csv must
    already be a page some OTHER citation in citations*.jsonl has verified
    (i.e. not a page/file pair invented for this PR)."""

    @classmethod
    def setUpClass(cls):
        cls.citations = _load_all_citations()
        cls.verified_file_pages = {(c["file"], c["page"]) for c in cls.citations if c.get("file") and isinstance(c.get("page"), int)}
        cls.citation_ids = {c["id"] for c in cls.citations if c.get("id")}

    def test_every_cited_sejong_page_was_independently_verified(self):
        rows = _load_csv_rows(GRAMMAR_GAPS_CSV)
        checked = 0
        for row in rows:
            page = row.get("sejong_page", "").strip()
            fname = row.get("sejong_file", "").strip()
            if not page:
                continue
            self.assertTrue(fname, f"row has sejong_page {page!r} but no sejong_file: {row}")
            key = (fname, int(page))
            self.assertIn(
                key, self.verified_file_pages,
                f"({fname!r}, {page}) is not backed by any entry in citations*.jsonl -- "
                "per protocol, do not cite a Sejong page that verify_sejong_citations.py "
                "has not already checked",
            )
            checked += 1
        # Sanity: this test should actually exercise something (regression guard
        # against silently dropping all sejong_evidence columns to empty).
        self.assertGreaterEqual(checked, 80, f"expected >=80 cited rows, found {checked}")

    def test_expected_citation_ids_exist(self):
        missing = EXPECTED_CITATION_IDS - self.citation_ids
        self.assertEqual(missing, set(), f"citation ids referenced by the v2 bible/Jin-decisions docs are missing from citations*.jsonl: {missing}")


if __name__ == "__main__":
    unittest.main()
