'use strict';
const params = new URLSearchParams(location.search);
const catalogState = {mode:['learn','packs','games'].includes(params.get('section'))?params.get('section'):'packs',locale:['de','en','ko'].includes(params.get('lang'))?params.get('lang'):'de',level:'A1',section:'all',search:'',completed:params.get('complete')==='1'};
const labels = {
 de:{learn:'Lernen',packs:'Wortpakete',games:'Spiele',learnIntro:'Was möchtest du heute üben?',packsIntro:'Wörter für echte Situationen. Wähle ein Thema.',gamesIntro:'Eine kurze Runde. Ein klarer Fokus.',nav:['Heute','Lernen','Spiele','Hanok','Gye'],search:'Thema oder Wort suchen',all:'Alle',words:'Wörter',listen:'Hören & Sprechen',hangul:'Hangul',review:'Wiederholen',activities:'Dein Übungsangebot',topics:'Themen',count:'Wörter',minutes:'Min.',continue:'Schritt für Schritt',challenge:'Heute spielerisch üben',browse:'Entdecken',done:'Abgeschlossen',close:'Schließen',compare:'Original · Ausschnitt · 100 px',back:'Zurück zu den Wörtern',source:'Bestehende Lerninhalte',vocabNote:'Diese Wörter und Übersetzungen stammen aus dem aktuellen Wortpaket. Diese Vorschau verändert deinen Lernfortschritt nicht.',noResults:'Kein passendes Thema gefunden. Versuche ein anderes Wort oder Niveau.',packList:'Wortpakete öffnen',openListen:'Hören ausprobieren',inventory:'252 Pakete · 184 eigene Illustrationen',artNote:'Die bestehende Illustration bleibt vollständig sichtbar. Tippe auf eine Karte, um Wörter und Bildausschnitt zu vergleichen.',reviewNote:'Designvorschau · keine Kontodaten',language:'Sprache',resultCount:'Ergebnisse',details:'Vorschau',activityNote:'Die Illustration, der Inhalt und die Dauer gehören zum bestehenden Angebot. Die Lern- und Spielfunktionen sind in dieser Designvorschau nicht verbunden.'},
 en:{learn:'Learn',packs:'Vocabulary packs',games:'Games',learnIntro:'What would you like to practise today?',packsIntro:'Words for real situations. Pick a topic.',gamesIntro:'A quick round with a clear focus.',nav:['Today','Learn','Games','Hanok','Gye'],search:'Search for a topic or word',all:'All',words:'Words',listen:'Listen & speak',hangul:'Hangul',review:'Review',activities:'Ways to practise',topics:'Topics',count:'words',minutes:'min',continue:'Step by step',challenge:'A little practice, a little play',browse:'Explore',done:'Completed',close:'Close',compare:'Original · crop · 100 px',back:'Back to the words',source:'Existing learning content',vocabNote:'These words and translations come from the current vocabulary pack. This preview does not change your learning progress.',noResults:'No matching topics. Try another word or level.',packList:'Browse vocabulary packs',openListen:'Try listening',inventory:'252 packs · 184 dedicated illustrations',artNote:'The existing illustration stays fully visible. Tap a card to compare its words and image crop.',reviewNote:'Design preview · no account data',language:'Language',resultCount:'results',details:'Preview',activityNote:'The illustration, content and duration come from the current app. The learning and game features are not connected in this design preview.'},
 ko:{learn:'학습',packs:'단어 팩',games:'게임',learnIntro:'오늘은 무엇을 연습할까요?',packsIntro:'실제 상황에서 쓰는 말. 배우고 싶은 주제를 골라요.',gamesIntro:'한 가지에 집중하는 짧은 한 판.',nav:['오늘','학습','게임','한옥','계'],search:'주제나 단어 검색',all:'전체',words:'단어',listen:'듣기·말하기',hangul:'한글',review:'복습',activities:'학습 방법 고르기',topics:'학습 주제',count:'개 단어',minutes:'분',continue:'차근차근 배우기',challenge:'오늘의 가벼운 도전',browse:'살펴보기',done:'완료',close:'닫기',compare:'원본 · 표시 영역 · 100px',back:'단어로 돌아가기',source:'현재 앱의 학습 내용',vocabNote:'현재 단어 팩의 한국어·번역을 그대로 보여줍니다. 이 시안은 실제 학습 진도를 변경하지 않습니다.',noResults:'일치하는 주제가 없어요. 다른 단어나 레벨로 찾아보세요.',packList:'전체 단어 팩 보기',openListen:'듣기 시안 체험',inventory:'252개 팩 · 전용 일러스트 184종',artNote:'현재 일러스트의 전체 구도를 살렸어요. 카드를 누르면 단어와 그림의 표시 영역을 비교할 수 있어요.',reviewNote:'디자인 시안 · 계정 데이터 없음',language:'언어',resultCount:'개 결과',details:'시안 보기',activityNote:'그림·학습 내용·소요 시간은 현재 앱 기준입니다. 이 디자인 시안에는 실제 학습·게임 기능을 연결하지 않았습니다.'}
};
const koreanActivities = {
 course:['학습 경로','실제 상황을 따라 배우는 학습 경로.'],hangul:['한글','음절을 조합하고 자신 있게 읽어요.'],calligraphy:['오늘의 글자','하루에 한 글자씩 알아가요.'],pronunciation:['발음','듣고 따라 말해요. 평가는 추후 제공할 예정이에요.'],vocab_packs:['단어 팩','생활 속 주제로 단어를 배워요.'],srs:['복습','배운 단어를 필요한 때 다시 익혀요.'],my_words:['내 단어','검색·책장·어려운 단어를 한곳에서.'],grammar:['문법','실제 예문에서 표현의 규칙을 알아봐요.'],book_capture:['책 촬영','사진 속 문장에서 단어를 찾아요.'],listening:['듣기','한국어를 듣고 내용을 이해해요.'],scenarios:['생활 장면','실제 상황에서 쓸 표현을 연습해요.'],smalltalk:['스몰 토크','짧고 자연스러운 대화를 이어가요.'],word_web:['뉘앙스·반대말','표현 사이의 차이와 관계를 알아봐요.'],daily_game:['오늘의 도전','오늘의 짧은 학습 게임.'],chosung:['초성 퀴즈','첫소리를 보고 단어를 떠올려요.'],syllable_cross:['음절 퍼즐','음절을 조합해 낱말을 만들어요.'],cloze:['빈칸 채우기','문맥에 맞는 말을 골라요.'],speed_match:['빠른 짝 맞추기','단어와 의미를 빠르게 연결해요.'],sentence_arcade:['문장 아케이드','말의 순서를 맞춰 문장을 만들어요.'],kkeunmari:['끝말잇기','앞말의 끝에서 다음 단어를 이어요.'],custom_practice:['내 단어로 연습','저장한 단어로 퀴즈·짝 맞추기·타자 연습.']
};
const catalogScreen=document.querySelector('#catalog-screen'),detail=document.querySelector('#catalog-detail');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ct=key=>labels[catalogState.locale][key];
const cArrow=()=>'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>';
const detailCTA=label=>`<span class="cta-emblem" aria-hidden="true">${cArrow()}</span><span class="cta-label">${label}</span><span class="cta-direction" aria-hidden="true">${cArrow()}</span>`;
const resultLabel=n=>catalogState.locale==='de'?(n===1?'Ergebnis':'Ergebnisse'):catalogState.locale==='en'?(n===1?'result':'results'):'개';
const title=a=>a.title[catalogState.locale]??koreanActivities[a.id]?.[0]??a.id;
const description=a=>a.description?.[catalogState.locale]??koreanActivities[a.id]?.[1]??'';
let inventory,focusedItem;
let catalogRenderEpoch=0;
async function markCatalogArtReady(){
 const epoch=++catalogRenderEpoch;
 document.documentElement.removeAttribute('data-art-ready');
 const firstImages=[...catalogScreen.querySelectorAll('img')].slice(0,5);
 firstImages.forEach(i=>i.loading='eager');
 await Promise.all(firstImages.map(i=>i.decode().catch(()=>{})));
 if(document.fonts?.ready)await document.fonts.ready;
 await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
 if(epoch!==catalogRenderEpoch)return;
 document.documentElement.dataset.artReady='true';
 if(params.get('embed')==='1')window.parent.postMessage({soriReviewArtReady:true},location.origin);
}
if(params.get('embed')==='1')document.body.classList.add('catalog-embedded');
if(params.get('clean')==='1')document.body.classList.add('catalog-clean');
if(params.get('motion')==='reduce')document.body.classList.add('reduced');
if(params.get('text')==='large')document.body.classList.add('large-text');
document.querySelector('#catalog-reduce').checked=document.body.classList.contains('reduced');
document.querySelector('#catalog-complete').checked=catalogState.completed;
const navPaths=['<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3Z"/>','<path d="M12 6v15M3 3h5a4 4 0 0 1 4 3 4 4 0 0 1 4-3h5v16h-5a4 4 0 0 0-4 2 4 4 0 0 0-4-2H3Z"/>','<path d="M7 6h10c2 0 3 2 4 6l1 6c0 3-2 3-4 1l-2-2H8l-2 2c-2 2-4 2-4-1l1-6c1-4 2-6 4-6ZM5 11h5m-2.5-2.5v5m9-3h.01m2 3h.01"/>','<path d="M2 9c4 0 7-2 10-6 3 4 6 6 10 6M4 10h16M5 10v10m14-10v10M3 21h18M9 13h6v8M12 13v8"/>','<circle cx="12" cy="7" r="4"/><path d="M4 21v-3a8 8 0 0 1 16 0v3"/>'];
function langSelect(){return `<select id="phone-locale" aria-label="${ct('language')}">${['de','en','ko'].map(l=>`<option value="${l}" ${l===catalogState.locale?'selected':''}>${{de:'DE',en:'EN',ko:'한국어'}[l]}</option>`).join('')}</select>`;}
function image(a){return `<div class="print-art"><img src="${a.asset}" alt="" loading="lazy" decoding="async"></div>`;}
function feature(a){return `<button class="catalog-feature ${a.tab==='games'?'gold':''}" data-item="${a.id}"><div><span>${ct(a.tab==='games'?'challenge':'continue')}</span><h3>${esc(title(a))}</h3><small>${a.minutes} ${ct('minutes')} · ${ct('details')}</small></div><img src="${a.asset}" alt="" decoding="async"><span class="feature-arrow" aria-hidden="true">${cArrow()}</span></button>`;}
function packCard(a){const done=catalogState.completed&&a.id==='a1_greetings_2';return `<button class="art-card" data-item="${a.id}" aria-label="${esc(title(a))}">${image(a)}<div class="art-caption"><strong>${esc(title(a))}</strong><small lang="ko">${esc(a.samples.slice(0,2).map(s=>s.ko).join(' · '))}</small><div class="card-foot"><span class="${done?'done':''}">${done?'✓ '+ct('done'):a.count+' '+ct('count')}</span><span class="go" aria-hidden="true">${cArrow()}</span></div></div></button>`;}
function activityCard(a){return `<button class="art-card" data-item="${a.id}" aria-label="${esc(title(a))}">${image(a)}<div class="art-caption"><strong>${esc(title(a))}</strong><div class="card-foot"><span>${a.minutes} ${ct('minutes')}</span><span class="go" aria-hidden="true">${cArrow()}</span></div></div></button>`;}
function filteredPacks(){const term=catalogState.search.trim().toLocaleLowerCase();return inventory.packs.filter(a=>a.level===catalogState.level&&(!term||[a.id,...Object.values(a.title),...a.samples.flatMap(s=>[s.ko,s.de,s.en])].join(' ').toLocaleLowerCase().includes(term)));}
function renderPackGrid(){const found=filteredPacks();document.querySelector('#catalog-grid').innerHTML=found.length?found.map(packCard).join(''):`<p class="catalog-empty">${ct('noResults')}</p>`;document.querySelector('#catalog-count').textContent=found.length+' '+resultLabel(found.length);markCatalogArtReady();}
function renderCatalog(focus=false){
 if(!inventory)return;
 document.documentElement.lang=catalogState.locale;
 document.querySelector('#catalog-locale').value=catalogState.locale;
 document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===catalogState.mode)));
 const mode=catalogState.mode,packMode=mode==='packs';
 const head=`<div class="catalog-head"><div><span class="catalog-kicker">한글소리</span><h2 class="catalog-title" tabindex="-1">${ct(mode)}</h2></div>${langSelect()}</div><p class="catalog-intro">${ct(mode+'Intro')}</p>`;
 let body;
 if(packMode){body=`<input type="search" id="pack-search" class="catalog-search" placeholder="${ct('search')}" aria-label="${ct('search')}" value="${esc(catalogState.search)}"><div class="catalog-filters" aria-label="CEFR">${Object.entries(inventory.stats.levels).map(([l,n])=>`<button data-level="${l}" aria-pressed="${catalogState.level===l}">${l}<small>${n} ${ct('topics')}</small></button>`).join('')}</div><div class="catalog-summary"><h3>${catalogState.level} · ${ct('topics')}</h3><span id="catalog-count" aria-live="polite"></span></div><div id="catalog-grid" class="catalog-grid"></div><p class="catalog-evidence">${ct('inventory')}<br>${ct('artNote')}</p>`;}
 else{const all=inventory.activities.filter(a=>a.tab===mode);const featured=all.find(a=>a.id===(mode==='learn'?'course':'daily_game'));const others=all.filter(a=>a!==featured&&(mode==='games'||catalogState.section==='all'||a.section===catalogState.section));body=feature(featured)+(mode==='learn'?`<div class="catalog-filters catalog-sections" aria-label="${ct('activities')}">${['all','words','listen','hangul','review'].map(s=>`<button data-section="${s}" aria-pressed="${catalogState.section===s}">${ct(s)}</button>`).join('')}</div>`:'')+`<div class="catalog-summary"><h3>${ct('activities')}</h3><span>${others.length} ${resultLabel(others.length)}</span></div><div class="catalog-grid catalog-activity-grid">${others.map(activityCard).join('')}</div><p class="catalog-evidence">${ct('reviewNote')}</p>`;}
 catalogScreen.innerHTML=`<div class="catalog-page">${head}${body}</div>`;
 if(packMode)renderPackGrid();
 else markCatalogArtReady();
 document.querySelector('#catalog-nav').innerHTML=ct('nav').map((label,i)=>`<button class="nav-button" data-nav="${i}" ${i===(mode==='games'?2:1)?'aria-current="page"':''}><svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${navPaths[i]}</svg><span>${label}</span></button>`).join('');
 document.querySelector('#catalog-nav').setAttribute('aria-label',catalogState.locale==='de'?'Hauptnavigation':catalogState.locale==='en'?'Main navigation':'주 메뉴');
 if(focus)document.querySelector('.catalog-title').focus({preventScroll:true});
 const url=new URL(location.href);url.searchParams.set('section',mode);url.searchParams.set('lang',catalogState.locale);history.replaceState(null,'',url);
}
function setMode(mode){catalogState.mode=mode;catalogState.search='';catalogState.section='all';renderCatalog(true);catalogScreen.scrollTop=0;}
function detailHead(a){return `<div class="detail-head"><div><span class="eyebrow">${a.level??ct('details')}</span><h2>${esc(title(a))}</h2></div><button data-close aria-label="${ct('close')}">×</button></div>`;}
function showItem(id){const a=inventory.packs.find(p=>p.id===id)??inventory.activities.find(p=>p.id===id);if(!a)return;focusedItem=a;if(params.get('embed')==='1'&&inventory.activities.some(item=>item.id===a.id))window.parent.postMessage({soriActivityOpened:a.id},location.origin);
 let html=detailHead(a)+`<img class="detail-art" src="${a.asset}" alt="${esc(a.subject??title(a))}">`;
 if(a.level)html+=`<p class="detail-note">${ct('vocabNote')}</p><ul class="word-preview">${a.samples.map(s=>`<li><strong lang="ko">${esc(s.ko)}</strong>${catalogState.locale==='ko'?'':`<span>${esc(s[catalogState.locale])}</span>`}</li>`).join('')}</ul><div class="detail-actions"><button data-compare>${ct('compare')}</button></div>`;
 else{html+=`<p>${esc(description(a))}</p><p class="detail-note">${ct('activityNote')}</p><div class="detail-actions">${a.id==='vocab_packs'?`<button class="primary tactile-cta" data-open-packs>${detailCTA(ct('packList'))}</button>`:a.id==='listening'?`<a class="primary tactile-cta" data-prototype-route="listen" href="index.html?view=listen&lang=${catalogState.locale}">${detailCTA(ct('openListen'))}</a>`:''}<button data-compare>${ct('compare')}</button></div>`;}
 document.querySelector('#detail-body').innerHTML=html;
 detail.showModal();detail.scrollTop=0;
}
function showComparison(){const a=focusedItem;document.querySelector('#detail-body').innerHTML=detailHead(a)+`<div class="ratio-grid"><figure><figcaption>4:3 · ${catalogState.locale==='ko'?'전체 원본':catalogState.locale==='de'?'Vollständiges Original':'Full original'}</figcaption><div class="ratio-frame"><img src="${a.asset}" alt="${esc(a.subject??title(a))}"></div></figure><figure><figcaption>16:10 · ${catalogState.locale==='ko'?(a.level?'현재 PackCard 중앙 표시':'중앙 표시 비교'):catalogState.locale==='de'?(a.level?'Bisheriger PackCard-Ausschnitt':'Ausschnitt-Vergleich'):(a.level?'Current PackCard centre crop':'Crop comparison')}</figcaption><div class="ratio-frame crop"><img src="${a.asset}" alt="${esc(a.subject??title(a))}"></div></figure></div><p class="detail-note">${catalogState.locale==='ko'?'100 CSS px · 먼저 소재가 읽히는지 확인하세요. 이미지는 크기·표시 영역만 다르게 보여주며 파일은 수정하지 않았습니다.':catalogState.locale==='de'?'100 CSS px · Sind die Gegenstände noch erkennbar? Nur die Anzeigegröße und der Ausschnitt ändern sich. Die Bilddatei bleibt unverändert.':'100 CSS px · Can you still recognise the objects? Only display size and cropping change. The original file stays unchanged.'}</p><img class="tiny-art" src="${a.asset}" alt="${catalogState.locale==='ko'?'100px 학습 카드':'100 px learning card'}"><p class="detail-note"><code>${esc(a.id)}</code></p><div class="detail-actions"><button data-back-detail>${ct('back')}</button></div>`;detail.scrollTop=0;}
document.addEventListener('click',e=>{const link=e.target.closest('[data-prototype-route]');if(link&&params.get('embed')==='1'){e.preventDefault();window.parent.postMessage({soriReviewRoute:link.dataset.prototypeRoute},location.origin);return;}const b=e.target.closest('button');if(!b)return;if(b.dataset.mode){setMode(b.dataset.mode);return;}if(b.dataset.level){catalogState.level=b.dataset.level;renderCatalog();document.querySelector(`[data-level="${catalogState.level}"]`)?.focus({preventScroll:true});return;}if(b.dataset.section){catalogState.section=b.dataset.section;renderCatalog();document.querySelector(`[data-section="${catalogState.section}"]`)?.focus({preventScroll:true});return;}if(b.dataset.item){showItem(b.dataset.item);return;}if(b.hasAttribute('data-close')){detail.close();return;}if(b.hasAttribute('data-compare')){showComparison();return;}if(b.hasAttribute('data-back-detail')){const a=focusedItem;detail.close();showItem(a.id);return;}if(b.hasAttribute('data-open-packs')){detail.close();if(params.get('embed')==='1')window.parent.postMessage({soriReviewRoute:'packs'},location.origin);else setMode('packs');return;}if(b.dataset.nav!==undefined){const n=Number(b.dataset.nav);if(n===1||n===2)setMode(n===1?'learn':'games');else location.href=`index.html?view=${['today','learn','games','hanok','gye'][n]}&lang=${catalogState.locale}`;}});
document.addEventListener('input',e=>{if(e.target.id==='pack-search'){catalogState.search=e.target.value;renderPackGrid();}});
document.addEventListener('change',e=>{if(['catalog-locale','phone-locale'].includes(e.target.id)){if(detail.open)detail.close();catalogState.locale=e.target.value;renderCatalog();}if(e.target.id==='catalog-reduce')document.body.classList.toggle('reduced',e.target.checked);if(e.target.id==='catalog-complete'){catalogState.completed=e.target.checked;renderCatalog();}});
detail.addEventListener('click',e=>{if(e.target===detail)detail.close();});
window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===window.parent&&typeof event.data?.soriReviewMotion==='boolean')document.body.classList.toggle('reduced',event.data.soriReviewMotion);});
fetch('catalog-data.json').then(r=>{if(!r.ok)throw new Error('inventory');return r.json();}).then(d=>{inventory=d;renderCatalog();if(params.get('open')&&inventory.activities.some(a=>a.id===params.get('open')))showItem(params.get('open'));document.documentElement.dataset.ready='true';}).catch(()=>{catalogScreen.innerHTML='<div class="catalog-page"><h2>목록을 불러오지 못했습니다.</h2><p>로컬 검토 서버에서 다시 열어 주세요.</p></div>';});
